var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[e]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.polyfill=function(a,e,c,b){if(e){c=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var h=a[b];h in c||(c[h]={});c=c[h]}a=a[a.length-1];b=c[a];e=e(b);e!=b&&null!=e&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,b){$jscomp.initSymbolIterator();c=null!=c?c:function(d){return d};var e=[],f=a[Symbol.iterator];if("function"==typeof f)for(a=f.call(a);!(f=a.next()).done;)e.push(c.call(b,f.value));else for(var f=a.length,l=0;l<f;l++)e.push(c.call(b,a[l]));return e}},"es6-impl","es3");$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(a,e){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,b={next:function(){if(c<a.length){var h=c++;return{value:e(h,a[h]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var e=a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,e){return Object.prototype.hasOwnProperty.call(a,e)};
$jscomp.polyfill("WeakMap",function(a){function e(a){$jscomp.owns(a,b)||$jscomp.defineProperty(a,b,{value:{}})}function c(a){var d=Object[a];d&&(Object[a]=function(a){e(a);return d(a)})}if(function(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),d=Object.seal({}),g=new a([[c,2],[d,3]]);if(2!=g.get(c)||3!=g.get(d))return!1;g["delete"](c);g.set(d,4);return!g.has(c)&&4==g.get(d)}catch(k){return!1}}())return a;var b="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");
c("seal");var h=0,f=function(a){this.id_=(h+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};f.prototype.set=function(a,d){e(a);if(!$jscomp.owns(a,b))throw Error("WeakMap key fail: "+a);a[b][this.id_]=d;return this};f.prototype.get=function(a){return $jscomp.owns(a,b)?a[b][this.id_]:void 0};f.prototype.has=function(a){return $jscomp.owns(a,b)&&$jscomp.owns(a[b],this.id_)};f.prototype["delete"]=
function(a){return $jscomp.owns(a,b)&&$jscomp.owns(a[b],this.id_)?delete a[b][this.id_]:!1};return f},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(a){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),c=new a($jscomp.makeIterator([[d,"s"]]));if("s"!=c.get(d)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var b=c.entries(),e=b.next();if(e.done||e.value[0]!=d||"s"!=e.value[1])return!1;e=b.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!b.next().done?!1:!0}catch(p){return!1}}())return a;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var e=new WeakMap,c=function(a){this.data_={};this.head_=f();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};c.prototype.set=function(a,c){var d=b(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=c:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:c},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};c.prototype["delete"]=
function(a){a=b(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=f();this.size=0};c.prototype.has=function(a){return!!b(this,a).entry};c.prototype.get=function(a){return(a=b(this,a).entry)&&a.value};c.prototype.entries=function(){return h(this,function(a){return[a.key,
a.value]})};c.prototype.keys=function(){return h(this,function(a){return a.key})};c.prototype.values=function(){return h(this,function(a){return a.value})};c.prototype.forEach=function(a,c){for(var d=this.entries(),b;!(b=d.next()).done;)b=b.value,a.call(c,b[1],b[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var b=function(a,c){var d;d=c&&typeof c;"object"==d||"function"==d?e.has(c)?d=e.get(c):(d=""+ ++l,e.set(c,d)):d="p_"+c;var b=a.data_[d];if(b&&$jscomp.owns(a.data_,d))for(var f=0;f<
b.length;f++){var g=b[f];if(c!==c&&g.key!==g.key||c===g.key)return{id:d,list:b,index:f,entry:g}}return{id:d,list:b,index:-1,entry:void 0}},h=function(a,c){var d=a.head_;return $jscomp.iteratorPrototype(function(){if(d){for(;d.head!=a.head_;)d=d.previous;for(;d.next!=d.head;)return d=d.next,{done:!1,value:c(d)};d=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.previous=a.next=a.head=a},l=0;return c},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(a){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a($jscomp.makeIterator([c]));if(!b.has(c)||1!=b.size||b.add(c)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var e=b.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(l){return!1}}())return a;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)this.add(c.value)}this.size=this.map_.size};e.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};e.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};e.prototype.clear=function(){this.map_.clear();this.size=0};e.prototype.has=function(a){return this.map_.has(a)};e.prototype.entries=
function(){return this.map_.entries()};e.prototype.values=function(){return this.map_.values()};e.prototype[Symbol.iterator]=e.prototype.values;e.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(e){return a.call(b,e,e,c)})};return e},"es6-impl","es3");
var AJAX=function(){return{GET:function(a,e){e=void 0===e?null:e;var c=new XMLHttpRequest;c.onreadystatechange=function(){4==this.readyState&&200==this.status&&null!==e&&e(this.responseText)};c.open("GET",a,!0);c.send()}}}(),MusicStorageManager=function(){return{getPiece:function(a){a=localStorage.getItem("_piece_"+a);return null===a?null:Piece.createFromString(a)},setPiece:function(a){localStorage.setItem("_piece_"+a.id,JSON.stringify(a))}}}(),IndexPage=function(){function a(){var a=g.getNextBar(k),
d=0;null!==a&&(d=a.first);AJAX.GET(window.location.pathname+"?p="+g.getId()+"&v="+d,function(){})}function e(a){b(a.clientX,a.clientY)}function c(a){a=null;for(var c=document.querySelectorAll("body > div#container > div#notes > div.note"),b=0;b<c.length;b++)if(c[b].classList.contains("selected")){a=c[b];break}if(null!==a){a.classList.remove("selected");ViolinSimulator.stop();var c=g.getBar(k),b=k-c.first,e=c.verticals[b],e=Array.from(e.notes.keys());"playAllNotesAndMoveNext"!==a.id?(e=[parseInt(a.getAttribute("value"))],
d.changeNotesColor(b,e,"green"),d.changeNotesSize(b,e,1)):(d.changeNotesColor(b,e,"black"),d.changeNotesSize(b,e,1),k+=1,a=!1,k>=c.first+c.verticals.length&&(a=!0),k>=g.getTotalVerticals()&&(k=0),a?window.location=window.location.pathname+"?p="+g.getId()+"&v="+k:(b+=1,e=c.verticals[b],e=Array.from(e.notes.keys()),d.changeNotesColor(b,e,"green"),d.changeNotesSize(b,e,1),h()))}}function b(a,c){for(var b=null,e=document.querySelectorAll("body > div#container > div#notes > div.note"),f=0;f<e.length;f++){var l=
e[f].getBoundingClientRect();if(a>=l.left&&a<=l.right&&c>=l.top&&c<=l.bottom){b=e[f];break}}if(null!==b)if(b.classList.contains("note")||(b=b.parentNode),b.classList.add("selected"),null===g)m={x:a,y:c};else{var f=g.getBar(k),e=k-f.first,l=f.verticals[e],h=[],n=[];if("playAllNotesAndMoveNext"===b.id)for(f=0;f<l.notes.length;f++)h.push(Note.getNoteFrequency(l.notes[f])),n.push(f);else b=parseInt(b.getAttribute("value")),h.push(Note.getNoteFrequency(l.notes[b])),n.push(b);ViolinSimulator.play(h);d.changeNotesColor(e,
n,"red");d.changeNotesSize(e,n,1.3)}}function h(){for(var a=document.querySelectorAll("body > div#container > div#notes > div.note"),b=0;b<a.length;b++)"playAllNotesAndMoveNext"!==a[b].id&&a[b].parentNode.removeChild(a[b]);for(var a=document.querySelector("body > div#container > div#notes"),b=g.getBar(k),c=b.verticals[k-b.first],b=c.notes.length-1;0<=b;b--){var d=document.createElement("div");d.classList.add("note");d.setAttribute("value",""+b);var e=Note.getNoteDetail(c.notes[b]);d.innerHTML='<div class="natural">'+
e.natural+'</div><div class="accidental">'+e.accidental+'</div><div class="octave">'+e.octave+"</div>";a.appendChild(d)}}function f(){null!==g&&(d.setPiece(g),d.setFocus(k),d.display(),h())}function l(){k>=g.getTotalVerticals()&&(k=0);f();var a=g.getBar(k),c=k-a.first;d.changeNotesColor(c,Array.from(a.verticals[c].notes.keys()),"green");null!==m&&b(m.x,m.y)}var d=null,g=null,k=0,q="mousedown",p="mouseup",m=null;"ontouchstart"in window&&(q="touchstart",p="touchend");return{initialize:function(b){var f=
b.p||"default";k=parseInt(b.v)||0;m=b.unhandledEvent||null;window.addEventListener(q,e);window.addEventListener(p,c);d=new MusicPlayer(document.querySelector("body > div#container > div#music"));g=MusicStorageManager.getPiece(f);null!==g?(l(),a()):AJAX.GET(App.getPiecesPath()+f+".json",function(b){g=Piece.createFromString(b);MusicStorageManager.setPiece(g);l();a()})},draw:f,getPath:function(){return"/index.html"}}}(),CatalogPage=function(){function a(){AJAX.GET(App.getPiecesPath()+"indexes.json",
function(a){var d=JSON.parse(a);a=d.scales;1==h.length?d.hasOwnProperty(h[0])&&(a=d[h[0]]):1<h.length&&"scales"==h[0]&&d.scales.hasOwnProperty(h[1])&&(a=d.scales[h[1]]);b={query:h,tiles:[]};for(var g in a)a.hasOwnProperty(g)&&(d=a[g],"string"==typeof d?b.tiles.push({type:"piece",title:g,detail:"Scale "+g+" on key "+h[0],data:{id:d}}):b.tiles.push({type:"folder",title:g,detail:"All scales for key "+g,id:g}));for(g=0;g<b.tiles.length;g++)a=b.tiles[g],"folder"==a.type?(d=document.createElement("div"),
d.classList.add("tile"),d.classList.add("folder"),d.setAttribute("data",a.id),d.innerHTML=a.title,d.addEventListener("click",e),f.append(d)):(d=document.createElement("div"),d.classList.add("tile"),d.classList.add("piece"),d.setAttribute("data",a.data.id),d.innerHTML=a.title,d.addEventListener("click",c),f.append(d),a.hasOwnProperty("data"))})}function e(a){a=a.target.getAttribute("data");window.location=App.getPagePath(CatalogPage)+"?q="+encodeURIComponent("scales,"+a)}function c(a){window.location=
App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a.target.getAttribute("data"))}var b={},h="",f=null;return{initialize:function(c){f=document.querySelector("div#tiles");window.hasOwnProperty("catalogSnapshot")&&(b=window.catalogSnapshot);parseInt(c.p);h=Array.from(new Set((c.q||"").split(",")));a()},draw:function(){},getPath:function(){return"/catalog.html"}}}(),App=function(){var a=null;return{initialize:function(e){e=void 0===e?{}:e;for(var c=window.location.pathname,b=window.location.search,
b=("?"===b[0]?b.substr(1):b).split("&"),h=0;h<b.length;h++){var f=b[h].split("=");e[decodeURIComponent(f[0])]=decodeURIComponent(f[1]||"")}0===c.indexOf("/v1"+CatalogPage.getPath())?(CatalogPage.initialize(e),a=CatalogPage):(IndexPage.initialize(e),a=IndexPage);window.addEventListener("resize",function(){a.draw()})},getPagePath:function(a){return"/v1"+a.getPath()},getPiecesPath:function(){return"/v1/pieces/"}}}();
