var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,b,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[b]=a.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var b=0;return $jscomp.iteratorPrototype(function(){return b<c.length?{done:!1,value:c[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.polyfill=function(c,b,a,g){if(b){a=$jscomp.global;c=c.split(".");for(g=0;g<c.length-1;g++){var f=c[g];f in a||(a[f]={});a=a[f]}c=c[c.length-1];g=a[c];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(a,c,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.from",function(c){return c?c:function(b,a,c){$jscomp.initSymbolIterator();a=null!=a?a:function(d){return d};var f=[],e=b[Symbol.iterator];if("function"==typeof e)for(b=e.call(b);!(e=b.next()).done;)f.push(a.call(c,e.value));else for(var e=b.length,h=0;h<e;h++)f.push(a.call(c,b[h]));return f}},"es6-impl","es3");$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(c,b){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var a=0,g={next:function(){if(a<c.length){var f=a++;return{value:b(f,c[f]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6-impl","es3");
$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var b=c[Symbol.iterator];return b?b.call(c):$jscomp.arrayIterator(c)};$jscomp.owns=function(c,b){return Object.prototype.hasOwnProperty.call(c,b)};
$jscomp.polyfill("WeakMap",function(c){function b(a){$jscomp.owns(a,g)||$jscomp.defineProperty(a,g,{value:{}})}function a(a){var d=Object[a];d&&(Object[a]=function(a){b(a);return d(a)})}if(function(){if(!c||!Object.seal)return!1;try{var a=Object.seal({}),d=Object.seal({}),b=new c([[a,2],[d,3]]);if(2!=b.get(a)||3!=b.get(d))return!1;b["delete"](a);b.set(d,4);return!b.has(a)&&4==b.get(d)}catch(l){return!1}}())return c;var g="$jscomp_hidden_"+Math.random().toString().substring(2);a("freeze");a("preventExtensions");
a("seal");var f=0,e=function(a){this.id_=(f+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};e.prototype.set=function(a,d){b(a);if(!$jscomp.owns(a,g))throw Error("WeakMap key fail: "+a);a[g][this.id_]=d;return this};e.prototype.get=function(a){return $jscomp.owns(a,g)?a[g][this.id_]:void 0};e.prototype.has=function(a){return $jscomp.owns(a,g)&&$jscomp.owns(a[g],this.id_)};e.prototype["delete"]=
function(a){return $jscomp.owns(a,g)&&$jscomp.owns(a[g],this.id_)?delete a[g][this.id_]:!1};return e},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(c){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new c($jscomp.makeIterator([[a,"s"]]));if("s"!=b.get(a)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var f=b.entries(),e=f.next();if(e.done||e.value[0]!=a||"s"!=e.value[1])return!1;e=f.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!f.next().done?!1:!0}catch(n){return!1}}())return c;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var b=new WeakMap,a=function(a){this.data_={};this.head_=e();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};a.prototype.set=function(a,b){var d=g(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=b:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};a.prototype["delete"]=
function(a){a=g(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};a.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=e();this.size=0};a.prototype.has=function(a){return!!g(this,a).entry};a.prototype.get=function(a){return(a=g(this,a).entry)&&a.value};a.prototype.entries=function(){return f(this,function(a){return[a.key,
a.value]})};a.prototype.keys=function(){return f(this,function(a){return a.key})};a.prototype.values=function(){return f(this,function(a){return a.value})};a.prototype.forEach=function(a,b){for(var f=this.entries(),d;!(d=f.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};a.prototype[Symbol.iterator]=a.prototype.entries;var g=function(a,f){var d;d=f&&typeof f;"object"==d||"function"==d?b.has(f)?d=b.get(f):(d=""+ ++h,b.set(f,d)):d="p_"+f;var e=a.data_[d];if(e&&$jscomp.owns(a.data_,d))for(var c=0;c<
e.length;c++){var g=e[c];if(f!==f&&g.key!==g.key||f===g.key)return{id:d,list:e,index:c,entry:g}}return{id:d,list:e,index:-1,entry:void 0}},f=function(a,b){var f=a.head_;return $jscomp.iteratorPrototype(function(){if(f){for(;f.head!=a.head_;)f=f.previous;for(;f.next!=f.head;)return f=f.next,{done:!1,value:b(f)};f=null}return{done:!0,value:void 0}})},e=function(){var a={};return a.previous=a.next=a.head=a},h=0;return a},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(c){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new c($jscomp.makeIterator([a]));if(!b.has(a)||1!=b.size||b.add(a)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var f=b.entries(),e=f.next();if(e.done||e.value[0]!=a||e.value[1]!=a)return!1;e=f.next();return e.done||e.value[0]==a||4!=e.value[0].x||e.value[1]!=e.value[0]?!1:f.next().done}catch(h){return!1}}())return c;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};b.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};b.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};b.prototype.clear=function(){this.map_.clear();this.size=0};b.prototype.has=function(a){return this.map_.has(a)};b.prototype.entries=
function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var f=this;this.map_.forEach(function(e){return a.call(b,e,e,f)})};return b},"es6-impl","es3");
var ViolinSimulator=function(){function c(){if(null!=b)return!0;if("AudioContext"in window)b=new AudioContext;else if("webkitAudioContext"in window)b=new webkitAudioContext;else return b=null,!1;a=b.createGain();a.gain.value=0;a.connect(b.destination);return!0}var b=null,a=null,g=[];return{play:function(f){c();for(var e=0;e<f.length;e++){var h=b.createOscillator();h.frequency.value=f[e];var d=h,k=Math.PI,l=new Float32Array(12),m=new Float32Array(12),n=[.49,.995,.94,.425,.48,0,.365,.04,.085,0,.09,
0],k=[0,0,k/2,0,k/2,0,k/2,0,k/2,0,k/2,0];l[0]=0;m[0]=0;for(var p=1;12>p;p++)l[p]=n[p]*n[0]*Math.cos(k[p]),m[p]=n[p]*n[0]*Math.sin(k[p]);l=b.createPeriodicWave(m,l);d.setPeriodicWave(l);h.connect(a);h.start(0);g.push(h)}a.gain.linearRampToValueAtTime(0,b.currentTime);a.gain.linearRampToValueAtTime(.5,b.currentTime+.05)},stop:function(){c();a.gain.linearRampToValueAtTime(.5,b.currentTime);a.gain.linearRampToValueAtTime(0,b.currentTime+.05);setTimeout(function(){for(var b=0;b<g.length;b++){var e=g[b];
e.stop(0);e.disconnect(a)}g=[]},50)},playAndStop:function(a,b,c){}}}(),AJAX=function(){return{GET:function(c,b){b=void 0===b?null:b;var a=new XMLHttpRequest;a.onreadystatechange=function(){4==this.readyState&&200==this.status&&null!==b&&b(this.responseText)};a.open("GET",c,!0);a.send()}}}(),MusicStorageManager=function(){return{getPiece:function(c){c=localStorage.getItem("_piece_"+c);return null===c?null:Piece.createFromString(c)},setPiece:function(c){localStorage.setItem("_piece_"+c.id,JSON.stringify(c))}}}(),
IndexPage=function(){function c(){var a=k.getNextBar(l),b=0;null!==a&&(b=a.first);AJAX.GET(window.location.pathname+"?p="+k.getId()+"&v="+b,function(){})}function b(a){g(a.clientX,a.clientY)}function a(a){a=null;for(var b=document.querySelectorAll("body > div#container > div#notes > div.note"),c=0;c<b.length;c++)if(b[c].classList.contains("selected")){a=b[c];break}if(null!==a){a.classList.remove("selected");ViolinSimulator.stop();var b=k.getBar(l),c=l-b.first,e=b.verticals[c],e=Array.from(e.notes.keys());
"playAllNotesAndMoveNext"!==a.id?(e=[parseInt(a.getAttribute("value"))],d.changeNotesColor(c,e,"green"),d.changeNotesSize(c,e,1)):(d.changeNotesColor(c,e,"black"),d.changeNotesSize(c,e,1),l+=1,a=!1,l>=b.first+b.verticals.length&&(a=!0),l>=k.getTotalVerticals()&&(l=0),a?window.location=window.location.pathname+"?p="+k.getId()+"&v="+l:(c+=1,e=b.verticals[c],e=Array.from(e.notes.keys()),d.changeNotesColor(c,e,"green"),d.changeNotesSize(c,e,1),f()))}}function g(a,b){for(var f=null,c=document.querySelectorAll("body > div#container > div#notes > div.note"),
e=0;e<c.length;e++){var g=c[e].getBoundingClientRect();if(a>=g.left&&a<=g.right&&b>=g.top&&b<=g.bottom){f=c[e];break}}if(null!==f)if(f.classList.contains("note")||(f=f.parentNode),f.classList.add("selected"),null===k)p={x:a,y:b};else{var e=k.getBar(l),c=l-e.first,g=e.verticals[c],h=[],m=[];if("playAllNotesAndMoveNext"===f.id)for(e=0;e<g.notes.length;e++)h.push(Note.getNoteFrequency(g.notes[e])),m.push(e);else f=parseInt(f.getAttribute("value")),h.push(Note.getNoteFrequency(g.notes[f])),m.push(f);
ViolinSimulator.play(h);d.changeNotesColor(c,m,"red");d.changeNotesSize(c,m,1.3)}}function f(){for(var a=document.querySelectorAll("body > div#container > div#notes > div.note"),b=0;b<a.length;b++)"playAllNotesAndMoveNext"!==a[b].id&&a[b].parentNode.removeChild(a[b]);for(var a=document.querySelector("body > div#container > div#notes"),b=k.getBar(l),f=b.verticals[l-b.first],b=f.notes.length-1;0<=b;b--){var e=document.createElement("div");e.classList.add("note");e.setAttribute("value",""+b);var c=Note.getNoteDetail(f.notes[b]);
e.innerHTML='<div class="natural">'+c.natural+'</div><div class="accidental">'+c.accidental+'</div><div class="octave">'+c.octave+"</div>";a.appendChild(e)}}function e(){null!==k&&(d.setPiece(k),d.setFocus(l),d.display(),f())}function h(){l>=k.getTotalVerticals()&&(l=0);e();var a=k.getBar(l),b=l-a.first;d.changeNotesColor(b,Array.from(a.verticals[b].notes.keys()),"green");null!==p&&g(p.x,p.y)}var d=null,k=null,l=0,m="mousedown",n="mouseup",p=null;"ontouchstart"in window&&(m="touchstart",n="touchend");
return{initialize:function(f){var e=f.p||"default";l=parseInt(f.v)||0;p=f.unhandledEvent||null;window.addEventListener(m,b);window.addEventListener(n,a);d=new MusicPlayer(document.querySelector("body > div#container > div#music"));k=MusicStorageManager.getPiece(e);null!==k?(h(),c()):AJAX.GET(App.getPiecesPath()+e+".json",function(a){k=Piece.createFromString(a);MusicStorageManager.setPiece(k);h();c()})},draw:e,getPath:function(){return"/index.html"}}}(),CatalogPage=function(){function c(){AJAX.GET(App.getPiecesPath()+
"indexes.json",function(c){var d=JSON.parse(c);c=d.scales;1==f.length?d.hasOwnProperty(f[0])&&(c=d[f[0]]):1<f.length&&"scales"==f[0]&&d.scales.hasOwnProperty(f[1])&&(c=d.scales[f[1]]);g={query:f,tiles:[]};for(var h in c)c.hasOwnProperty(h)&&(d=c[h],"string"==typeof d?g.tiles.push({type:"piece",title:h,detail:"Scale "+h+" on key "+f[0],data:{id:d}}):g.tiles.push({type:"folder",title:h,detail:"All scales for key "+h,id:h}));for(h=0;h<g.tiles.length;h++)c=g.tiles[h],"folder"==c.type?(d=document.createElement("div"),
d.classList.add("tile"),d.classList.add("folder"),d.setAttribute("data",c.id),d.innerHTML=c.title,d.addEventListener("click",b),e.append(d)):(d=document.createElement("div"),d.classList.add("tile"),d.classList.add("piece"),d.setAttribute("data",c.data.id),d.innerHTML=c.title,d.addEventListener("click",a),e.append(d),c.hasOwnProperty("data"))})}function b(a){a=a.target.getAttribute("data");window.location=App.getPagePath(CatalogPage)+"?q="+encodeURIComponent("scales,"+a)}function a(a){window.location=
App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a.target.getAttribute("data"))}var g={},f="",e=null;return{initialize:function(a){e=document.querySelector("div#tiles");window.hasOwnProperty("catalogSnapshot")&&(g=window.catalogSnapshot);parseInt(a.p);f=Array.from(new Set((a.q||"").split(",")));c()},draw:function(){},getPath:function(){return"/catalog.html"}}}(),App=function(){var c=null;return{initialize:function(b){b=void 0===b?{}:b;for(var a=window.location.pathname,g=window.location.search,
g=("?"===g[0]?g.substr(1):g).split("&"),f=0;f<g.length;f++){var e=g[f].split("=");b[decodeURIComponent(e[0])]=decodeURIComponent(e[1]||"")}0===a.indexOf("/ve"+CatalogPage.getPath())?(CatalogPage.initialize(b),c=CatalogPage):(IndexPage.initialize(b),c=IndexPage);window.addEventListener("resize",function(){c.draw()})},getPagePath:function(b){return"/ve"+b.getPath()},getPiecesPath:function(){return"/ve/pieces/"}}}(),Note=function(){function c(a){var c={A:[0,1],"B\ud834\udd2b":[0,1],"G\ud834\udd2a":[0,
1],"A\u266f":[0,2],"B\u266d":[0,2],B:[0,3],"A\ud834\udd2a":[0,3],"C\u266d":[0,3],C:[1,4],"D\ud834\udd2b":[1,4],"B\u266f":[0,4],"C\u266f":[1,5],"D\u266d":[1,5],D:[1,6],"E\ud834\udd2b":[1,6],"C\ud834\udd2a":[1,6],"D\u266f":[1,7],"E\u266d":[1,7],"F\ud834\udd2b":[1,7],E:[1,8],"F\u266d":[1,8],"D\ud834\udd2a":[1,8],F:[1,9],"G\ud834\udd2b":[1,9],"E\u266f":[1,9],"F\u266f":[1,10],"G\u266d":[1,10],G:[1,11],"A\ud834\udd2b":[1,11],"F\ud834\udd2a":[1,11],"G\u266f":[1,12],"A\u266d":[1,12]};a=b(a);var f=a.natural+
a.accidental;return c.hasOwnProperty(f)?(c=c[f],c[1]+12*(a.octave-c[0])):-1}function b(a){var b={natural:"",octave:-1,accidental:""};if(0>=a.length)return b;b.natural=a[0];b.octave=parseInt(a.substring(a.length-1,a.length));b.accidental="";b.accidentalASCII="";2<a.length&&(1==a.indexOf("\u266d")?(b.accidental="\u266d",b.accidentalASCII="b"):1==a.indexOf("\u266f")?(b.accidental="\u266f",b.accidentalASCII="#"):1==a.indexOf("\ud834\udd2b")?(b.accidental="\ud834\udd2b",b.accidentalASCII="bb"):1==a.indexOf("\ud834\udd2a")&&
(b.accidental="\ud834\udd2a",b.accidentalASCII="##"));return b}function a(a,b){var c=g[a],f="";"\u266d"==c.sharpflat&&"BEADGCF".indexOf(b)<c.amount?f="\u266d":"\u266f"==c.sharpflat&&"FCGDAEB".indexOf(b)<c.amount&&(f="\u266f");return f}var g={"D\u266d":{index:0,sharpflat:"\u266d",amount:5},"G\u266f":{index:1,sharpflat:"\u266f",amount:8},"b\u266d":{index:2,sharpflat:"\u266d",amount:5},"C\u266d":{index:3,sharpflat:"\u266d",amount:7},e:{index:4,sharpflat:"\u266f",amount:1},"C\u266f":{index:5,sharpflat:"\u266f",
amount:7},B:{index:6,sharpflat:"\u266f",amount:5},g:{index:7,sharpflat:"\u266d",amount:2},f:{index:8,sharpflat:"\u266d",amount:4},"F\u266d":{index:9,sharpflat:"\u266d",amount:8},a:{index:10,sharpflat:"\u266f",amount:0},G:{index:11,sharpflat:"\u266f",amount:1},"B\u266d":{index:12,sharpflat:"\u266d",amount:2},"e\u266f":{index:13,sharpflat:"\u266f",amount:8},"a\u266f":{index:14,sharpflat:"\u266f",amount:7},"d\u266d":{index:15,sharpflat:"\u266d",amount:8},d:{index:16,sharpflat:"\u266d",amount:1},"F\u266f":{index:17,
sharpflat:"\u266f",amount:6},"g\u266f":{index:18,sharpflat:"\u266f",amount:5},C:{index:19,sharpflat:"\u266f",amount:0},D:{index:20,sharpflat:"\u266f",amount:2},"A\u266d":{index:21,sharpflat:"\u266d",amount:4},A:{index:22,sharpflat:"\u266f",amount:3},"E\u266d":{index:23,sharpflat:"\u266d",amount:3},"f\u266f":{index:24,sharpflat:"\u266f",amount:3},c:{index:25,sharpflat:"\u266d",amount:3},b:{index:26,sharpflat:"\u266f",amount:2},F:{index:27,sharpflat:"\u266d",amount:1},E:{index:28,sharpflat:"\u266f",
amount:4},"G\u266d":{index:29,sharpflat:"\u266d",amount:6},"c\u266f":{index:30,sharpflat:"\u266f",amount:4},"e\u266d":{index:31,sharpflat:"\u266d",amount:6},"a\u266d":{index:32,sharpflat:"\u266d",amount:7},"d\u266f":{index:33,sharpflat:"\u266f",amount:6}};return{flat:"\u266d",sharp:"\u266f",flatflat:"\ud834\udd2b",sharpsharp:"\ud834\udd2a",getNoteOrder:c,getNoteFrequency:function(a){a=c(a);return 0>a?0:440*Math.pow(Math.pow(2,1/12),a-49)},getNoteDetail:b,getDefaultAccidental:a,getDefaultAccidentalASCII:function(b,
c){return a(b,c).replace("\u266f","#").replace("\u266d","b")},getFirstNoteInKey:function(a){a=a.substring(0,1);return 0<="GAB".indexOf(a)?a+"3":a+"4"}}}(),Piece=function(){function c(b){function a(a){for(var b=0;b<c.bars.length;b++)if(c.bars[b].first<=a&&a<c.bars[b].first+c.bars[b].verticals.length)return c.bars[b];return null}var c=JSON.parse(b);return{getId:function(){return c.id},getBar:a,getNextBar:function(b){b=a(b);return a(b.first+b.verticals.length)},getTotalVerticals:function(){var a=c.bars[c.bars.length-
1];return a.first+a.verticals.length}}}return{createFromString:function(b){return new c(b)}}}(),VFUtility=function(){function c(b){b=Note.getNoteDetail(b);return b.natural+b.accidentalASCII+"/"+b.octave}return{toVFKeySignature:function(b){var a=b.replace(Note.flat,"b").replace(Note.sharp,"#");b!==b.toUpperCase()&&(a=a.toUpperCase()+"m");return a},prepareStaveNote:function(b,a,g){for(var f,e,h,d=[],k=0;k<a.notes.length;k++)d.push(c(a.notes[k]));d=new Vex.Flow.StaveNote({keys:d,duration:a.duration});
for(k=0;k<a.notes.length;k++)a:{var l=b,m=d,n=k,p=g;h=m.keys[n];var q=h.indexOf("/");f=h.substring(0,1);e=parseInt(h.substring(q+1));h=h.substring(1,q);q=f+e;e=!1;if(p.hasOwnProperty(q))if(p[q]==h)break a;else e=!0;p[q]=h;"bb"==h?m.addAccidental(n,new Vex.Flow.Accidental("bb")):"##"==h?m.addAccidental(n,new Vex.Flow.Accidental("##")):(f=Note.getDefaultAccidentalASCII(l,f),"#"==f?"#"==h?e&&m.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==h?m.addAccidental(n,new Vex.Flow.Accidental("b")):m.addAccidental(n,
new Vex.Flow.Accidental("n")):"b"==f?"#"==h?m.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==h?e&&m.addAccidental(n,new Vex.Flow.Accidental("b")):m.addAccidental(n,new Vex.Flow.Accidental("n")):"#"==h?m.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==h?m.addAccidental(n,new Vex.Flow.Accidental("b")):e&&m.addAccidental(n,new Vex.Flow.Accidental("n")))}b=a.duration;"dd"==b.substring(b.length-2)?d.addDotToAll().addDotToAll():(a=a.duration,"d"==a.substring(a.length-1)&&d.addDotToAll());return d}}}();
function MusicPlayer(c){function b(a){for(var b=a.first,c=[],f=0;f<a.verticals.length;f++){for(var d=[],e=0;e<a.verticals[f].notes.length;e++)d.push({color:"black",size:"1.0"});c.push(d)}return{isOnBar:function(a){return b===a.first},changeNotesSize:function(a,b,f){for(var d=0;d<b.length;d++)c[a][b[d]].size=f},changeNotesColor:function(a,b,f){for(var d=0;d<b.length;d++)c[a][b[d]].color=f},drawAllOrnaments:function(){for(var a=0;a<c.length;a++)for(var b=0;b<c[a].length;b++){if("1.0"!==c[a][b].size){var d=
g(a,[b]);d[0].style.transform="scale("+c[a][b].size+")";d[0].style.transformOrigin="50% 50%"}"black"!==c[a][b].color&&(d=g(a,[b]),d[0].setAttribute("fill",c[a][b].color))}}}}function a(){var a=document.createElement("div");e.innerHTML="";e.appendChild(a);var b=new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.SVG),c=b.getContext();b.resize(a.clientWidth,a.clientHeight);c.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return c}function g(a,b){for(var c=document.querySelectorAll("#vf-"+d[a].attrs.id+
" g.vf-notehead path"),f=[],e=0;e<b.length;e++)f.push(c[b[e]]);return f}function f(a){var b=h.getBar(a);return a-b.first}var e=c,h=null,d=[],k=0,l=null;return{setPiece:function(a){h=a;k=0},setFocus:function(a){k=a},display:function(){var c=a(),f=new Vex.Flow.Stave(0,40,c.width),e=h.getBar(k);f.addClef("treble").addTimeSignature(e.time).addKeySignature(VFUtility.toVFKeySignature(e.key));f.setContext(c).draw();d=[];for(var g={},r=0;r<e.verticals.length;r++)d.push(VFUtility.prepareStaveNote(e.key,e.verticals[r],
g));g=Vex.Flow.Beam.generateBeams(d);Vex.Flow.Formatter.FormatAndDraw(c,f,d);g.forEach(function(a){a.setContext(c).draw()});null!==l&&l.isOnBar(e)?l.drawAllOrnaments():l=new b(e)},changeNotesSize:function(a,b,c){c=void 0===c?"1.0":c;a=f(a);for(var d=g(a,b),e=0;e<d.length;e++)d[e].style.transform="scale("+c+")",d[e].style.transformOrigin="50% 50%";l.changeNotesSize(a,b,c)},changeNotesColor:function(a,b,c){c=void 0===c?"black":c;a=f(a);for(var d=g(a,b),e=0;e<d.length;e++)d[e].setAttribute("fill",c);
l.changeNotesColor(a,b,c)}}};
