var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[e]=a.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var e=0;return $jscomp.iteratorPrototype(function(){return e<b.length?{done:!1,value:b[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.polyfill=function(b,e,a,c){if(e){a=$jscomp.global;b=b.split(".");for(c=0;c<b.length-1;c++){var h=b[c];h in a||(a[h]={});a=a[h]}b=b[b.length-1];c=a[b];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.from",function(b){return b?b:function(b,a,c){$jscomp.initSymbolIterator();a=null!=a?a:function(a){return a};var e=[],d=b[Symbol.iterator];if("function"==typeof d)for(b=d.call(b);!(d=b.next()).done;)e.push(a.call(c,d.value));else for(var d=b.length,l=0;l<d;l++)e.push(a.call(c,b[l]));return e}},"es6-impl","es3");$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();var e=b[Symbol.iterator];return e?e.call(b):$jscomp.arrayIterator(b)};
$jscomp.owns=function(b,e){return Object.prototype.hasOwnProperty.call(b,e)};
$jscomp.polyfill("WeakMap",function(b){function e(a){$jscomp.owns(a,c)||$jscomp.defineProperty(a,c,{value:{}})}function a(a){var m=Object[a];m&&(Object[a]=function(a){e(a);return m(a)})}if(function(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),m=Object.seal({}),d=new b([[a,2],[m,3]]);if(2!=d.get(a)||3!=d.get(m))return!1;d["delete"](a);d.set(m,4);return!d.has(a)&&4==d.get(m)}catch(f){return!1}}())return b;var c="$jscomp_hidden_"+Math.random().toString().substring(2);a("freeze");a("preventExtensions");
a("seal");var h=0,d=function(a){this.id_=(h+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};d.prototype.set=function(a,d){e(a);if(!$jscomp.owns(a,c))throw Error("WeakMap key fail: "+a);a[c][this.id_]=d;return this};d.prototype.get=function(a){return $jscomp.owns(a,c)?a[c][this.id_]:void 0};d.prototype.has=function(a){return $jscomp.owns(a,c)&&$jscomp.owns(a[c],this.id_)};d.prototype["delete"]=
function(a){return $jscomp.owns(a,c)&&$jscomp.owns(a[c],this.id_)?delete a[c][this.id_]:!1};return d},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(b){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),d=new b($jscomp.makeIterator([[a,"s"]]));if("s"!=d.get(a)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),e=c.next();if(e.done||e.value[0]!=a||"s"!=e.value[1])return!1;e=c.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!c.next().done?!1:!0}catch(p){return!1}}())return b;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var e=new WeakMap,a=function(a){this.data_={};this.head_=d();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};a.prototype.set=function(a,d){var b=c(this,a);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=d:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:d},b.list.push(b.entry),this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};a.prototype["delete"]=
function(a){a=c(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};a.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=d();this.size=0};a.prototype.has=function(a){return!!c(this,a).entry};a.prototype.get=function(a){return(a=c(this,a).entry)&&a.value};a.prototype.entries=function(){return h(this,function(a){return[a.key,
a.value]})};a.prototype.keys=function(){return h(this,function(a){return a.key})};a.prototype.values=function(){return h(this,function(a){return a.value})};a.prototype.forEach=function(a,d){for(var c=this.entries(),b;!(b=c.next()).done;)b=b.value,a.call(d,b[1],b[0],this)};a.prototype[Symbol.iterator]=a.prototype.entries;var c=function(a,d){var c;c=d&&typeof d;"object"==c||"function"==c?e.has(d)?c=e.get(d):(c=""+ ++l,e.set(d,c)):c="p_"+d;var b=a.data_[c];if(b&&$jscomp.owns(a.data_,c))for(var p=0;p<
b.length;p++){var n=b[p];if(d!==d&&n.key!==n.key||d===n.key)return{id:c,list:b,index:p,entry:n}}return{id:c,list:b,index:-1,entry:void 0}},h=function(a,d){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:d(c)};c=null}return{done:!0,value:void 0}})},d=function(){var a={};return a.previous=a.next=a.head=a},l=0;return a},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(b){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),c=new b($jscomp.makeIterator([a]));if(!c.has(a)||1!=c.size||c.add(a)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var e=c.entries(),d=e.next();if(d.done||d.value[0]!=a||d.value[1]!=a)return!1;d=e.next();return d.done||d.value[0]==a||4!=d.value[0].x||d.value[1]!=d.value[0]?!1:e.next().done}catch(l){return!1}}())return b;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)this.add(c.value)}this.size=this.map_.size};e.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};e.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};e.prototype.clear=function(){this.map_.clear();this.size=0};e.prototype.has=function(a){return this.map_.has(a)};e.prototype.entries=
function(){return this.map_.entries()};e.prototype.values=function(){return this.map_.values()};e.prototype[Symbol.iterator]=e.prototype.values;e.prototype.forEach=function(a,c){var b=this;this.map_.forEach(function(d){return a.call(c,d,d,b)})};return e},"es6-impl","es3");
var AboutPage=function(){return{initialize:function(b){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){Header.handleConfig()})},draw:function(){},getPath:function(){return"/about.html"}}}(),AJAX=function(){return{GET:function(b){var e=b.url,a=b.onSuccess||null,c=b.onFailure||null,h=new XMLHttpRequest;h.responseType=b.responseType||"";h.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==a&&a(this.response):null!==
c&&c(this.status))};h.open("GET",e,!0);h.send()}}}(),CatalogPage=function(){function b(){var b=[],a;for(a in localStorage)0===a.indexOf("_config_")&&b.push(JSON.parse(localStorage[a]));b.sort(function(a,d){return a.name>d.name?1:a.name<d.name?-1:0});b.splice(0,0,Locale.getDefaultConfig());var c="";for(a=0;a<b.length;a++)c+='<div class="tile" id="ID">NAME</div>'.replace("ID",b[a].id).replace("NAME",b[a].name);document.querySelector("body > div#container > div#tiles").innerHTML=c;b=document.querySelectorAll("body > div#container > div#tiles > div.tile");
for(a=0;a<b.length;a++)b[a].addEventListener("click",function(a){a=a.target.id;window.location=App.getPagePath(IndexPage)+"?c="+a})}return{initialize:function(e){document.querySelector("div#tiles");parseInt(e.p);Array.from(new Set((e.q||"").split(",")));b()},draw:function(){},getPath:function(){return"/catalog.html"}}}(),ConfigSettingPage=function(){function b(a){a=a.target.id;if("ok"===a)localStorage.setItem("_config_"+c.id,JSON.stringify(c));else if("cancel"===a){if(h.isDirty()&&!confirm("Exit without saving changes?"))return}else{confirm("Do you want to discard all the changes?")&&
(h.markClean(),c=JSON.parse(localStorage.getItem("_config_"+c.id)),document.querySelector("body > div#container > div#configSetting > div#configNameSetting > input#name").value=c.name);return}window.location=App.getPagePath(IndexPage)+"?c="+c.id}function e(a){a=a.target.id;if("clone"===a){a=c;a.name+=" copy";for(var b="",d=0;32>d;d++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));a.id=b;localStorage.setItem("_config_"+a.id,JSON.stringify(a));
window.location=App.getPagePath(IndexPage)+"?c="+a.id}else"delete"===a&&confirm("Do you want to delete this config?")&&(localStorage.removeItem("_config_"+c.id),window.location=App.getPagePath(CatalogPage))}function a(){var a=document.querySelector("body > div#container > div#configSetting > div#configNameSetting > input#name");a.value=c.name;a.addEventListener("change",function(){c.name=this.value;h.markDirty()});for(var l=document.querySelectorAll("body > div#container > div#configSetting > div#buttons > div.button"),
a=0;a<l.length;a++)l[a].addEventListener("click",b);l=document.querySelectorAll("body > div#container > div#configSetting > div#header > div#controls > div.control");for(a=0;a<l.length;a++)l[a].addEventListener("click",e)}var c=null,h=null;return{initialize:function(b){b=b.c;h=new DirtyManager([document.querySelector("body > div#container > div#configSetting > div#buttons > div.button#revert")]);"string"===typeof b&&/[a-zA-Z0-9]{32}/.test(b)&&"_config_"+b in localStorage?(b=localStorage.getItem("_config_"+
b),c=JSON.parse(b),a()):(alert("No config id. Please select a config."),window.location=App.getPagePath(CatalogPage))},draw:function(){},getPath:function(){return"/configSetting.html"}}}(),DirtyManager=function(b){var e=!1,a=b;return{markDirty:function(){e=!0;for(var b=0;b<a.length;b++)a[b].classList.remove("gray")},markClean:function(){e=!1;for(var b=0;b<a.length;b++)a[b].classList.remove("gray")},isDirty:function(){return e},setElements:function(b){a=b}}},Header=function(){function b(){var a;a=
App.getParams();var b="untitled";a.hasOwnProperty("c")?b=a.c:"lastConfigId"in sessionStorage&&(b=sessionStorage.lastConfigId);a=b;window.location=App.getPagePath(IndexPage)+"?c="+encodeURIComponent(a)}function e(){window.location=App.getPagePath(CatalogPage)}function a(){window.location=App.getPagePath(AboutPage)}var c=null,h=null;return{initialize:function(){c=document.querySelector("div#header > div#controls > div.control#config");h=document.querySelector("div#header > div#controls > div.control#open");
c.addEventListener("click",b);h.addEventListener("click",e);document.querySelector("div#header > div#title  > div#text").addEventListener("click",a);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",a);document.querySelector("div#header > div#title  > div#text").innerHTML=Locale.getApplicationTitle()},highlight:function(a){c.classList.remove("highlighted");h.classList.remove("highlighted");a===IndexPage?c.classList.add("highlighted"):a===CatalogPage&&h.classList.add("highlighted")},
handleConfig:b}}(),IndexPage=function(){function b(){var a=f.sequences[g.sequenceIndex],b="1";"1/1"!==a.time&&(b=g.indexInBar+1+a.time.substr(a.time.indexOf("/")));document.querySelector("body > div#container > div#tiles  > div.tile#s"+g.sequenceIndex+" > div#body > div#progress > div#bar > div#info").innerHTML=b;b=0;0!=a.time&&(b=(parseFloat(a.time.substr(0,a.time.indexOf("/")))-(g.indexInBar+1))/(g.indexInBar+1));document.querySelector("body > div#container > div#tiles  > div.tile#s"+g.sequenceIndex+
" > div#body > div#progress > div#bar > div#remaining").style.flexGrow=b;b=g.indexInSequence+1+"/";b=0===a.amount?b+"\u221e":b+a.amount;document.querySelector("body > div#container > div#tiles  > div.tile#s"+g.sequenceIndex+" > div#body > div#progress > div#sequence > div#info").innerHTML=b;b=100;0<a.amount&&(b=(a.amount-(g.indexInSequence+1))/(g.indexInSequence+1));document.querySelector("body > div#container > div#tiles  > div.tile#s"+g.sequenceIndex+" > div#body > div#progress > div#sequence > div#remaining").style.flexGrow=
b}function e(){var a=f.sequences[g.sequenceIndex];g.indexInBar+=1;if("1/1"===a.time||g.indexInBar>=parseInt(a.time.substr(0,a.time.indexOf("/"))))g.indexInBar=0,g.indexInSequence+=1;0!==a.amount&&g.indexInSequence>=a.amount&&(h(g.sequenceIndex),g.sequenceIndex+=1,g.indexInBar=0,g.indexInSequence=0);if(g.sequenceIndex>=f.sequences.length)return!0;c(g.sequenceIndex);return!1}function a(){var c=f.sequences[g.sequenceIndex],c=c.hasUniformBeats?c.beats[0]:c.beats[g.indexInBar];p=setTimeout(a,6E4/c);0===
g.indexInBar?Player.playFirst():Player.playOther();document.querySelector("body > div#container > div#tiles > div.tile#s"+g.sequenceIndex+" > div#body > div#bpm").innerHTML=""+c;b();e()&&(clearTimeout(p),g=null,setTimeout(function(){alert("Played!")},10))}function c(a){document.querySelector("body > div#container > div#tiles > div.tile#s"+a+" > div#body > div#header  > div#indicator").style.display="block";document.querySelector("body > div#container > div#tiles > div.tile#s"+a+" > div#body > div#progress").style.display=
"block"}function h(a){document.querySelector("body > div#container > div#tiles > div.tile#s"+a+" > div#body > div#header  > div#indicator").style.display="none";document.querySelector("body > div#container > div#tiles > div.tile#s"+a+" > div#body > div#progress").style.display="none"}function d(b){for(b=b.target;!b.classList.contains("tile");)b=b.parentNode;b=parseInt(b.id.substr(1));null!==g&&(h(g.sequenceIndex),clearTimeout(p));null===g||g.sequenceIndex!==b?(g={sequenceIndex:b,indexInBar:0,indexInSequence:0},
c(b),a()):window.location.reload()}function l(){for(var a=f,b="",c=0;32>c;c++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));a.id=b;for(a=1;;a++)if(b=f.name+" "+a,null===localStorage.getItem("_config_"+b)){f.name=b;break}localStorage.setItem("_config_"+f.id,JSON.stringify(f))}function m(a){a.stopPropagation();"default"===f.id&&l();window.location=App.getPagePath(ConfigSettingPage)+"?c="+f.id}function k(a){a.stopPropagation();"default"===f.id&&
l();for(element=a.target;element!==window&&!element.classList.contains("tile");)element=element.parentNode;window.location=App.getPagePath(SequenceSettingPage)+"?c="+f.id+"&s="+element.id.substr(1)}var f=null,g=null,p=null;return{initialize:function(a){a=a.c;if(void 0===a)f=Locale.getDefaultConfig(),window.history.replaceState&&window.history.replaceState({reason:"EmptyConfig"},Locale.getIndexPageTitle(f.id),App.getPagePath(IndexPage)+"?c=default");else if("default"===a)f=Locale.getDefaultConfig();
else if("string"===typeof a&&/[a-zA-Z0-9]{32}/.test(a)){var b=localStorage.getItem("_config_"+a);null===b?(alert("Cannot load config "+a+". Please select a config."),window.location=App.getPagePath(CatalogPage)):f=JSON.parse(b)}else alert("Invalid config ID. Please select a config."),window.location=App.getPagePath(CatalogPage);sessionStorage.lastConfigId=f.id;document.querySelector("body > div#container > div#title > div#text").innerHTML=f.name;b="";for(a=0;a<f.sequences.length;a++)var c="1/1"===
f.sequences[a].time?"None":f.sequences[a].time,b=b+'<div class="tile" id="sINDEX"><div id="body"><div id="header"><div id="indicator"></div><div id="time">TIME</div><div id="amount">AMOUNT</div><div id="title">NAME</div></div><div id="bpm">BPM</div><div id="progress"><div id="bar"><div id="played"></div><div id="remaining"></div><div id="info"></div></div><div id="sequence"><div id="played"></div><div id="remaining"></div><div id="info"></div></div></div></div><div id="setting"></div></div>'.replace("INDEX",
""+a).replace("TIME",c).replace("AMOUNT",0===f.sequences[a].amount?"\u221e":""+f.sequences[a].amount).replace("NAME",f.sequences[a].name).replace("BPM",""+f.sequences[a].beats[0]);document.querySelector("body > div#container > div#tiles").innerHTML=b;b=document.querySelectorAll("body > div#container > div#tiles  > div.tile");for(a=0;a<b.length;a++)b[a].addEventListener("click",d);b=document.querySelectorAll("body > div#container > div#tiles  > div.tile > div#setting");for(a=0;a<b.length;a++)b[a].addEventListener("click",
k);document.querySelector("body > div#container > div#title > div#setting").addEventListener("click",m)},draw:function(){},getPath:function(){return"/index.html"}}}(),Locale=function(){function b(){if(!("language"in localStorage&&0<=c.indexOf(localStorage.language))){var a=navigator.languages&&navigator.languages[0]||navigator.language||navigator.userLanguage,a=a.toLowerCase();c.indexOf(a)}}function e(a){a=void 0===a?"":a;return a in c?a:"en"}function a(a,b){var c;c=b in a?a[b]:a.en;for(var d=2;d<
arguments.length;d++)c=c.replace("{"+(d-1)+"}",arguments[d]);return c}var c=["en","zh-cn"],h={en:"Metronome","zh-cn":"\u8282\u62cd\u5668"},d={en:{id:"default",name:"Untitled config",lastModified:0,sequences:[{name:"Untitled sequence",time:"4/4",amount:16,hasUniformBeats:!0,beats:[60]}]},"zh-cn":{id:"default",name:"\u672a\u547d\u540d\u7684\u8bbe\u7f6e",lastModified:0,sequences:[{name:"\u672a\u547d\u540d\u7684\u5e8f\u5217",time:"4/4",amount:16,hasUniformBeats:!0,beats:[60]}]}},l={en:"Metronome config {1}",
"zh-cn":"\u8282\u62cd\u5668\u8bbe\u7f6e{1}"};b();return{checkLanguage:b,getApplicationTitle:function(b){return a(h,e(void 0===b?"":b))},getDefaultConfig:function(b){return a(d,e(void 0===b?"":b))},getIndexPageTitle:function(b,c){return a(l,e(void 0===c?"":c),b)},getTranslation:a}}(),Player=function(){function b(b,d){AJAX.GET({url:b,responseType:"arraybuffer",onSuccess:function(b){a.decodeAudioData(b,function(a){c[d]=a})}})}function e(b){if(null===b)return!1;var c=a.createBufferSource();c.buffer=b;
c.connect(a.destination);c.start(0);return!0}var a=null,c={first:null,other:null};return{initialize:function(){window.AudioContext=window.AudioContext||window.webkitAudioContext;a=new AudioContext;b(App.getRootPath()+"/sound/first.wav","first");b(App.getRootPath()+"/sound/other.wav","other")},playFirst:function(){return e(c.first)},playOther:function(){return e(c.other)}}}(),SequenceSettingPage=function(){function b(a){var b=a.target.parentNode.id;"repeatsSetting"!==b&&(b="beatsSetting");var c=a.target.parentNode.querySelector("div#value"),
d=parseInt(c.innerHTML);isNaN(d)&&(d=0);var e=d;"plus"===a.target.id?e+=1:"plusplus"===a.target.id?e+=10:"minus"===a.target.id?--e:"minusminus"===a.target.id&&(e-=10);"beatsSetting"===b?(240<e&&(e=240),20>e&&(e=20),a="a"===a.target.parentNode.id?0:parseInt(a.target.parentNode.id),e!==d&&(g.markDirty(),k.sequences[f].beats[a]=e)):(0>=e&&(e=0),e!==d&&(g.markDirty(),k.sequences[f].amount=e),0>=e&&(e="\u221e"));c.innerHTML=""+e}function e(){var a=document.querySelector("body > div#container > div#sequenceSetting > div#beatsSettingGroup"),
c="";if(k.sequences[f].hasUniformBeats)c+='<div class="beatsSetting" id="ID"><div class="shortlabel">LABEL</div><div class="valueControl" id="minusminus"></div><div class="valueControl" id="minus"></div><div class="beats" id="value">VALUE</div><div class="valueControl" id="plus"></div><div class="valueControl" id="plusplus"></div></div>'.replace("ID","a").replace("LABEL","BPM").replace("VALUE",k.sequences[f].beats[0]);else for(var d=0;d<k.sequences[f].beats.length;d++)c+='<div class="beatsSetting" id="ID"><div class="shortlabel">LABEL</div><div class="valueControl" id="minusminus"></div><div class="valueControl" id="minus"></div><div class="beats" id="value">VALUE</div><div class="valueControl" id="plus"></div><div class="valueControl" id="plusplus"></div></div>'.replace("ID",
d).replace("LABEL","BPM "+(d+1)).replace("VALUE",k.sequences[f].beats[d]);a.innerHTML=c;a=a.querySelectorAll("div.valueControl");for(d=0;d<a.length;d++)a[d].addEventListener("click",b)}function a(a){var b=document.querySelector("body > div#container > div#sequenceSetting > div#beatsSettingGroup");if(a<=b.childNodes.length)k.sequences[f].beats.splice(a);else for(var c=parseInt(b.childNodes[b.childNodes.length-1].querySelector("div#value").innerHTML),d=0;d<a-b.childNodes.length;d++)k.sequences[f].beats.push(c)}
function c(){g.markDirty();k.sequences[f].time=this.value;var b=document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#uniformSetting > input#uniformBeats");"1/1"===this.value?(a(1),e(),b.disabled=!0):(b.disabled=!1,b.checked||(a(parseInt(this.value.substr(0,this.value.indexOf("/")))),e()))}function h(){g.markDirty();if(k.sequences[f].hasUniformBeats=this.checked)a(1);else{var b=document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#timeSignatureSetting > select#time").value,
b=parseInt(b.substr(0,b.indexOf("/")));a(b)}e()}function d(a){a=a.target.id;if("ok"===a)localStorage.setItem("_config_"+k.id,JSON.stringify(k));else if("cancel"===a){if(g.isDirty()&&!confirm("Exit without saving changes?"))return}else{confirm("Do you want to discard all the changes?")&&(g.markClean(),k=JSON.parse(localStorage.getItem("_config_"+k.id)),m());return}window.location=App.getPagePath(IndexPage)+"?c="+k.id}function l(a){a=a.target.id;if("delete"===a){if(1>=k.sequences.length){alert("You cannot delete the last sequence in this config.");
return}if(confirm("Don you want to delete this sequence?"))k.sequences.splice(f,1);else return}else"insertBefore"===a?k.sequences.splice(f,0,Locale.getDefaultConfig().sequences[0]):"insertAfter"===a&&k.sequences.splice(f+1,0,Locale.getDefaultConfig().sequences[0]);localStorage.setItem("_config_"+k.id,JSON.stringify(k));window.location=url=App.getPagePath(IndexPage)+"?c="+k.id}function m(){console.log("got "+JSON.stringify(k));document.querySelector("body > div#container > div#sequenceSetting > div#header > div#title").innerHTML=
"Sequence "+(f+1)+" in "+k.name;document.querySelector("body > div#container > div#sequenceSetting > div#sequenceNameSetting > input#name ").value=k.sequences[f].name;document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#timeSignatureSetting > select#time ").value=k.sequences[f].time;document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#uniformSetting > input#uniformBeats").checked=k.sequences[f].hasUniformBeats;e();var a=""+
k.sequences[f].amount;"0"===a&&(a="\u221e");document.querySelector("body > div#container > div#sequenceSetting > div#repeatsSetting > div#value").innerHTML=a;for(var n=document.querySelectorAll("body > div#container > div#sequenceSetting > div#repeatsSetting > div.valueControl"),a=0;a<n.length;a++)n[a].addEventListener("click",b);document.querySelector("body > div#container > div#sequenceSetting > div#sequenceNameSetting > input#name").addEventListener("change",function(){g.markDirty();k.sequences[f].name=
this.value});document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#timeSignatureSetting > select#time").addEventListener("change",c);document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#uniformSetting > input#uniformBeats").addEventListener("change",h);n=document.querySelectorAll("body > div#container > div#sequenceSetting > div#buttons > div.button");for(a=0;a<n.length;a++)n[a].addEventListener("click",d);n=document.querySelectorAll("body > div#container > div#sequenceSetting > div#header > div#controls > div.control");
for(a=0;a<n.length;a++)n[a].addEventListener("click",l)}var k=null,f=0,g=null;return{initialize:function(a){g=new DirtyManager([document.querySelector("body > div#container > div#sequenceSetting > div#buttons > div.button#revert")]);var b=a.c;f=parseInt(a.s);"string"===typeof b&&/[a-zA-Z0-9]{32}/.test(b)&&"_config_"+b in localStorage?(a=localStorage.getItem("_config_"+b),k=JSON.parse(a),isNaN(f)||f>=k.sequences.length?(alert("Invalid sequence index. Please select again."),window.location=App.getPagePath(IndexPage)+
"?c="+b):m()):(alert("No config id. Please select a config."),window.location=App.getPagePath(CatalogPage))},draw:function(){},getPath:function(){return"/sequenceSetting.html"}}}(),App=function(){function b(){a.draw()}var e={},a=null;return{initialize:function(c){c=void 0===c?{}:c;Header.initialize();"Player"in window&&Player.initialize();for(var h=window.location.pathname,d=window.location.search,d=("?"===d[0]?d.substr(1):d).split("&"),l=0;l<d.length;l++){var m=d[l].split("=");c[decodeURIComponent(m[0])]=
decodeURIComponent(m[1]||"")}c.lastPage=sessionStorage.lastPage||null;e=c;d=null;0===h.indexOf("/m1"+CatalogPage.getPath())?a=CatalogPage:0===h.indexOf("/m1"+AboutPage.getPath())?a=AboutPage:0===h.indexOf("/m1"+SequenceSettingPage.getPath())?(a=SequenceSettingPage,d=IndexPage):0===h.indexOf("/m1"+ConfigSettingPage.getPath())?(a=ConfigSettingPage,d=IndexPage):a=IndexPage;Header.highlight(null===d?a:d);a.initialize(c);sessionStorage.setItem("lastPage",a.getPath());window.addEventListener("resize",b)},
getParams:function(){return e},getRootPath:function(){return"/m1"},getPagePath:function(a){return"/m1"+(void 0===a?null:a).getPath()},resize:b}}();
