var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(h,e,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");h!=Array.prototype&&h!=Object.prototype&&(h[e]=a.value)};$jscomp.getGlobal=function(h){return"undefined"!=typeof window&&window===h?h:"undefined"!=typeof global&&null!=global?global:h};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var h=$jscomp.global.Symbol.iterator;h||(h=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[h]&&$jscomp.defineProperty(Array.prototype,h,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(h){var e=0;return $jscomp.iteratorPrototype(function(){return e<h.length?{done:!1,value:h[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(h){$jscomp.initSymbolIterator();h={next:h};h[$jscomp.global.Symbol.iterator]=function(){return this};return h};$jscomp.polyfill=function(h,e,a,b){if(e){a=$jscomp.global;h=h.split(".");for(b=0;b<h.length-1;b++){var f=h[b];f in a||(a[f]={});a=a[f]}h=h[h.length-1];b=a[h];e=e(b);e!=b&&null!=e&&$jscomp.defineProperty(a,h,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.from",function(h){return h?h:function(e,a,b){$jscomp.initSymbolIterator();a=null!=a?a:function(b){return b};var f=[],c=e[Symbol.iterator];if("function"==typeof c)for(e=c.call(e);!(c=e.next()).done;)f.push(a.call(b,c.value));else for(var c=e.length,m=0;m<c;m++)f.push(a.call(b,e[m]));return f}},"es6-impl","es3");$jscomp.makeIterator=function(h){$jscomp.initSymbolIterator();var e=h[Symbol.iterator];return e?e.call(h):$jscomp.arrayIterator(h)};
$jscomp.owns=function(h,e){return Object.prototype.hasOwnProperty.call(h,e)};
$jscomp.polyfill("WeakMap",function(h){function e(a){$jscomp.owns(a,b)||$jscomp.defineProperty(a,b,{value:{}})}function a(b){var a=Object[b];a&&(Object[b]=function(b){e(b);return a(b)})}if(function(){if(!h||!Object.seal)return!1;try{var b=Object.seal({}),a=Object.seal({}),d=new h([[b,2],[a,3]]);if(2!=d.get(b)||3!=d.get(a))return!1;d["delete"](b);d.set(a,4);return!d.has(b)&&4==d.get(a)}catch(k){return!1}}())return h;var b="$jscomp_hidden_"+Math.random().toString().substring(2);a("freeze");a("preventExtensions");
a("seal");var f=0,c=function(b){this.id_=(f+=Math.random()+1).toString();if(b){$jscomp.initSymbol();$jscomp.initSymbolIterator();b=$jscomp.makeIterator(b);for(var a;!(a=b.next()).done;)a=a.value,this.set(a[0],a[1])}};c.prototype.set=function(a,c){e(a);if(!$jscomp.owns(a,b))throw Error("WeakMap key fail: "+a);a[b][this.id_]=c;return this};c.prototype.get=function(a){return $jscomp.owns(a,b)?a[b][this.id_]:void 0};c.prototype.has=function(a){return $jscomp.owns(a,b)&&$jscomp.owns(a[b],this.id_)};c.prototype["delete"]=
function(a){return $jscomp.owns(a,b)&&$jscomp.owns(a[b],this.id_)?delete a[b][this.id_]:!1};return c},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(h){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!h||!h.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new h($jscomp.makeIterator([[a,"s"]]));if("s"!=b.get(a)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var c=b.entries(),f=c.next();if(f.done||f.value[0]!=a||"s"!=f.value[1])return!1;f=c.next();return f.done||4!=f.value[0].x||"t"!=f.value[1]||!c.next().done?!1:!0}catch(r){return!1}}())return h;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var e=new WeakMap,a=function(b){this.data_={};this.head_=c();this.size=0;if(b){b=$jscomp.makeIterator(b);for(var a;!(a=b.next()).done;)a=a.value,this.set(a[0],a[1])}};a.prototype.set=function(a,c){var d=b(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=c:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:c},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};a.prototype["delete"]=
function(a){a=b(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};a.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=c();this.size=0};a.prototype.has=function(a){return!!b(this,a).entry};a.prototype.get=function(a){return(a=b(this,a).entry)&&a.value};a.prototype.entries=function(){return f(this,function(a){return[a.key,
a.value]})};a.prototype.keys=function(){return f(this,function(a){return a.key})};a.prototype.values=function(){return f(this,function(a){return a.value})};a.prototype.forEach=function(a,b){for(var d=this.entries(),c;!(c=d.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};a.prototype[Symbol.iterator]=a.prototype.entries;var b=function(a,b){var c;c=b&&typeof b;"object"==c||"function"==c?e.has(b)?c=e.get(b):(c=""+ ++m,e.set(b,c)):c="p_"+b;var d=a.data_[c];if(d&&$jscomp.owns(a.data_,c))for(var f=0;f<
d.length;f++){var t=d[f];if(b!==b&&t.key!==t.key||b===t.key)return{id:c,list:d,index:f,entry:t}}return{id:c,list:d,index:-1,entry:void 0}},f=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},c=function(){var a={};return a.previous=a.next=a.head=a},m=0;return a},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(h){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!h||!h.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new h($jscomp.makeIterator([a]));if(!b.has(a)||1!=b.size||b.add(a)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var f=b.entries(),c=f.next();if(c.done||c.value[0]!=a||c.value[1]!=a)return!1;c=f.next();return c.done||c.value[0]==a||4!=c.value[0].x||c.value[1]!=c.value[0]?!1:f.next().done}catch(m){return!1}}())return h;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var e=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};e.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};e.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};e.prototype.clear=function(){this.map_.clear();this.size=0};e.prototype.has=function(a){return this.map_.has(a)};e.prototype.entries=
function(){return this.map_.entries()};e.prototype.values=function(){return this.map_.values()};e.prototype[Symbol.iterator]=e.prototype.values;e.prototype.forEach=function(a,b){var f=this;this.map_.forEach(function(c){return a.call(b,c,c,f)})};return e},"es6-impl","es3");
var AboutPage=function(){return{initialize:function(h){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){Header.handleConfig()})},draw:function(){},getPath:function(){return"/about.html"}}}(),AJAX=function(){return{GET:function(h){var e=h.url,a=h.onSuccess||null,b=h.onFailure||null,f=new XMLHttpRequest;f.responseType=h.responseType||"";f.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==a&&a(this.response):null!==
b&&b(this.status))};f.open("GET",e,!0);f.send()}}}(),CatalogPage=function(){function h(){var e=[],a;for(a in localStorage)0===a.indexOf("_config_")&&e.push(JSON.parse(localStorage[a]));e.sort(function(a,b){return a.name>b.name?1:a.name<b.name?-1:0});e.splice(0,0,Locale.getDefaultConfig());var b="";for(a=0;a<e.length;a++)b+='<div class="tile" id="ID">NAME</div>'.replace("ID",e[a].id).replace("NAME",e[a].name);document.querySelector("body > div#container > div#tiles").innerHTML=b;e=document.querySelectorAll("body > div#container > div#tiles > div.tile");
for(a=0;a<e.length;a++)e[a].addEventListener("click",function(a){a=a.target.id;window.location=App.getPagePath(IndexPage)+"?c="+a})}return{initialize:function(e){document.querySelector("div#tiles");parseInt(e.p);Array.from(new Set((e.q||"").split(",")));h()},draw:function(){},getPath:function(){return"/catalog.html"}}}(),codec=function(){function h(b,f){f=void 0===f?a:f;if(b<f.base.length)return f.base[b];if(b<f.base.length*(f.extra.length+1))return f.extra[Math.floor(b/f.base.length)-1]+f.base[b%
f.base.length];for(var c=f.extraExtra;;){if(b<f.base.length){c+=f.base[b];break}c+=f.base[b%f.base.length];b=Math.floor(b/f.base.length)}return c+f.extraExtra}function e(b,f,c){c=void 0===c?a:c;var e={};if(f>=b.length)return null;if(0<=c.base.indexOf(b[f])){var h=c.base.indexOf(b[f]);if(0>h)return null;e.value=h;e.end=f+1}else if(0<=c.extra.indexOf(b[f])){if(f==b.lengt-1)return null;h=c.extra.indexOf(b[f])+1;b=c.base.indexOf(b[f+1]);if(0>=h||0>b)return null;e.value=h*c.base.length+b;e.end=f+2}else if(c.extraExtra==
b[f]){var d=f+1,k=b.indexOf(c.extraExtra,d);if(k<=d)return null;h=c.base.indexOf(b[k-1]);if(0>h)return null;for(var l=k-2;l>=d;l--){var r=c.base.indexOf(b[l]);if(0>r)return null;h=h*c.base.length+r}e.value=h;e.end=f+k-d+2}f=[];for(var t in e)e.hasOwnProperty(t)&&f.push(t);return 0==f.length?null:e}var a={base:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",extra:"0123456789-",extraExtra:"_"};return{encodeInt:h,decodeInt:e,encodeIntArray:function(b,f){f=void 0===f?a:f;for(var c="",e=0;e<b.length;e++)c+=
h(b[e],f);return c},decodeIntArray:function(b,f){f=void 0===f?a:f;for(var c=[],h=0;h<b.length;){h=e(b,h,f);if(null==h)return null;c.push(h.value);h=h.end}return c}}}(),Config=function(){function h(a){var b={original:a,last:0};a=a.match(/(.*)\ +\((\d+)\)\ *$/);null!==a&&(b.original=a[1],b.last=parseInt(a[2]));return b}var e="1/1 2/2 2/4 3/4 4/4 5/4 3/8 6/8 7/8 8/8 12/8".split(" ");return{toURLString:function(a){for(var b=[a.name],f=[],c=0;c<a.sequences.length;c++){var h=a.sequences[c];b.push(h.name);
e.indexOf(h.time);e.indexOf(h.time);f.push((e.indexOf(h.time)<<4)+(h.hasUniformBeats?1:0));f.push(h.amount);for(var n=h.hasUniformBeats?1:parseInt(h.time.substr(0,h.time.indexOf("/"))),d=0;d<n;d++)f.push(h.beats[d])}b.push(codec.encodeIntArray(f));a=JSON.stringify(b);if(896<a)for(c=1;c<b.length-1;c++)b[c]="S"+c;a=JSON.stringify(b);return 896<a.length?"":a},fromURLString:function(a){try{for(var b=JSON.parse(a),f=codec.decodeIntArray(b[b.length-1]),c={name:b[0],sequences:[]},h=a=0;h<b.length-2;h++){var n=
{name:b[h+1],beats:[]};n.time=e[(f[a]&240)>>>4];n.hasUniformBeats=1===(f[a]&15)?!0:!1;a+=1;n.amount=f[a];a+=1;for(var d=n.hasUniformBeats?1:parseInt(n.time.substr(0,n.time.indexOf("/"))),k=0;k<d;k++)n.beats.push(f[a]),a+=1;c.sequences.push(n)}return c}catch(l){return console.log("caught exception when parsing config to be imported: "+l),null}},getNextAvailableName:function(a){var b=h(a);a=new RegExp(b.original+" +\\((\\d+)\\)\\ *$");var f=b.original,b=b.last,c=!1,e=!1,n;for(n in localStorage)if(0===
n.indexOf("_config_")){var d=JSON.parse(localStorage[n]);d.name.trim()===f?e=!0:(match=d.name.match(a),null!==match&&(c=!0,d=parseInt(match[1]),d>b&&(b=d)))}return c?f+" ("+(b+1)+")":e?f+" (1)":f},generateConfigId:function(a){a=void 0===a?32:a;for(var b="",f=0;f<a;f++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return b},isEquivalent:function(a,b){var f=h(a.name),c=h(b.name);if(f.original!==c.original||a.sequences.length!==b.sequences.length)return!1;
for(f=0;f<a.sequences.length;f++){var c=a.sequences[f],e=b.sequences[f];if(c.name!==e.name||c.time!==e.time||c.amount!==e.amount||c.hasUniformBeats!==e.hasUniformBeats)return!1;for(var n=parseInt(c.time.substr(0,c.time.indexOf("/"))),f=0;f<n;f++)if(c.beats[f]!==e.beats[f])return!1}return!0}}}(),ConfigSettingPage=function(){function h(a){a=a.target.id;if("ok"===a)localStorage.setItem("_config_"+b.id,JSON.stringify(b));else if("cancel"===a){if(f.isDirty()&&!confirm("Exit without saving changes?"))return}else{confirm("Do you want to discard all the changes?")&&
(f.markClean(),b=JSON.parse(localStorage.getItem("_config_"+b.id)),document.querySelector("body > div#container > div#configSetting > div#configNameSetting > input#name").value=b.name);return}window.location=App.getPagePath(IndexPage)+"?c="+b.id}function e(a){a=a.target.id;"clone"===a?(a=b,a.name=Config.getNextAvailableName(a.name),a.id=Config.generateConfigId(),localStorage.setItem("_config_"+a.id,JSON.stringify(a)),window.location=App.getPagePath(IndexPage)+"?c="+a.id):"delete"===a?confirm("Do you want to delete this config?")&&
(localStorage.removeItem("_config_"+b.id),sessionStorage.getItem("lastConfigId")===b.id&&sessionStorage.removeItem("lastConfigId"),window.location=App.getPagePath(CatalogPage)):"share"===a&&(sessionStorage.setItem("tsSharePageLastRequested",(new Date).getTime()),window.location=App.getPagePath(SharePage)+"?c="+b.id)}function a(){var a=document.querySelector("body > div#container > div#configSetting > div#configNameSetting > input#name");a.value=b.name;a.addEventListener("change",function(){b.name=
this.value;f.markDirty()});for(var m=document.querySelectorAll("body > div#container > div#configSetting > div#buttons > div.button"),a=0;a<m.length;a++)m[a].addEventListener("click",h);m=document.querySelectorAll("body > div#container > div#configSetting > div#header > div#controls > div.control");for(a=0;a<m.length;a++)m[a].addEventListener("click",e)}var b=null,f=null;return{initialize:function(c){c=c.c;f=new DirtyManager([document.querySelector("body > div#container > div#configSetting > div#buttons > div.button#revert")]);
"string"===typeof c&&/[a-zA-Z0-9]{32}/.test(c)&&"_config_"+c in localStorage?(c=localStorage.getItem("_config_"+c),b=JSON.parse(c),a()):(alert("No config id. Please select a config."),window.location=App.getPagePath(CatalogPage))},draw:function(){},getPath:function(){return"/configSetting.html"}}}(),DirtyManager=function(h){var e=!1,a=h;return{markDirty:function(){e=!0;for(var b=0;b<a.length;b++)a[b].classList.remove("gray")},markClean:function(){e=!1;for(var b=0;b<a.length;b++)a[b].classList.remove("gray")},
isDirty:function(){return e},setElements:function(b){a=b}}}(function(){var h=0;document.addEventListener("touchend",function(e){var a=(new Date).getTime();300>=a-h&&e.preventDefault();h=a},!1)})(),Header=function(){function h(){var a;a=App.getParams();var b="default";a.hasOwnProperty("c")?b=a.c:"lastConfigId"in sessionStorage&&(b=sessionStorage.lastConfigId);a=b;window.location=App.getPagePath(IndexPage)+"?c="+encodeURIComponent(a)}function e(){window.location=App.getPagePath(CatalogPage)}function a(){window.location=
App.getPagePath(AboutPage)}var b=null,f=null;return{initialize:function(){b=document.querySelector("div#header > div#controls > div.control#config");f=document.querySelector("div#header > div#controls > div.control#open");b.addEventListener("click",h);f.addEventListener("click",e);document.querySelector("div#header > div#title  > div#text").addEventListener("click",a);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",a);document.querySelector("div#header > div#title  > div#text").innerHTML=
Locale.getApplicationTitle()},highlight:function(a){b.classList.remove("highlighted");f.classList.remove("highlighted");a===IndexPage?b.classList.add("highlighted"):a===CatalogPage&&f.classList.add("highlighted")},handleConfig:h}}(),IndexPage=function(){function h(){var a=k.sequences[l.sequenceIndex],g="1";"1/1"!==a.time&&(g=l.indexInBar+1+a.time.substr(a.time.indexOf("/")));document.querySelector("body > div#container > div#tiles  > div.tile#s"+l.sequenceIndex+" > div#body > div#progress > div#bar > div#info").innerHTML=
g;g=0;0!=a.time&&(g=(parseFloat(a.time.substr(0,a.time.indexOf("/")))-(l.indexInBar+1))/(l.indexInBar+1));document.querySelector("body > div#container > div#tiles  > div.tile#s"+l.sequenceIndex+" > div#body > div#progress > div#bar > div#remaining").style.flexGrow=g;g=l.indexInSequence+1+"/";g=0===a.amount?g+"\u221e":g+a.amount;document.querySelector("body > div#container > div#tiles  > div.tile#s"+l.sequenceIndex+" > div#body > div#progress > div#sequence > div#info").innerHTML=g;g=100;0<a.amount&&
(g=(a.amount-(l.indexInSequence+1))/(l.indexInSequence+1));document.querySelector("body > div#container > div#tiles  > div.tile#s"+l.sequenceIndex+" > div#body > div#progress > div#sequence > div#remaining").style.flexGrow=g}function e(){var a=k.sequences[l.sequenceIndex];l.indexInBar+=1;if("1/1"===a.time||l.indexInBar>=parseInt(a.time.substr(0,a.time.indexOf("/"))))l.indexInBar=0,l.indexInSequence+=1;0!==a.amount&&l.indexInSequence>=a.amount&&(f(l.sequenceIndex),l.sequenceIndex+=1,l.indexInBar=0,
l.indexInSequence=0);if(l.sequenceIndex>=k.sequences.length)return!0;b(l.sequenceIndex);return!1}function a(){var b=k.sequences[l.sequenceIndex],b=b.hasUniformBeats?b.beats[0]:b.beats[l.indexInBar];r=setTimeout(a,6E4/b);0===l.indexInBar?Player.playFirst():Player.playOther();document.querySelector("body > div#container > div#tiles > div.tile#s"+l.sequenceIndex+" > div#body > div#bpm").innerHTML=""+b;h();e()&&(clearTimeout(r),l=null,setTimeout(function(){alert("Played!")},10))}function b(a){document.querySelector("body > div#container > div#tiles > div.tile#s"+
a+" > div#body > div#header  > div#indicator").style.display="block";document.querySelector("body > div#container > div#tiles > div.tile#s"+a+" > div#body > div#progress").style.display="block"}function f(a){document.querySelector("body > div#container > div#tiles > div.tile#s"+a+" > div#body > div#header  > div#indicator").style.display="none";document.querySelector("body > div#container > div#tiles > div.tile#s"+a+" > div#body > div#progress").style.display="none"}function c(d){for(d=d.target;!d.classList.contains("tile");)d=
d.parentNode;d=parseInt(d.id.substr(1));null!==l&&(f(l.sequenceIndex),clearTimeout(r));null===l||l.sequenceIndex!==d?(l={sequenceIndex:d,indexInBar:0,indexInSequence:0},b(d),a()):window.location.reload()}function m(){k.id=Config.generateConfigId();k.name=Config.getNextAvailableName(k.name);k.name===Locale.getDefaultConfigName()&&(k.name=Locale.getDefaultConfigName()+" (1)");localStorage.setItem("_config_"+k.id,JSON.stringify(k))}function n(a){a.stopPropagation();if("default"===k.id)if(confirm("You will create a new config when editting the default config. Do you want to continue?"))m();
else return;window.location=App.getPagePath(ConfigSettingPage)+"?c="+k.id}function d(a){a.stopPropagation();if("default"===k.id)if(confirm("You will create a new config when editting the default config. Do you want to continue?"))m();else return;for(element=a.target;element!==window&&!element.classList.contains("tile");)element=element.parentNode;window.location=App.getPagePath(SequenceSettingPage)+"?c="+k.id+"&s="+element.id.substr(1)}var k=null,l=null,r=null;return{initialize:function(a){a=a.c;
if(void 0===a)k=Locale.getDefaultConfig(),window.history.replaceState&&window.history.replaceState({reason:"EmptyConfig"},Locale.getIndexPageTitle(k.id),App.getPagePath(IndexPage)+"?c=default");else if("default"===a)k=Locale.getDefaultConfig();else if("string"===typeof a&&/[a-zA-Z0-9]{32}/.test(a)){var g=localStorage.getItem("_config_"+a);null===g?(alert("Cannot load config "+a+". Please select a config."),window.location=App.getPagePath(CatalogPage)):k=JSON.parse(g)}else alert("Invalid config ID. Please select a config."),
window.location=App.getPagePath(CatalogPage);sessionStorage.lastConfigId=k.id;document.querySelector("body > div#container > div#title > div#text").innerHTML=k.name;g="";for(a=0;a<k.sequences.length;a++)var b="1/1"===k.sequences[a].time?"None":k.sequences[a].time,g=g+'<div class="tile" id="sINDEX"><div id="body"><div id="header"><div id="indicator"></div><div id="time">TIME</div><div id="amount">AMOUNT</div><div id="title">NAME</div></div><div id="bpm">BPM</div><div id="progress"><div id="bar"><div id="played"></div><div id="remaining"></div><div id="info"></div></div><div id="sequence"><div id="played"></div><div id="remaining"></div><div id="info"></div></div></div></div><div id="setting"></div></div>'.replace("INDEX",
""+a).replace("TIME",b).replace("AMOUNT",0===k.sequences[a].amount?"\u221e":""+k.sequences[a].amount).replace("NAME",k.sequences[a].name).replace("BPM",""+k.sequences[a].beats[0]);document.querySelector("body > div#container > div#tiles").innerHTML=g;g=document.querySelectorAll("body > div#container > div#tiles  > div.tile");for(a=0;a<g.length;a++)g[a].addEventListener("click",c);g=document.querySelectorAll("body > div#container > div#tiles  > div.tile > div#setting");for(a=0;a<g.length;a++)g[a].addEventListener("click",
d);document.querySelector("body > div#container > div#title > div#setting").addEventListener("click",n)},draw:function(){},getPath:function(){return"/index.html"}}}(),LoadingIconManager=function(){var h=0,e=document.querySelector("body > div#loading");return{show:function(){setTimeout(function(){100<(new Date).getTime()-h&&e.classList.remove("hidden")},100)},hide:function(){e.classList.add("hidden");h=(new Date).getTime()}}}(),Locale=function(){function h(){if(!("language"in localStorage&&0<=b.indexOf(localStorage.language))){var a=
navigator.languages&&navigator.languages[0]||navigator.language||navigator.userLanguage,a=a.toLowerCase();b.indexOf(a)}}function e(a){a=void 0===a?"":a;return a in b?a:"en"}function a(a,b){var d;d=b in a?a[b]:a.en;for(var c=2;c<arguments.length;c++)d=d.replace("{"+(c-1)+"}",arguments[c]);return d}var b=["en","zh-cn"],f={en:"Metronome","zh-cn":"\u8282\u62cd\u5668"},c={en:{id:"default",name:"Untitled config",lastModified:0,sequences:[{name:"Untitled sequence",time:"4/4",amount:16,hasUniformBeats:!0,
beats:[60]}]},"zh-cn":{id:"default",name:"\u672a\u547d\u540d\u7684\u8bbe\u7f6e",lastModified:0,sequences:[{name:"\u672a\u547d\u540d\u7684\u5e8f\u5217",time:"4/4",amount:16,hasUniformBeats:!0,beats:[60]}]}},m={en:"Metronome config {1}","zh-cn":"\u8282\u62cd\u5668\u8bbe\u7f6e{1}"},n={en:"Untitled config","zh-cn":"\u672a\u547d\u540d\u7684\u8bbe\u7f6e"};h();return{checkLanguage:h,getApplicationTitle:function(b){return a(f,e(void 0===b?"":b))},getDefaultConfigName:function(b){return a(n,e(void 0===b?"":
b))},getDefaultConfig:function(b){return a(c,e(void 0===b?"":b))},getIndexPageTitle:function(b,c){return a(m,e(void 0===c?"":c),b)},getTranslation:a}}(),Player=function(){function h(f,c){AJAX.GET({url:f,responseType:"arraybuffer",onSuccess:function(f){a.decodeAudioData(f,function(a){b[c]=a})}})}function e(b){if(null===b)return!1;var c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);return!0}var a=null,b={first:null,other:null};return{initialize:function(){window.AudioContext=
window.AudioContext||window.webkitAudioContext;a=new AudioContext;h(App.getRootPath()+"/sound/first.wav","first");h(App.getRootPath()+"/sound/other.wav","other")},playFirst:function(){return e(b.first)},playOther:function(){return e(b.other)}}}(),QRCode;
!function(){function h(a){this.mode=m.MODE_8BIT_BYTE;this.data=a;this.parsedData=[];a=[];for(var b=0,g=this.data.length;g>b;b++){var q=this.data.charCodeAt(b);65536<q?(a[0]=240|(1835008&q)>>>18,a[1]=128|(258048&q)>>>12,a[2]=128|(4032&q)>>>6,a[3]=128|63&q):2048<q?(a[0]=224|(61440&q)>>>12,a[1]=128|(4032&q)>>>6,a[2]=128|63&q):128<q?(a[0]=192|(1984&q)>>>6,a[1]=128|63&q):a[0]=q;this.parsedData=this.parsedData.concat(a)}this.parsedData.length!=this.data.length&&(this.parsedData.unshift(191),this.parsedData.unshift(187),
this.parsedData.unshift(239))}function e(a,b){this.typeNumber=a;this.errorCorrectLevel=b;this.modules=null;this.moduleCount=0;this.dataCache=null;this.dataList=[]}function a(a,b){if(void 0==a.length)throw Error(a.length+"/"+b);for(var g=0;g<a.length&&0==a[g];)g++;this.num=Array(a.length-g+b);for(var q=0;q<a.length-g;q++)this.num[q]=a[q+g]}function b(a,b){this.totalCount=a;this.dataCount=b}function f(){this.buffer=[];this.length=0}function c(){var a=!1,b=navigator.userAgent;return/android/i.test(b)&&
(a=!0,aMat=b.toString().match(/android ([0-9]\.[0-9])/i),aMat&&aMat[1]&&(a=parseFloat(aMat[1]))),a}h.prototype={getLength:function(){return this.parsedData.length},write:function(a){for(var b=0,g=this.parsedData.length;g>b;b++)a.put(this.parsedData[b],8)}};e.prototype={addData:function(a){a=new h(a);this.dataList.push(a);this.dataCache=null},isDark:function(a,b){if(0>a||this.moduleCount<=a||0>b||this.moduleCount<=b)throw Error(a+","+b);return this.modules[a][b]},getModuleCount:function(){return this.moduleCount},
make:function(){this.makeImpl(!1,this.getBestMaskPattern())},makeImpl:function(a,b){this.moduleCount=4*this.typeNumber+17;this.modules=Array(this.moduleCount);for(var g=0;g<this.moduleCount;g++){this.modules[g]=Array(this.moduleCount);for(var q=0;q<this.moduleCount;q++)this.modules[g][q]=null}this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(a,
b);7<=this.typeNumber&&this.setupTypeNumber(a);null==this.dataCache&&(this.dataCache=e.createData(this.typeNumber,this.errorCorrectLevel,this.dataList));this.mapData(this.dataCache,b)},setupPositionProbePattern:function(a,b){for(var g=-1;7>=g;g++)if(!(-1>=a+g||this.moduleCount<=a+g))for(var q=-1;7>=q;q++)-1>=b+q||this.moduleCount<=b+q||(this.modules[a+g][b+q]=0<=g&&6>=g&&(0==q||6==q)||0<=q&&6>=q&&(0==g||6==g)||2<=g&&4>=g&&2<=q&&4>=q?!0:!1)},getBestMaskPattern:function(){for(var a=0,b=0,c=0;8>c;c++){this.makeImpl(!0,
c);var q=d.getLostPoint(this);(0==c||a>q)&&(a=q,b=c)}return b},createMovieClip:function(a,b,c){a=a.createEmptyMovieClip(b,c);this.make();for(b=0;b<this.modules.length;b++){c=1*b;for(var g=0;g<this.modules[b].length;g++){var d=1*g;this.modules[b][g]&&(a.beginFill(0,100),a.moveTo(d,c),a.lineTo(d+1,c),a.lineTo(d+1,c+1),a.lineTo(d,c+1),a.endFill())}}return a},setupTimingPattern:function(){for(var a=8;a<this.moduleCount-8;a++)null==this.modules[a][6]&&(this.modules[a][6]=0==a%2);for(a=8;a<this.moduleCount-
8;a++)null==this.modules[6][a]&&(this.modules[6][a]=0==a%2)},setupPositionAdjustPattern:function(){for(var a=d.getPatternPosition(this.typeNumber),b=0;b<a.length;b++)for(var c=0;c<a.length;c++){var q=a[b],f=a[c];if(null==this.modules[q][f])for(var h=-2;2>=h;h++)for(var e=-2;2>=e;e++)this.modules[q+h][f+e]=-2==h||2==h||-2==e||2==e||0==h&&0==e?!0:!1}},setupTypeNumber:function(a){for(var b=d.getBCHTypeNumber(this.typeNumber),g=0;18>g;g++){var c=!a&&1==(1&b>>g);this.modules[Math.floor(g/3)][g%3+this.moduleCount-
8-3]=c}for(g=0;18>g;g++)c=!a&&1==(1&b>>g),this.modules[g%3+this.moduleCount-8-3][Math.floor(g/3)]=c},setupTypeInfo:function(a,b){for(var g=d.getBCHTypeInfo(this.errorCorrectLevel<<3|b),c=0;15>c;c++){var f=!a&&1==(1&g>>c);6>c?this.modules[c][8]=f:8>c?this.modules[c+1][8]=f:this.modules[this.moduleCount-15+c][8]=f}for(c=0;15>c;c++)f=!a&&1==(1&g>>c),8>c?this.modules[8][this.moduleCount-c-1]=f:9>c?this.modules[8][15-c-1+1]=f:this.modules[8][15-c-1]=f;this.modules[this.moduleCount-8][8]=!a},mapData:function(a,
b){for(var c=-1,g=this.moduleCount-1,f=7,h=0,e=this.moduleCount-1;0<e;e-=2)for(6==e&&e--;;){for(var p=0;2>p;p++)if(null==this.modules[g][e-p]){var k=!1;h<a.length&&(k=1==(1&a[h]>>>f));d.getMask(b,g,e-p)&&(k=!k);this.modules[g][e-p]=k;f--; -1==f&&(h++,f=7)}if(g+=c,0>g||this.moduleCount<=g){g-=c;c=-c;break}}}};e.PAD0=236;e.PAD1=17;e.createData=function(a,c,h){c=b.getRSBlocks(a,c);for(var g=new f,p=0;p<h.length;p++){var k=h[p];g.put(k.mode,4);g.put(k.getLength(),d.getLengthInBits(k.mode,a));k.write(g)}for(p=
a=0;p<c.length;p++)a+=c[p].dataCount;if(g.getLengthInBits()>8*a)throw Error("code length overflow. ("+g.getLengthInBits()+">"+8*a+")");for(g.getLengthInBits()+4<=8*a&&g.put(0,4);0!=g.getLengthInBits()%8;)g.putBit(!1);for(;!(g.getLengthInBits()>=8*a||(g.put(e.PAD0,8),g.getLengthInBits()>=8*a));)g.put(e.PAD1,8);return e.createBytes(g,c)};e.createBytes=function(b,c){for(var g=0,f=0,h=0,e=Array(c.length),k=Array(c.length),p=0;p<c.length;p++){var l=c[p].dataCount,r=c[p].totalCount-l,f=Math.max(f,l),h=
Math.max(h,r);e[p]=Array(l);for(var m=0;m<e[p].length;m++)e[p][m]=255&b.buffer[m+g];g+=l;m=d.getErrorCorrectPolynomial(r);l=(new a(e[p],m.getLength()-1)).mod(m);k[p]=Array(m.getLength()-1);for(m=0;m<k[p].length;m++)r=m+l.getLength()-k[p].length,k[p][m]=0<=r?l.get(r):0}for(m=p=0;m<c.length;m++)p+=c[m].totalCount;g=Array(p);for(m=l=0;f>m;m++)for(p=0;p<c.length;p++)m<e[p].length&&(g[l++]=e[p][m]);for(m=0;h>m;m++)for(p=0;p<c.length;p++)m<k[p].length&&(g[l++]=k[p][m]);return g};for(var m={MODE_NUMBER:1,
MODE_ALPHA_NUM:2,MODE_8BIT_BYTE:4,MODE_KANJI:8},n={L:1,M:0,Q:3,H:2},d={PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50],[6,30,54],[6,32,58],[6,34,62],[6,26,46,66],[6,26,48,70],[6,26,50,74],[6,30,54,78],[6,30,56,82],[6,30,58,86],[6,34,62,90],[6,28,50,72,94],[6,26,50,74,98],[6,30,54,78,102],[6,28,54,80,106],[6,32,58,84,110],[6,30,58,86,114],[6,34,62,90,118],[6,26,50,74,98,122],[6,30,54,78,102,126],[6,26,52,78,104,130],[6,30,56,82,108,134],[6,34,60,
86,112,138],[6,30,58,86,114,142],[6,34,62,90,118,146],[6,30,54,78,102,126,150],[6,24,50,76,102,128,154],[6,28,54,80,106,132,158],[6,32,58,84,110,136,162],[6,26,54,82,110,138,166],[6,30,58,86,114,142,170]],G15:1335,G18:7973,G15_MASK:21522,getBCHTypeInfo:function(a){for(var b=a<<10;0<=d.getBCHDigit(b)-d.getBCHDigit(d.G15);)b^=d.G15<<d.getBCHDigit(b)-d.getBCHDigit(d.G15);return(a<<10|b)^d.G15_MASK},getBCHTypeNumber:function(a){for(var b=a<<12;0<=d.getBCHDigit(b)-d.getBCHDigit(d.G18);)b^=d.G18<<d.getBCHDigit(b)-
d.getBCHDigit(d.G18);return a<<12|b},getBCHDigit:function(a){for(var b=0;0!=a;)b++,a>>>=1;return b},getPatternPosition:function(a){return d.PATTERN_POSITION_TABLE[a-1]},getMask:function(a,b,c){switch(a){case 0:return 0==(b+c)%2;case 1:return 0==b%2;case 2:return 0==c%3;case 3:return 0==(b+c)%3;case 4:return 0==(Math.floor(b/2)+Math.floor(c/3))%2;case 5:return 0==b*c%2+b*c%3;case 6:return 0==(b*c%2+b*c%3)%2;case 7:return 0==(b*c%3+(b+c)%2)%2;default:throw Error("bad maskPattern:"+a);}},getErrorCorrectPolynomial:function(b){for(var c=
new a([1],0),g=0;b>g;g++)c=c.multiply(new a([1,k.gexp(g)],0));return c},getLengthInBits:function(a,b){if(1<=b&&10>b)switch(a){case m.MODE_NUMBER:return 10;case m.MODE_ALPHA_NUM:return 9;case m.MODE_8BIT_BYTE:return 8;case m.MODE_KANJI:return 8;default:throw Error("mode:"+a);}else if(27>b)switch(a){case m.MODE_NUMBER:return 12;case m.MODE_ALPHA_NUM:return 11;case m.MODE_8BIT_BYTE:return 16;case m.MODE_KANJI:return 10;default:throw Error("mode:"+a);}else{if(!(41>b))throw Error("type:"+b);switch(a){case m.MODE_NUMBER:return 14;
case m.MODE_ALPHA_NUM:return 13;case m.MODE_8BIT_BYTE:return 16;case m.MODE_KANJI:return 12;default:throw Error("mode:"+a);}}},getLostPoint:function(a){for(var b=a.getModuleCount(),c=0,g=0;b>g;g++)for(var d=0;b>d;d++){for(var f=0,h=a.isDark(g,d),e=-1;1>=e;e++)if(!(0>g+e||g+e>=b))for(var k=-1;1>=k;k++)0>d+k||d+k>=b||(0!=e||0!=k)&&h==a.isDark(g+e,d+k)&&f++;5<f&&(c+=3+f-5)}for(g=0;b-1>g;g++)for(d=0;b-1>d;d++)f=0,a.isDark(g,d)&&f++,a.isDark(g+1,d)&&f++,a.isDark(g,d+1)&&f++,a.isDark(g+1,d+1)&&f++,0!=f&&
4!=f||(c+=3);for(g=0;b>g;g++)for(d=0;b-6>d;d++)a.isDark(g,d)&&!a.isDark(g,d+1)&&a.isDark(g,d+2)&&a.isDark(g,d+3)&&a.isDark(g,d+4)&&!a.isDark(g,d+5)&&a.isDark(g,d+6)&&(c+=40);for(d=0;b>d;d++)for(g=0;b-6>g;g++)a.isDark(g,d)&&!a.isDark(g+1,d)&&a.isDark(g+2,d)&&a.isDark(g+3,d)&&a.isDark(g+4,d)&&!a.isDark(g+5,d)&&a.isDark(g+6,d)&&(c+=40);for(d=f=0;b>d;d++)for(g=0;b>g;g++)a.isDark(g,d)&&f++;return c+Math.abs(100*f/b/b-50)/5*10}},k={glog:function(a){if(1>a)throw Error("glog("+a+")");return k.LOG_TABLE[a]},
gexp:function(a){for(;0>a;)a+=255;for(;256<=a;)a-=255;return k.EXP_TABLE[a]},EXP_TABLE:Array(256),LOG_TABLE:Array(256)},l=0;8>l;l++)k.EXP_TABLE[l]=1<<l;for(l=8;256>l;l++)k.EXP_TABLE[l]=k.EXP_TABLE[l-4]^k.EXP_TABLE[l-5]^k.EXP_TABLE[l-6]^k.EXP_TABLE[l-8];for(l=0;255>l;l++)k.LOG_TABLE[k.EXP_TABLE[l]]=l;a.prototype={get:function(a){return this.num[a]},getLength:function(){return this.num.length},multiply:function(b){for(var c=Array(this.getLength()+b.getLength()-1),d=0;d<this.getLength();d++)for(var g=
0;g<b.getLength();g++)c[d+g]^=k.gexp(k.glog(this.get(d))+k.glog(b.get(g)));return new a(c,0)},mod:function(b){if(0>this.getLength()-b.getLength())return this;for(var c=k.glog(this.get(0))-k.glog(b.get(0)),d=Array(this.getLength()),g=0;g<this.getLength();g++)d[g]=this.get(g);for(g=0;g<b.getLength();g++)d[g]^=k.gexp(k.glog(b.get(g))+c);return(new a(d,0)).mod(b)}};b.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[2,35,17],[2,35,13],
[1,100,80],[2,50,32],[2,50,24],[4,25,9],[1,134,108],[2,67,43],[2,33,15,2,34,16],[2,33,11,2,34,12],[2,86,68],[4,43,27],[4,43,19],[4,43,15],[2,98,78],[4,49,31],[2,32,14,4,33,15],[4,39,13,1,40,14],[2,121,97],[2,60,38,2,61,39],[4,40,18,2,41,19],[4,40,14,2,41,15],[2,146,116],[3,58,36,2,59,37],[4,36,16,4,37,17],[4,36,12,4,37,13],[2,86,68,2,87,69],[4,69,43,1,70,44],[6,43,19,2,44,20],[6,43,15,2,44,16],[4,101,81],[1,80,50,4,81,51],[4,50,22,4,51,23],[3,36,12,8,37,13],[2,116,92,2,117,93],[6,58,36,2,59,37],[4,
46,20,6,47,21],[7,42,14,4,43,15],[4,133,107],[8,59,37,1,60,38],[8,44,20,4,45,21],[12,33,11,4,34,12],[3,145,115,1,146,116],[4,64,40,5,65,41],[11,36,16,5,37,17],[11,36,12,5,37,13],[5,109,87,1,110,88],[5,65,41,5,66,42],[5,54,24,7,55,25],[11,36,12],[5,122,98,1,123,99],[7,73,45,3,74,46],[15,43,19,2,44,20],[3,45,15,13,46,16],[1,135,107,5,136,108],[10,74,46,1,75,47],[1,50,22,15,51,23],[2,42,14,17,43,15],[5,150,120,1,151,121],[9,69,43,4,70,44],[17,50,22,1,51,23],[2,42,14,19,43,15],[3,141,113,4,142,114],[3,
70,44,11,71,45],[17,47,21,4,48,22],[9,39,13,16,40,14],[3,135,107,5,136,108],[3,67,41,13,68,42],[15,54,24,5,55,25],[15,43,15,10,44,16],[4,144,116,4,145,117],[17,68,42],[17,50,22,6,51,23],[19,46,16,6,47,17],[2,139,111,7,140,112],[17,74,46],[7,54,24,16,55,25],[34,37,13],[4,151,121,5,152,122],[4,75,47,14,76,48],[11,54,24,14,55,25],[16,45,15,14,46,16],[6,147,117,4,148,118],[6,73,45,14,74,46],[11,54,24,16,55,25],[30,46,16,2,47,17],[8,132,106,4,133,107],[8,75,47,13,76,48],[7,54,24,22,55,25],[22,45,15,13,
46,16],[10,142,114,2,143,115],[19,74,46,4,75,47],[28,50,22,6,51,23],[33,46,16,4,47,17],[8,152,122,4,153,123],[22,73,45,3,74,46],[8,53,23,26,54,24],[12,45,15,28,46,16],[3,147,117,10,148,118],[3,73,45,23,74,46],[4,54,24,31,55,25],[11,45,15,31,46,16],[7,146,116,7,147,117],[21,73,45,7,74,46],[1,53,23,37,54,24],[19,45,15,26,46,16],[5,145,115,10,146,116],[19,75,47,10,76,48],[15,54,24,25,55,25],[23,45,15,25,46,16],[13,145,115,3,146,116],[2,74,46,29,75,47],[42,54,24,1,55,25],[23,45,15,28,46,16],[17,145,115],
[10,74,46,23,75,47],[10,54,24,35,55,25],[19,45,15,35,46,16],[17,145,115,1,146,116],[14,74,46,21,75,47],[29,54,24,19,55,25],[11,45,15,46,46,16],[13,145,115,6,146,116],[14,74,46,23,75,47],[44,54,24,7,55,25],[59,46,16,1,47,17],[12,151,121,7,152,122],[12,75,47,26,76,48],[39,54,24,14,55,25],[22,45,15,41,46,16],[6,151,121,14,152,122],[6,75,47,34,76,48],[46,54,24,10,55,25],[2,45,15,64,46,16],[17,152,122,4,153,123],[29,74,46,14,75,47],[49,54,24,10,55,25],[24,45,15,46,46,16],[4,152,122,18,153,123],[13,74,
46,32,75,47],[48,54,24,14,55,25],[42,45,15,32,46,16],[20,147,117,4,148,118],[40,75,47,7,76,48],[43,54,24,22,55,25],[10,45,15,67,46,16],[19,148,118,6,149,119],[18,75,47,31,76,48],[34,54,24,34,55,25],[20,45,15,61,46,16]];b.getRSBlocks=function(a,c){var d=b.getRsBlockTable(a,c);if(void 0==d)throw Error("bad rs block @ typeNumber:"+a+"/errorCorrectLevel:"+c);for(var g=d.length/3,f=[],e=0;g>e;e++)for(var h=d[3*e+0],k=d[3*e+1],l=d[3*e+2],r=0;h>r;r++)f.push(new b(k,l));return f};b.getRsBlockTable=function(a,
c){switch(c){case n.L:return b.RS_BLOCK_TABLE[4*(a-1)+0];case n.M:return b.RS_BLOCK_TABLE[4*(a-1)+1];case n.Q:return b.RS_BLOCK_TABLE[4*(a-1)+2];case n.H:return b.RS_BLOCK_TABLE[4*(a-1)+3]}};f.prototype={get:function(a){return 1==(1&this.buffer[Math.floor(a/8)]>>>7-a%8)},put:function(a,b){for(var c=0;b>c;c++)this.putBit(1==(1&a>>>b-c-1))},getLengthInBits:function(){return this.length},putBit:function(a){var b=Math.floor(this.length/8);this.buffer.length<=b&&this.buffer.push(0);a&&(this.buffer[b]|=
128>>>this.length%8);this.length++}};var r=[[17,14,11,7],[32,26,20,14],[53,42,32,24],[78,62,46,34],[106,84,60,44],[134,106,74,58],[154,122,86,64],[192,152,108,84],[230,180,130,98],[271,213,151,119],[321,251,177,137],[367,287,203,155],[425,331,241,177],[458,362,258,194],[520,412,292,220],[586,450,322,250],[644,504,364,280],[718,560,394,310],[792,624,442,338],[858,666,482,382],[929,711,509,403],[1003,779,565,439],[1091,857,611,461],[1171,911,661,511],[1273,997,715,535],[1367,1059,751,593],[1465,1125,
805,625],[1528,1190,868,658],[1628,1264,908,698],[1732,1370,982,742],[1840,1452,1030,790],[1952,1538,1112,842],[2068,1628,1168,898],[2188,1722,1228,958],[2303,1809,1283,983],[2431,1911,1351,1051],[2563,1989,1423,1093],[2699,2099,1499,1139],[2809,2213,1579,1219],[2953,2331,1663,1273]],l=function(){var a=function(a,b){this._el=a;this._htOption=b};return a.prototype.draw=function(a){function b(a,b){var c=document.createElementNS("http://www.w3.org/2000/svg",a),d;for(d in b)b.hasOwnProperty(d)&&c.setAttribute(d,
b[d]);return c}var c=this._htOption,d=this._el,g=a.getModuleCount();Math.floor(c.width/g);Math.floor(c.height/g);this.clear();var f=b("svg",{viewBox:"0 0 "+String(g)+" "+String(g),width:"100%",height:"100%",fill:c.colorLight});f.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:xlink","http://www.w3.org/1999/xlink");d.appendChild(f);f.appendChild(b("rect",{fill:c.colorDark,width:"1",height:"1",id:"template"}));for(c=0;g>c;c++)for(d=0;g>d;d++)if(a.isDark(c,d)){var e=b("use",{x:String(c),y:String(d)});
e.setAttributeNS("http://www.w3.org/1999/xlink","href","#template");f.appendChild(e)}},a.prototype.clear=function(){for(;this._el.hasChildNodes();)this._el.removeChild(this._el.lastChild)},a}(),t="svg"===document.documentElement.tagName.toLowerCase()?l:"undefined"!=typeof CanvasRenderingContext2D?function(){function a(){this._elImage.src=this._elCanvas.toDataURL("image/png");this._elImage.style.display="block";this._elCanvas.style.display="none"}function b(a,b){var c=this;if(c._fFail=b,c._fSuccess=
a,null===c._bSupportDataURI){var d=document.createElement("img"),g=function(){c._bSupportDataURI=!1;c._fFail&&_fFail.call(c)};return d.onabort=g,d.onerror=g,d.onload=function(){c._bSupportDataURI=!0;c._fSuccess&&c._fSuccess.call(c)},d.src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==",void 0}!0===c._bSupportDataURI&&c._fSuccess?c._fSuccess.call(c):!1===c._bSupportDataURI&&c._fFail&&c._fFail.call(c)}if(this._android&&
2.1>=this._android){var d=1/window.devicePixelRatio,f=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(a,b,c,g,e,h,k,l){if("nodeName"in a&&/img/i.test(a.nodeName))for(var r=arguments.length-1;1<=r;r--)arguments[r]*=d;else"undefined"==typeof l&&(arguments[1]*=d,arguments[2]*=d,arguments[3]*=d,arguments[4]*=d);f.apply(this,arguments)}}var e=function(a,b){this._bIsPainted=!1;this._android=c();this._htOption=b;this._elCanvas=document.createElement("canvas");
this._elCanvas.width=b.width;this._elCanvas.height=b.height;a.appendChild(this._elCanvas);this._el=a;this._oContext=this._elCanvas.getContext("2d");this._bIsPainted=!1;this._elImage=document.createElement("img");this._elImage.style.display="none";this._el.appendChild(this._elImage);this._bSupportDataURI=null};return e.prototype.draw=function(a){var b=this._elImage,c=this._oContext,d=this._htOption,g=a.getModuleCount(),f=d.width/g,e=d.height/g,h=Math.round(f),k=Math.round(e);b.style.display="none";
this.clear();for(b=0;g>b;b++)for(var l=0;g>l;l++){var r=a.isDark(b,l),m=l*f,p=b*e;c.strokeStyle=r?d.colorDark:d.colorLight;c.lineWidth=1;c.fillStyle=r?d.colorDark:d.colorLight;c.fillRect(m,p,f,e);c.strokeRect(Math.floor(m)+.5,Math.floor(p)+.5,h,k);c.strokeRect(Math.ceil(m)-.5,Math.ceil(p)-.5,h,k)}this._bIsPainted=!0},e.prototype.makeImage=function(){this._bIsPainted&&b.call(this,a)},e.prototype.isPainted=function(){return this._bIsPainted},e.prototype.clear=function(){this._oContext.clearRect(0,0,
this._elCanvas.width,this._elCanvas.height);this._bIsPainted=!1},e.prototype.round=function(a){return a?Math.floor(1E3*a)/1E3:a},e}():function(){var a=function(a,b){this._el=a;this._htOption=b};return a.prototype.draw=function(a){for(var b=this._htOption,c=this._el,d=a.getModuleCount(),g=Math.floor(b.width/d),f=Math.floor(b.height/d),e=['<table style="border:0;border-collapse:collapse;">'],h=0;d>h;h++){e.push("<tr>");for(var k=0;d>k;k++)e.push('<td style="border:0;border-collapse:collapse;padding:0;margin:0;width:'+
g+"px;height:"+f+"px;background-color:"+(a.isDark(h,k)?b.colorDark:b.colorLight)+';"></td>');e.push("</tr>")}e.push("</table>");c.innerHTML=e.join("");a=c.childNodes[0];c=(b.width-a.offsetWidth)/2;b=(b.height-a.offsetHeight)/2;0<c&&0<b&&(a.style.margin=b+"px "+c+"px")},a.prototype.clear=function(){this._el.innerHTML=""},a}();QRCode=function(a,b){if(this._htOption={width:256,height:256,typeNumber:4,colorDark:"#000000",colorLight:"#ffffff",correctLevel:n.H},"string"==typeof b&&(b={text:b}),b)for(var d in b)this._htOption[d]=
b[d];"string"==typeof a&&(a=document.getElementById(a));this._android=c();this._el=a;this._oQRCode=null;this._oDrawing=new t(this._el,this._htOption);this._htOption.text&&this.makeCode(this._htOption.text)};QRCode.prototype.makeCode=function(a){var b=this._htOption.correctLevel,c=1,d;d=encodeURI(a).toString().replace(/\%[0-9a-fA-F]{2}/g,"a");d=d.length+(d.length!=a?3:0);for(var g=0,f=r.length;f>=g;g++){var h=0;switch(b){case n.L:h=r[g][0];break;case n.M:h=r[g][1];break;case n.Q:h=r[g][2];break;case n.H:h=
r[g][3]}if(h>=d)break;c++}if(c>r.length)throw Error("Too long data");this._oQRCode=new e(c,this._htOption.correctLevel);this._oQRCode.addData(a);this._oQRCode.make();this._el.title=a;this._oDrawing.draw(this._oQRCode);this.makeImage()};QRCode.prototype.makeImage=function(){"function"==typeof this._oDrawing.makeImage&&(!this._android||3<=this._android)&&this._oDrawing.makeImage()};QRCode.prototype.clear=function(){this._oDrawing.clear()};QRCode.CorrectLevel=n}();
var SequenceSettingPage=function(){function h(a){var b=a.target.parentNode.id;"repeatsSetting"!==b&&(b="beatsSetting");var c=a.target.parentNode.querySelector("div#value"),f=parseInt(c.innerHTML);isNaN(f)&&(f=0);var e=f;"plus"===a.target.id?e+=1:"plusplus"===a.target.id?e+=10:"minus"===a.target.id?--e:"minusminus"===a.target.id&&(e-=10);"beatsSetting"===b?(240<e&&(e=240),20>e&&(e=20),a="a"===a.target.parentNode.id?0:parseInt(a.target.parentNode.id),e!==f&&(l.markDirty(),d.sequences[k].beats[a]=e)):
(0>=e&&(e=0),e!==f&&(l.markDirty(),d.sequences[k].amount=e),0>=e&&(e="\u221e"));c.innerHTML=""+e}function e(){var a=document.querySelector("body > div#container > div#sequenceSetting > div#beatsSettingGroup"),b="";if(d.sequences[k].hasUniformBeats)b+='<div class="beatsSetting" id="ID"><div class="shortlabel">LABEL</div><div class="valueControl" id="minusminus"></div><div class="valueControl" id="minus"></div><div class="beats" id="value">VALUE</div><div class="valueControl" id="plus"></div><div class="valueControl" id="plusplus"></div></div>'.replace("ID",
"a").replace("LABEL","BPM").replace("VALUE",d.sequences[k].beats[0]);else for(var c=0;c<d.sequences[k].beats.length;c++)b+='<div class="beatsSetting" id="ID"><div class="shortlabel">LABEL</div><div class="valueControl" id="minusminus"></div><div class="valueControl" id="minus"></div><div class="beats" id="value">VALUE</div><div class="valueControl" id="plus"></div><div class="valueControl" id="plusplus"></div></div>'.replace("ID",c).replace("LABEL","BPM "+(c+1)).replace("VALUE",d.sequences[k].beats[c]);
a.innerHTML=b;a=a.querySelectorAll("div.valueControl");for(c=0;c<a.length;c++)a[c].addEventListener("click",h)}function a(a){var b=document.querySelector("body > div#container > div#sequenceSetting > div#beatsSettingGroup");if(a<=b.childNodes.length)d.sequences[k].beats.splice(a);else for(var c=parseInt(b.childNodes[b.childNodes.length-1].querySelector("div#value").innerHTML),e=0;e<a-b.childNodes.length;e++)d.sequences[k].beats.push(c)}function b(){l.markDirty();d.sequences[k].time=this.value;var b=
document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#uniformSetting > input#uniformBeats");"1/1"===this.value?(a(1),e(),b.disabled=!0):(b.disabled=!1,b.checked||(a(parseInt(this.value.substr(0,this.value.indexOf("/")))),e()))}function f(){l.markDirty();if(d.sequences[k].hasUniformBeats=this.checked)a(1);else{var b=document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#timeSignatureSetting > select#time").value,b=parseInt(b.substr(0,
b.indexOf("/")));a(b)}e()}function c(a){a=a.target.id;if("ok"===a)localStorage.setItem("_config_"+d.id,JSON.stringify(d));else if("cancel"===a){if(l.isDirty()&&!confirm("Exit without saving changes?"))return}else{confirm("Do you want to discard all the changes?")&&(l.markClean(),d=JSON.parse(localStorage.getItem("_config_"+d.id)),n());return}window.location=App.getPagePath(IndexPage)+"?c="+d.id}function m(a){a=a.target.id;if("delete"===a){if(1>=d.sequences.length){alert("You cannot delete the last sequence in this config.");
return}if(confirm("Don you want to delete this sequence?"))d.sequences.splice(k,1);else return}else"insertBefore"===a?d.sequences.splice(k,0,Locale.getDefaultConfig().sequences[0]):"insertAfter"===a&&d.sequences.splice(k+1,0,Locale.getDefaultConfig().sequences[0]);localStorage.setItem("_config_"+d.id,JSON.stringify(d));window.location=url=App.getPagePath(IndexPage)+"?c="+d.id}function n(){document.querySelector("body > div#container > div#sequenceSetting > div#header > div#title").innerHTML="Sequence "+
(k+1)+" in "+d.name;document.querySelector("body > div#container > div#sequenceSetting > div#sequenceNameSetting > input#name ").value=d.sequences[k].name;document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#timeSignatureSetting > select#time ").value=d.sequences[k].time;document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#uniformSetting > input#uniformBeats").checked=d.sequences[k].hasUniformBeats;e();var a=""+d.sequences[k].amount;
"0"===a&&(a="\u221e");document.querySelector("body > div#container > div#sequenceSetting > div#repeatsSetting > div#value").innerHTML=a;for(var n=document.querySelectorAll("body > div#container > div#sequenceSetting > div#repeatsSetting > div.valueControl"),a=0;a<n.length;a++)n[a].addEventListener("click",h);document.querySelector("body > div#container > div#sequenceSetting > div#sequenceNameSetting > input#name").addEventListener("change",function(){l.markDirty();d.sequences[k].name=this.value});
document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#timeSignatureSetting > select#time").addEventListener("change",b);document.querySelector("body > div#container > div#sequenceSetting > div#timeSetting > div#uniformSetting > input#uniformBeats").addEventListener("change",f);n=document.querySelectorAll("body > div#container > div#sequenceSetting > div#buttons > div.button");for(a=0;a<n.length;a++)n[a].addEventListener("click",c);n=document.querySelectorAll("body > div#container > div#sequenceSetting > div#header > div#controls > div.control");
for(a=0;a<n.length;a++)n[a].addEventListener("click",m)}var d=null,k=0,l=null;return{initialize:function(a){l=new DirtyManager([document.querySelector("body > div#container > div#sequenceSetting > div#buttons > div.button#revert")]);var b=a.c;k=parseInt(a.s);"string"===typeof b&&/[a-zA-Z0-9]{32}/.test(b)&&"_config_"+b in localStorage?(a=localStorage.getItem("_config_"+b),d=JSON.parse(a),isNaN(k)||k>=d.sequences.length?(alert("Invalid sequence index. Please select again."),window.location=App.getPagePath(IndexPage)+
"?c="+b):n()):(alert("No config id. Please select a config."),window.location=App.getPagePath(CatalogPage))},draw:function(){},getPath:function(){return"/sequenceSetting.html"}}}(),SharePage=function(){function h(){window.location=null!==c?App.getPagePath(IndexPage)+"?c="+c.id:App.getPagePath(CatalogPage)}function e(a){var b=a.target.id;b in n?(a=n[b].replace("URL",encodeURIComponent(m.url)).replace("DESCRIPTION",encodeURIComponent(m.description)).replace("VIA","Metronome"),window.open(a,"_blank")):
"mail"==b?(a="mailto:?subject="+encodeURIComponent(m.description)+"&body="+encodeURIComponent(m.url),window.open(a,"_blank")):"link"==a.target.id&&(a=document.querySelector("body > input#copy"),a.classList.remove("hidden"),a.value=m.url,a.select(),document.execCommand("copy"),a.classList.add("hidden"));h()}function a(){for(var a=document.querySelectorAll("body > div#container > div#share > div#services > div.service"),b=0;b<a.length;b++)a[b].addEventListener("click",e);document.querySelector("body > div#container > div#share > div#buttons > div.button#ok").addEventListener("click",
function(){h()});document.querySelector("body > div#container > div#share > div#title").innerHTML="Share "+m.description+" to your friends!";document.querySelector("body > div#container > div#import").classList.add("hidden");document.querySelector("body > div#container > div#share").classList.remove("hidden");history.replaceState("","",m.uri);f()}function b(b){"string"===typeof b&&/[a-zA-Z0-9]{32}/.test(b)&&"_config_"+b in localStorage&&(b=localStorage.getItem("_config_"+b),c=JSON.parse(b));var d=
App.getRootPath(),e="";b="Metronome";null!==c&&"default"!==c.id&&(d=App.getPagePath(SharePage),e=Config.toURLString(c),b="Metronome "+c.name);d+=""===e?"":"?d="+encodeURIComponent(e);m={url:App.getHost()+d,description:b,uri:d};a()}function f(){var a=Math.min(window.innerWidth,window.innerHeight-180)-16;256<a&&(a=256);var b=document.querySelector("body > div#container > div#share > div#qrContainer");b.innerHTML='<div id="qrCode"></div>';b=b.querySelector("div#qrCode");b.innerHTML="";b.style.width=
a+"px";b.style.height=a+"px";new QRCode("qrCode",{text:m.url,width:a,height:a,colorDark:"#000000",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H})}var c=null,m=null,n={qq:"http://v.t.qq.com/share/share.php?url=URL&title=DESCRIPTION",weibo:"http://service.weibo.com/share/share.php?url=URL&title=DESCRIPTION",qzone:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=URL&title=DESCRIPTION",facebook:"https://www.facebook.com/sharer/sharer.php?u=URL&t=DESCRIPTION",twitter:"https://twitter.com/intent/tweet?text=DESCRIPTION&url=URL&via=VIA"};
return{initialize:function(a){var c=a.c;a=a.d;if("string"===typeof a)if(LoadingIconManager.show(),a=Config.fromURLString(a),null===a)LoadingIconManager.hide(),b(c);else{document.querySelector("body > div#container > div#import").innerHTML="Importing...";a:{for(var d in localStorage)if(0===d.indexOf("_config_")&&(c=JSON.parse(localStorage[d]),Config.isEquivalent(c,a))){LoadingIconManager.hide();window.location=App.getPagePath(IndexPage)+"?c="+c.id;break a}a.id=Config.generateConfigId();a.name=Config.getNextAvailableName(a.name);
localStorage.setItem("_config_"+a.id,JSON.stringify(a));LoadingIconManager.hide();window.location=App.getPagePath(IndexPage)+"?c="+a.id}}else b(c)},draw:f,getPath:function(){return"/share.html"}}}(),App=function(){function h(){a.draw()}var e={},a=null;return{initialize:function(b){b=void 0===b?{}:b;Header.initialize();"Player"in window&&Player.initialize();for(var f=window.location.pathname,c=window.location.search,c=("?"===c[0]?c.substr(1):c).split("&"),m=0;m<c.length;m++){var n=c[m].split("=");
b[decodeURIComponent(n[0])]=decodeURIComponent(n[1]||"")}b.lastPage=sessionStorage.lastPage||null;e=b;c=null;0===f.indexOf("/m1"+CatalogPage.getPath())?a=CatalogPage:0===f.indexOf("/m1"+AboutPage.getPath())?a=AboutPage:0===f.indexOf("/m1"+SequenceSettingPage.getPath())?(a=SequenceSettingPage,c=IndexPage):0===f.indexOf("/m1"+ConfigSettingPage.getPath())?(a=ConfigSettingPage,c=IndexPage):0===f.indexOf("/m1"+SharePage.getPath())?(a=SharePage,c=IndexPage):a=IndexPage;Header.highlight(null===c?a:c);a.initialize(b);
sessionStorage.setItem("lastPage",a.getPath());window.addEventListener("resize",h)},getParams:function(){return e},getHost:function(){var a="";"http:"===window.location.protocol&&"80"!==window.location.port&&(a=":"+window.location.port);"https:"===window.location.protocol&&"443"!==window.location.port&&(a=":"+window.location.port);return window.location.protocol+"//"+window.location.hostname+a},getRootPath:function(){return"/m1"},getPagePath:function(a){return"/m1"+(void 0===a?null:a).getPath()},
resize:h}}();
	//---------------------------------------------------------------------
	// QRCode for JavaScript
	//
	// Copyright (c) 2009 Kazuhiko Arase
	//
	// URL: http://www.d-project.com/
	//
	// Licensed under the MIT license:
	//   http://www.opensource.org/licenses/mit-license.php
	//
	// The word "QR Code" is registered trademark of 
	// DENSO WAVE INCORPORATED
	//   http://www.denso-wave.com/qrcode/faqpatent-e.html
	//
	//---------------------------------------------------------------------

