var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[d]=b.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var d=0;return $jscomp.iteratorPrototype(function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.polyfill=function(c,d,b,f){if(d){b=$jscomp.global;c=c.split(".");for(f=0;f<c.length-1;f++){var e=c[f];e in b||(b[e]={});b=b[e]}c=c[c.length-1];f=b[c];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(b,c,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.from",function(c){return c?c:function(d,b,c){$jscomp.initSymbolIterator();b=null!=b?b:function(g){return g};var e=[],a=d[Symbol.iterator];if("function"==typeof a)for(d=a.call(d);!(a=d.next()).done;)e.push(b.call(c,a.value));else for(var a=d.length,f=0;f<a;f++)e.push(b.call(c,d[f]));return e}},"es6-impl","es3");$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var d=c[Symbol.iterator];return d?d.call(c):$jscomp.arrayIterator(c)};
$jscomp.owns=function(c,d){return Object.prototype.hasOwnProperty.call(c,d)};
$jscomp.polyfill("WeakMap",function(c){function d(a){$jscomp.owns(a,f)||$jscomp.defineProperty(a,f,{value:{}})}function b(a){var g=Object[a];g&&(Object[a]=function(a){d(a);return g(a)})}if(function(){if(!c||!Object.seal)return!1;try{var a=Object.seal({}),g=Object.seal({}),b=new c([[a,2],[g,3]]);if(2!=b.get(a)||3!=b.get(g))return!1;b["delete"](a);b.set(g,4);return!b.has(a)&&4==b.get(g)}catch(k){return!1}}())return c;var f="$jscomp_hidden_"+Math.random().toString().substring(2);b("freeze");b("preventExtensions");
b("seal");var e=0,a=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var g;!(g=a.next()).done;)g=g.value,this.set(g[0],g[1])}};a.prototype.set=function(a,g){d(a);if(!$jscomp.owns(a,f))throw Error("WeakMap key fail: "+a);a[f][this.id_]=g;return this};a.prototype.get=function(a){return $jscomp.owns(a,f)?a[f][this.id_]:void 0};a.prototype.has=function(a){return $jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)};a.prototype["delete"]=
function(a){return $jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)?delete a[f][this.id_]:!1};return a},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(c){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new c($jscomp.makeIterator([[a,"s"]]));if("s"!=b.get(a)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var k=b.entries(),e=k.next();if(e.done||e.value[0]!=a||"s"!=e.value[1])return!1;e=k.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!k.next().done?!1:!0}catch(n){return!1}}())return c;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var d=new WeakMap,b=function(g){this.data_={};this.head_=a();this.size=0;if(g){g=$jscomp.makeIterator(g);for(var b;!(b=g.next()).done;)b=b.value,this.set(b[0],b[1])}};b.prototype.set=function(a,b){var g=f(this,a);g.list||(g.list=this.data_[g.id]=[]);g.entry?g.entry.value=b:(g.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},g.list.push(g.entry),this.head_.previous.next=g.entry,this.head_.previous=g.entry,this.size++);return this};b.prototype["delete"]=
function(a){a=f(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};b.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=a();this.size=0};b.prototype.has=function(a){return!!f(this,a).entry};b.prototype.get=function(a){return(a=f(this,a).entry)&&a.value};b.prototype.entries=function(){return e(this,function(a){return[a.key,
a.value]})};b.prototype.keys=function(){return e(this,function(a){return a.key})};b.prototype.values=function(){return e(this,function(a){return a.value})};b.prototype.forEach=function(a,b){for(var e=this.entries(),g;!(g=e.next()).done;)g=g.value,a.call(b,g[1],g[0],this)};b.prototype[Symbol.iterator]=b.prototype.entries;var f=function(a,b){var g;g=b&&typeof b;"object"==g||"function"==g?d.has(b)?g=d.get(b):(g=""+ ++h,d.set(b,g)):g="p_"+b;var e=a.data_[g];if(e&&$jscomp.owns(a.data_,g))for(var c=0;c<
e.length;c++){var f=e[c];if(b!==b&&f.key!==f.key||b===f.key)return{id:g,list:e,index:c,entry:f}}return{id:g,list:e,index:-1,entry:void 0}},e=function(a,b){var g=a.head_;return $jscomp.iteratorPrototype(function(){if(g){for(;g.head!=a.head_;)g=g.previous;for(;g.next!=g.head;)return g=g.next,{done:!1,value:b(g)};g=null}return{done:!0,value:void 0}})},a=function(){var a={};return a.previous=a.next=a.head=a},h=0;return b},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(c){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new c($jscomp.makeIterator([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),a=e.next();if(a.done||a.value[0]!=b||a.value[1]!=b)return!1;a=e.next();return a.done||a.value[0]==b||4!=a.value[0].x||a.value[1]!=a.value[0]?!1:e.next().done}catch(h){return!1}}())return c;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var d=function(b){this.map_=new Map;if(b){b=$jscomp.makeIterator(b);for(var d;!(d=b.next()).done;)this.add(d.value)}this.size=this.map_.size};d.prototype.add=function(b){this.map_.set(b,b);this.size=this.map_.size;return this};d.prototype["delete"]=function(b){b=this.map_["delete"](b);this.size=this.map_.size;return b};d.prototype.clear=function(){this.map_.clear();this.size=0};d.prototype.has=function(b){return this.map_.has(b)};d.prototype.entries=
function(){return this.map_.entries()};d.prototype.values=function(){return this.map_.values()};d.prototype[Symbol.iterator]=d.prototype.values;d.prototype.forEach=function(b,d){var e=this;this.map_.forEach(function(a){return b.call(d,a,a,e)})};return d},"es6-impl","es3");$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(c,d){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var b=0,f={next:function(){if(b<c.length){var e=b++;return{value:d(e,c[e]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6-impl","es3");
var AboutPage=function(){return{initialize:function(c){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){Header.handlePlay()})},draw:function(){},getPath:function(){return"/about.html"}}}(),AJAX=function(){return{GET:function(c,d,b){d=void 0===d?null:d;b=void 0===b?null:b;var f=new XMLHttpRequest;f.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==d&&d(this.responseText):null!==b&&b(this.status))};f.open("GET",
c,!0);f.send()}}}(),CatalogPage=function(){function c(){AJAX.GET(App.getPiecesPath()+"indexes.json",function(b){b=JSON.parse(b);var g=b.scales;1==a.length?b.hasOwnProperty(a[0])&&(g=b[a[0]]):1<a.length&&"scales"==a[0]&&b.scales.hasOwnProperty(a[1])&&(g=b.scales[a[1]]);e={query:a,tiles:[]};b=[];for(c in g)g.hasOwnProperty(c)&&"_"!==c.substring(0,1)&&b.push(c);b.sort(function(a,b){var d=Locale.getTranslation(g[a]._desc,"en"),e=Locale.getTranslation(g[b]._desc,"en");return d<e?-1:d>e?1:0});for(var d=
0;d<b.length;d++){var c=b[d],h=g[c];if("_"!==c.substring(0,1)){var c={id:c,description:h._desc},q=0;for(keyInNextLevel in h)h.hasOwnProperty(keyInNextLevel)&&"_"!==keyInNextLevel.substring(0,1)&&(q+=1);0>=q?c.type="piece":(c.type="folder",c.total=q);e.tiles.push(c)}}f()})}function d(a){a=a.target.getAttribute("data");window.location=App.getPagePath(CatalogPage)+"?q="+encodeURIComponent("scales,"+a)}function b(a){window.location=App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a.target.getAttribute("data"))}
function f(){for(var a=0;a<e.tiles.length;a++){var c=e.tiles[a];if("folder"==c.type){var f=document.createElement("div");f.classList.add("tile");f.classList.add("folder");f.setAttribute("data",c.id);f.innerHTML=Locale.getTranslation(c.description);f.addEventListener("click",d);h.append(f)}else f=document.createElement("div"),f.classList.add("tile"),f.classList.add("piece"),f.setAttribute("data",c.id),f.innerHTML=Locale.getTranslation(c.description),f.addEventListener("click",b),h.append(f),c.hasOwnProperty("data")}}
var e={},a="",h=null;return{initialize:function(b){h=document.querySelector("div#tiles");window.hasOwnProperty("catalogSnapshot")&&(e=window.catalogSnapshot);parseInt(b.p);a=Array.from(new Set((b.q||"").split(",")));c()},draw:function(){},getPath:function(){return"/catalog.html"}}}(),Header=function(){function c(){var a=App.getParams(),b="default";a.hasOwnProperty("p")?b=a.p:"lastPieceId"in sessionStorage&&(b=sessionStorage.lastPieceId);return b}function d(){var a=c();window.location=App.getPagePath(IndexPage)+
"?p="+encodeURIComponent(a)+"&v=0"}function b(){var a=c();window.location=App.getPagePath(ViewerPage)+"?p="+encodeURIComponent(a)+"&b=0"}function f(){window.location=App.getPagePath(CatalogPage)}function e(){window.location=App.getPagePath(AboutPage)}return{initialize:function(){document.querySelector("div#header > div#controls > div.control#play").addEventListener("click",d);document.querySelector("div#header > div#controls > div.control#view").addEventListener("click",b);document.querySelector("div#header > div#controls > div.control#open").addEventListener("click",
f);document.querySelector("div#header > div#title  > div#text").addEventListener("click",e);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",e);document.querySelector("div#header > div#title  > div#text").innerHTML=Locale.getApplicationTitle()},handlePlay:d}}(),IndexPage=function(){function c(){var a=k.getNextBar(m),b=0;null!==a&&(b=a.first);AJAX.GET(window.location.pathname+"?p="+k.getData().id+"&v="+b,function(){})}function d(a){var b=a.clientX,c=a.clientY;"ontouchstart"in
window&&(b=a.touches[0].clientX,c=a.touches[0].clientY);f(b,c)}function b(a){a=null;for(var b=document.querySelectorAll("body > div#container > div#notes > div.note"),c=0;c<b.length;c++)if(b[c].classList.contains("selected")){a=b[c];break}if(null!==a){a.classList.remove("selected");ViolinSimulator.stop();var b=k.getBar(m),c=m-b.first,d=b.verticals[c],d=Array.from(d.notes.keys());"playAllNotesAndMoveNext"!==a.id?(d=[parseInt(a.getAttribute("value"))],l.changeNotesColor(c,d,"green"),l.changeNotesSize(c,
d,1)):(l.changeNotesColor(c,d,"black"),l.changeNotesSize(c,d,1),m+=1,a=!1,m>=b.first+b.verticals.length&&(a=!0),m>=k.getTotalVerticals()&&(m=0),a?window.location=window.location.pathname+"?p="+k.getData().id+"&v="+m:(c+=1,d=b.verticals[c],d=Array.from(d.notes.keys()),l.changeNotesColor(c,d,"green"),l.changeNotesSize(c,d,1),e()))}}function f(a,b){for(var c=null,d=document.querySelectorAll("body > div#container > div#notes > div.note"),e=0;e<d.length;e++){var g=d[e].getBoundingClientRect();if(a>=g.left&&
a<=g.right&&b>=g.top&&b<=g.bottom){c=d[e];break}}if(null!==c)if(c.classList.contains("note")||(c=c.parentNode),c.classList.add("selected"),null===k)t={x:a,y:b};else{var e=k.getBar(m),d=m-e.first,g=e.verticals[d],f=[],h=[];if("playAllNotesAndMoveNext"===c.id)for(e=0;e<g.notes.length;e++)f.push(Note.getNoteFrequency(g.notes[e])),h.push(e);else c=parseInt(c.getAttribute("value")),f.push(Note.getNoteFrequency(g.notes[c])),h.push(c);"r"===g.duration.substr(-1)?ViolinSimulator.play([0]):ViolinSimulator.play(f);
l.changeNotesColor(d,h,"red");l.changeNotesSize(d,h,1.3)}}function e(){for(var a=document.querySelectorAll("body > div#container > div#notes > div.note"),b=0;b<a.length;b++)"playAllNotesAndMoveNext"!==a[b].id&&a[b].parentNode.removeChild(a[b]);var a=document.querySelector("body > div#container > div#notes"),b=k.getBar(m),c=b.verticals[m-b.first];if("r"!==c.duration.substr(-1))for(b=c.notes.length-1;0<=b;b--){var d=document.createElement("div");d.classList.add("note");d.setAttribute("value",""+b);
var e=d,g;g=Note.getNoteDetail(c.notes[b]);var f=""===g.accidental?"":"withAccidental";g=('<div class="natural YYY">'+g.natural+'</div><div class="accidental XXX"></div><div class="octave ZZZ">'+g.octave+"</div>").replace("XXX",""===g.accidental?"hidden":g.accidental).replace("YYY",f).replace("ZZZ",f);e.innerHTML=g;a.appendChild(d)}}function a(){null!==k&&(l.setPiece(k),l.setFocus(m),l.display(),e())}function h(){m>=k.getTotalVerticals()&&(m=0);a();var b=k.getBar(m),d=m-b.first;l.changeNotesColor(d,
Array.from(b.verticals[d].notes.keys()),"green");null!==t&&f(t.x,t.y);k.getData();document.querySelector("body > div#container > div#musicTitle").innerHTML=Locale.getTranslation(k.getData().descriptions);sessionStorage.lastPieceId=k.getData().id;c()}function g(){return"/index.html"}var l=null,k=null,m=0,n="mousedown",q="mouseup",t=null;"ontouchstart"in window&&(n="touchstart",q="touchend");return{initialize:function(a){window.addEventListener(n,d);window.addEventListener(q,b);l=new MusicPlayer(document.querySelector("body > div#container > div#music"));
var c=a.p||"default";m=parseInt(a.v)||0;t="unhandledEvent"in a&&a.lastPage===g()?a.unhandledEvent:null;k=MusicStorageManager.getPiece(c);null!==k?h():(LoadingIconManager.show(),AJAX.GET(App.getPiecesPath()+c+".json",function(a){k=Piece.createFromString(a);MusicStorageManager.setPiece(k);h();LoadingIconManager.hide()},function(a){alert(Locale.getPieceLoadingFailureNotice(c));window.location=App.getPagePath(CatalogPage)}))},draw:a,getPath:g}}(),LoadingIconManager=function(){var c=0,d=document.querySelector("body > div#loading");
return{show:function(){setTimeout(function(){100<(new Date).getTime()-c&&d.classList.remove("hidden")},100)},hide:function(){d.classList.add("hidden");c=(new Date).getTime()}}}(),Locale=function(){function c(){if("language"in localStorage&&0<=b.indexOf(localStorage.language))f=localStorage.language;else{var a=navigator.languages&&navigator.languages[0]||navigator.language||navigator.userLanguage,a=a.toLowerCase();f=0<=b.indexOf(a)?a:"en"}}function d(a,b){b=void 0===b?"":b;""===b&&(b=f);return b in
a?a[b]:a.en}var b=["en","zh-cn"],f="en",e={en:"Check more from $1","zh-cn":"\u66f4\u591a\u8d44\u6e90\u5728 $1"},a={en:"Cannot load piece $piece from $address. Please choose a new one.","zh-cn":"\u65e0\u6cd5\u4ece$address\u4e0b\u8f7d\u66f2\u76ee$piece\u3002\u8bf7\u9009\u62e9\u65b0\u66f2\u76ee\u3002"},h={en:"ViolinEscort","zh-cn":"\u5c0f\u63d0\u7434\u4f34\u4fa3"};c();return{checkLanguage:c,getApplicationTitle:function(){return d(h)},getPrintFooter:function(){return f in e?e[f].replace("$1",window.location.hostname+
App.getRootPath()):e.en.replace("$1",window.location.hostname+App.getRootPath())},getTranslation:d,getPieceLoadingFailureNotice:function(b){return f in a?a[f].replace("$piece",b).replace("$address",window.location.hostname+App.getRootPath()):a.en.replace("$piece",b).replace("$address",window.location.hostname+App.getRootPath())}}}();
function MusicPlayer(c){function d(a){for(var b=a.first,c=[],d=0;d<a.verticals.length;d++){for(var e=[],g=0;g<a.verticals[d].notes.length;g++)e.push({color:"black",size:"1.0"});c.push(e)}return{isOnBar:function(a){return b===a.first},changeNotesSize:function(a,b,d){for(var e=0;e<b.length;e++)c[a][b[e]].size=d},changeNotesColor:function(a,b,d){for(var e=0;e<b.length;e++)c[a][b[e]].color=d},drawAllOrnaments:function(){for(var a=0;a<c.length;a++)for(var b=0;b<c[a].length;b++){if("1.0"!==c[a][b].size){var d=
f(a,[b]);d[0].style.transform="scale("+c[a][b].size+")";d[0].style.transformOrigin="50% 50%"}"black"!==c[a][b].color&&(d=f(a,[b]),d[0].setAttribute("fill",c[a][b].color))}}}}function b(){a.innerHTML="";var b=new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.SVG);context=b.getContext();b.resize(a.clientWidth,a.clientHeight);context.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return context}function f(a,b){for(var c=document.querySelectorAll("#vf-"+g[a].attrs.id+" g.vf-notehead path"),
d=[],e=0;e<b.length;e++)d.push(c[b[e]]);return d}function e(a){var b=h.getBar(a);return a-b.first}var a=c,h=null,g=[],l=0,k=null;return{setPiece:function(a){h=a;l=0},setFocus:function(a){l=a},display:function(){var a=b(),c=new Vex.Flow.Stave(4,40,a.width-8),e=h.getBar(l);c.addClef("treble").addTimeSignature(e.time).addKeySignature(VFUtility.toVFKeySignature(e.key));c.setMeasure(h.getData().bars.indexOf(e)+1);c.setContext(a).draw();g=[];for(var f={},A=0;A<e.verticals.length;A++)g.push(VFUtility.prepareStaveNote(e.key,
e.verticals[A],f));f=Vex.Flow.Beam.generateBeams(g);Vex.Flow.Formatter.FormatAndDraw(a,c,g);f.forEach(function(b){b.setContext(a).draw()});null!==k&&k.isOnBar(e)?k.drawAllOrnaments():k=new d(e)},changeNotesSize:function(a,b,c){c=void 0===c?"1.0":c;a=e(a);for(var d=f(a,b),g=0;g<d.length;g++)d[g].style.transform="scale("+c+")",d[g].style.transformOrigin="50% 50%";k.changeNotesSize(a,b,c)},changeNotesColor:function(a,b,c){c=void 0===c?"black":c;a=e(a);for(var d=f(a,b),g=0;g<d.length;g++)d[g].setAttribute("fill",
c);k.changeNotesColor(a,b,c)}}}var MusicStorageManager=function(){return{getPiece:function(c){c=localStorage.getItem("_piece_"+c);return null===c?null:Piece.createFromString(c)},setPiece:function(c){localStorage.setItem("_piece_"+c.id,JSON.stringify(c))}}}();
function MusicViewer(c){function d(){e.innerHTML="";var a=Vex.Flow.Renderer.Backends.SVG;"CANVAS"===e.tagName.toUpperCase()&&(a=Vex.Flow.Renderer.Backends.CANVAS);a=new Vex.Flow.Renderer(e,a);l=a.getContext();a.resize(e.clientWidth,e.clientHeight);l.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return l}function b(b,c,d){c=void 0===c?0:c;d=void 0===d?0:d;var f={"C\u266f":7,"b\u266d":5,"E\u266d":3,"c\u266f":4,d:1,c:3,"a\u266f":7,F:1,B:5,D:2,"G\u266d":6,"B\u266d":2,"g\u266f":5,e:1,"C\u266d":7,
"F\u266f":6,b:2,G:1,"a\u266d":7,E:4,a:0,C:0,"A\u266d":4,"f\u266f":3,"d\u266f":6,g:2,A:3,f:4,"D\u266d":5,"e\u266d":6};c=(0===c?e.clientWidth:c)-8;var h=0===d?e.clientHeight:d;d=Math.floor(h/160);for(var h=40+.33*(h-160*d),k=a.getData(),l=[],m=0;m<d;m++)l.push({height:160,staves:[]});for(m=0;m<d&&b<k.bars.length;m++){for(var n=[],v="",w="",z="",p=b;p<k.bars.length;p++){var x=k.bars[p],r={clef:"",key:"",time:"",verticals:x.verticals.length,size:0};x.clef!==v&&(v=r.clef=x.clef,r.size+=25);x.key!==w&&
(w=r.key=x.key,r.size+=8*f[x.key]);x.time!==z&&(z=r.time=x.time,r.size+=14);r.size+=50*r.verticals;n.push(r)}w=0;v=k.bars.length-b;for(p=b;p<k.bars.length;p++)if(w+=n[p-b].size,w>c){v=p>b?p-b:1;break}for(p=w=0;p<v;p++)w+=n[p].size;for(p=z=0;p<v;p++)g=x=p+b,r=n[p].size/w*c,l[m].staves.push({barIndex:x,left:z+4,width:r}),z+=r;b+=v}return{rows:l,staveOffsetTop:h}}function f(c){var d=a.getData();c=0==c?d.bars.length-1:c-1;for(var e=0,g=0;g<d.bars.length;g++){for(var f=e,h=b(e),k=0;k<h.rows.length;k++)for(var l=
0;l<h.rows[k].length;l++){if(c===h.rows[k][l].barIndex)return 0==k+l?f:e;e=h.rows[k][l].barIndex}e+=1}}var e=c,a=null,h=0,g=0,l=null;d();return{setPiece:function(b){a=b},setFirstBar:function(a){h=a},display:function(){d();for(var c=a.getData(),e=b(h),g=e.staveOffsetTop,f=0;f<e.rows.length;f++){for(var t="",A="",B="",y=0;y<e.rows[f].staves.length;y++){var u=c.bars[e.rows[f].staves[y].barIndex],v=new Vex.Flow.Stave(e.rows[f].staves[y].left,g,e.rows[f].staves[y].width);0==y&&v.setMeasure(e.rows[f].staves[y].barIndex+
1);u.clef!==t&&(t=u.clef,v.addClef(u.clef));u.key!==A&&(A=u.key,v.addKeySignature(VFUtility.toVFKeySignature(u.key)));u.time!==B&&(B=u.time,v.addTimeSignature(u.time));v.setContext(l).draw();for(var w=[],z={},p=0;p<u.verticals.length;p++)w.push(VFUtility.prepareStaveNote(u.key,u.verticals[p],z));u=Vex.Flow.Beam.generateBeams(w);Vex.Flow.Formatter.FormatAndDraw(l,v,w);u.forEach(function(a){a.setContext(l).draw()})}g+=e.rows[f].height}},getLastBar:function(){return g},getFirstBarInPreviousPage:f,getFirstBarInLastPage:function(){return f(0)}}}
var Note=function(){function c(b){var a={A:[0,1],"B\ud834\udd2b":[0,1],"G\ud834\udd2a":[0,1],"A\u266f":[0,2],"B\u266d":[0,2],B:[0,3],"A\ud834\udd2a":[0,3],"C\u266d":[0,3],C:[1,4],"D\ud834\udd2b":[1,4],"B\u266f":[0,4],"C\u266f":[1,5],"D\u266d":[1,5],D:[1,6],"E\ud834\udd2b":[1,6],"C\ud834\udd2a":[1,6],"D\u266f":[1,7],"E\u266d":[1,7],"F\ud834\udd2b":[1,7],E:[1,8],"F\u266d":[1,8],"D\ud834\udd2a":[1,8],F:[1,9],"G\ud834\udd2b":[1,9],"E\u266f":[1,9],"F\u266f":[1,10],"G\u266d":[1,10],G:[1,11],"A\ud834\udd2b":[1,
11],"F\ud834\udd2a":[1,11],"G\u266f":[1,12],"A\u266d":[1,12]};b=d(b);var c=b.natural+b.accidental;return a.hasOwnProperty(c)?(a=a[c],a[1]+12*(b.octave-a[0])):-1}function d(b){var a={natural:"",octave:-1,accidental:""};if(0>=b.length)return a;a.natural=b[0];a.octave=parseInt(b.substring(b.length-1,b.length));a.accidental="";a.accidentalASCII="";2<b.length&&(1==b.indexOf("\u266d")?(a.accidental="\u266d",a.accidentalASCII="b"):1==b.indexOf("\u266f")?(a.accidental="\u266f",a.accidentalASCII="#"):1==b.indexOf("\ud834\udd2b")?
(a.accidental="\ud834\udd2b",a.accidentalASCII="bb"):1==b.indexOf("\ud834\udd2a")&&(a.accidental="\ud834\udd2a",a.accidentalASCII="##"));return a}function b(b,a){var c=f[b],d="";"\u266d"==c.sharpflat&&"BEADGCF".indexOf(a)<c.amount?d="\u266d":"\u266f"==c.sharpflat&&"FCGDAEB".indexOf(a)<c.amount&&(d="\u266f");return d}var f={"D\u266d":{index:0,sharpflat:"\u266d",amount:5},"G\u266f":{index:1,sharpflat:"\u266f",amount:8},"b\u266d":{index:2,sharpflat:"\u266d",amount:5},"C\u266d":{index:3,sharpflat:"\u266d",
amount:7},e:{index:4,sharpflat:"\u266f",amount:1},"C\u266f":{index:5,sharpflat:"\u266f",amount:7},B:{index:6,sharpflat:"\u266f",amount:5},g:{index:7,sharpflat:"\u266d",amount:2},f:{index:8,sharpflat:"\u266d",amount:4},"F\u266d":{index:9,sharpflat:"\u266d",amount:8},a:{index:10,sharpflat:"\u266f",amount:0},G:{index:11,sharpflat:"\u266f",amount:1},"B\u266d":{index:12,sharpflat:"\u266d",amount:2},"e\u266f":{index:13,sharpflat:"\u266f",amount:8},"a\u266f":{index:14,sharpflat:"\u266f",amount:7},"d\u266d":{index:15,
sharpflat:"\u266d",amount:8},d:{index:16,sharpflat:"\u266d",amount:1},"F\u266f":{index:17,sharpflat:"\u266f",amount:6},"g\u266f":{index:18,sharpflat:"\u266f",amount:5},C:{index:19,sharpflat:"\u266f",amount:0},D:{index:20,sharpflat:"\u266f",amount:2},"A\u266d":{index:21,sharpflat:"\u266d",amount:4},A:{index:22,sharpflat:"\u266f",amount:3},"E\u266d":{index:23,sharpflat:"\u266d",amount:3},"f\u266f":{index:24,sharpflat:"\u266f",amount:3},c:{index:25,sharpflat:"\u266d",amount:3},b:{index:26,sharpflat:"\u266f",
amount:2},F:{index:27,sharpflat:"\u266d",amount:1},E:{index:28,sharpflat:"\u266f",amount:4},"G\u266d":{index:29,sharpflat:"\u266d",amount:6},"c\u266f":{index:30,sharpflat:"\u266f",amount:4},"e\u266d":{index:31,sharpflat:"\u266d",amount:6},"a\u266d":{index:32,sharpflat:"\u266d",amount:7},"d\u266f":{index:33,sharpflat:"\u266f",amount:6}};return{flat:"\u266d",sharp:"\u266f",flatflat:"\ud834\udd2b",sharpsharp:"\ud834\udd2a",getNoteOrder:c,getNoteFrequency:function(b){b=c(b);return 0>b?0:440*Math.pow(Math.pow(2,
1/12),b-49)},getNoteDetail:d,getDefaultAccidental:b,getDefaultAccidentalASCII:function(c,a){return b(c,a).replace("\u266f","#").replace("\u266d","b")},getFirstNoteInKey:function(b){b=b.substring(0,1);return 0<="GAB".indexOf(b)?b+"3":b+"4"}}}(),PDFConverter=function(c,d){function b(){var c=f.querySelectorAll("div.page");h+=1;h>=c.length?e(a.output("datauristring")):(a.addPage(),a.addHTML(c[h],b))}var f=c,e=d,a=null,h=0;return{convert:function(){var c=f.querySelectorAll("div.page");0>=c.length?e(null):
(a=new jsPDF("p","pt","a4"),h=0,a.addHTML(c[0],b))}}},PDFRenderer=function(c){return{render:function(d){c.innerHTML="";for(var b=-1,f=-1,e=0;8>e;e++){f+=1;b+=1;if(b>=d.getData().bars.length)break;var a;a=f;var h=document.createElement("div");h.classList.add("page");h.innerHTML='<div class="header"></div><div class="title XXX"></div><canvas class="music"></canvas><div class="footer"></div>'.replace("XXX",0===a?"":"hide");c.appendChild(h);a=h;a.querySelector("div.title").innerHTML=Locale.getTranslation(d.getData().descriptions);
a.querySelector("div.footer").innerHTML=Locale.getPrintFooter();a=new MusicViewer(a.querySelector("canvas.music"));a.setPiece(d);a.setFirstBar(b);a.display();b=a.getLastBar()}}}},Piece=function(){function c(c){function b(b){for(var a=0;a<d.bars.length;a++)if(d.bars[a].first<=b&&b<d.bars[a].first+d.bars[a].verticals.length)return d.bars[a];return null}var d=JSON.parse(c);return{getData:function(){return d},getBar:b,getNextBar:function(c){c=b(c);return b(c.first+c.verticals.length)},getTotalVerticals:function(){var b=
d.bars[d.bars.length-1];return b.first+b.verticals.length}}}return{createFromString:function(d){return new c(d)}}}();(function(){var c=function(){document.querySelector("div#printFooter").classList.remove("hidden");App.resize()},d=function(){document.querySelector("div#printFooter").classList.add("hidden");App.resize()};window.matchMedia&&window.matchMedia("print").addListener(function(b){b.matches?c():d()});window.onbeforeprint=c;window.onafterprint=d})();
var VFUtility=function(){function c(c){c=Note.getNoteDetail(c);return c.natural+c.accidentalASCII+"/"+c.octave}return{toVFKeySignature:function(c){c!==c.toUpperCase()&&(c=c.toUpperCase()+"m");return c=c.replace(Note.flat,"b").replace(Note.sharp,"#")},prepareStaveNote:function(d,b,f){for(var e,a,h,g=[],l=0;l<b.notes.length;l++)g.push(c(b.notes[l]));g=new Vex.Flow.StaveNote({keys:g,duration:b.duration});if("r"!==b.duration.substr(-1))for(l=0;l<b.notes.length;l++)a:{var k=d,m=g,n=l,q=f;h=m.keys[n];var t=
h.indexOf("/");e=h.substring(0,1);a=parseInt(h.substring(t+1));h=h.substring(1,t);t=e+a;a=!1;if(q.hasOwnProperty(t))if(q[t]==h)break a;else a=!0;q[t]=h;"bb"==h?m.addAccidental(n,new Vex.Flow.Accidental("bb")):"##"==h?m.addAccidental(n,new Vex.Flow.Accidental("##")):(e=Note.getDefaultAccidentalASCII(k,e),"#"==e?"#"==h?a&&m.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==h?m.addAccidental(n,new Vex.Flow.Accidental("b")):m.addAccidental(n,new Vex.Flow.Accidental("n")):"b"==e?"#"==h?m.addAccidental(n,
new Vex.Flow.Accidental("#")):"b"==h?a&&m.addAccidental(n,new Vex.Flow.Accidental("b")):m.addAccidental(n,new Vex.Flow.Accidental("n")):"#"==h?m.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==h?m.addAccidental(n,new Vex.Flow.Accidental("b")):a&&m.addAccidental(n,new Vex.Flow.Accidental("n")))}d=b.duration;"dd"==d.substring(d.length-2)?g.addDotToAll().addDotToAll():(b=b.duration,"d"==b.substring(b.length-1)&&g.addDotToAll());return g}}}(),ViewerPage=function(){function c(){b();for(var c=document.querySelectorAll("body > div#controls > div.control"),
d=0;d<c.length;d++){var e=c[d];0<=["pre","next","pdf"].indexOf(e.id)&&e.classList.remove("disabled")}document.querySelector("body > div#container > div#musicTitle").innerHTML=Locale.getTranslation(a.getData().descriptions);sessionStorage.lastPieceId=a.getData().id}function d(b){b=b.target.id;var c=a.getData();if("pdf"===b){LoadingIconManager.show();var d=document.querySelector("body > div#pdfRenderer");d.style.display="block";(new PDFRenderer(d)).render(a);(new PDFConverter(d,function(a){window.location=
a;d.style.display="none";LoadingIconManager.hide()})).convert(a)}else"pre"==b?window.location=window.location.pathname+"?p="+a.getData().id+"&b="+e.getFirstBarInPreviousPage(h):"next"==b&&(window.location=window.location.pathname+"?p="+a.getData().id+"&b="+(e.getLastBar()+1)%c.bars.length)}function b(){null!==a&&(e.setPiece(a),e.setFirstBar(h),e.display())}function f(){e=new MusicViewer(document.querySelector("body > div#container > div#music"));for(var a=document.querySelectorAll("body > div#controls > div.control"),
b=0;b<a.length;b++)a[b].addEventListener("click",d)}var e=null,a=null,h=0;return{initialize:function(b){f();var d=b.p||"default";h=parseInt(b.b)||0;a=MusicStorageManager.getPiece(d);null!==a?c():(LoadingIconManager.show(),AJAX.GET(App.getPiecesPath()+d+".json",function(b){a=Piece.createFromString(b);MusicStorageManager.setPiece(a);c();LoadingIconManager.hide()}))},draw:b,getPath:function(){return"/viewer.html"}}}(),ViolinSimulator=function(){function c(){if(null!=d)return!0;if("AudioContext"in window)d=
new AudioContext;else if("webkitAudioContext"in window)d=new webkitAudioContext;else return d=null,!1;b=d.createGain();b.gain.value=0;b.connect(d.destination);return!0}var d=null,b=null,f=[];return{play:function(e){c();for(var a=0;a<e.length;a++){var h=d.createOscillator();h.frequency.value=e[a];var g=h,l=Math.PI,k=new Float32Array(12),m=new Float32Array(12),n=[.49,.995,.94,.425,.48,0,.365,.04,.085,0,.09,0],l=[0,0,l/2,0,l/2,0,l/2,0,l/2,0,l/2,0];k[0]=0;m[0]=0;for(var q=1;12>q;q++)k[q]=n[q]*n[0]*Math.cos(l[q]),
m[q]=n[q]*n[0]*Math.sin(l[q]);k=d.createPeriodicWave(m,k);g.setPeriodicWave(k);h.connect(b);h.start(0);f.push(h)}b.gain.linearRampToValueAtTime(0,d.currentTime);b.gain.linearRampToValueAtTime(.5,d.currentTime+.05)},stop:function(){c();b.gain.linearRampToValueAtTime(.5,d.currentTime);b.gain.linearRampToValueAtTime(0,d.currentTime+.05);setTimeout(function(){for(var c=0;c<f.length;c++){var a=f[c];a.stop(0);a.disconnect(b)}f=[]},50)},playAndStop:function(b,a,c){}}}(),App=function(){function c(){b.draw()}
var d={},b=null;return{initialize:function(f){f=void 0===f?{}:f;Header.initialize();for(var e=window.location.pathname,a=window.location.search,a=("?"===a[0]?a.substr(1):a).split("&"),h=0;h<a.length;h++){var g=a[h].split("=");f[decodeURIComponent(g[0])]=decodeURIComponent(g[1]||"")}f.lastPage=sessionStorage.lastPage||null;d=f;0===e.indexOf("/v1"+ViewerPage.getPath())?(ViewerPage.initialize(f),b=ViewerPage):0===e.indexOf("/v1"+CatalogPage.getPath())?(CatalogPage.initialize(f),b=CatalogPage):0===e.indexOf("/v1"+
AboutPage.getPath())?(AboutPage.initialize(f),b=AboutPage):(IndexPage.initialize(f),b=IndexPage);sessionStorage.setItem("lastPage",b.getPath());document.querySelector("body > div#container > div#printFooter").innerHTML=Locale.getPrintFooter();window.addEventListener("resize",c)},getParams:function(){return d},getRootPath:function(){return"/v1"},getPagePath:function(b){return"/v1"+(void 0===b?null:b).getPath()},getPiecesPath:function(){return"/v1/pieces/"},resize:c}}();
/*
Vex Flow - A JavaScript library for rendering music notation.
Copyright (c) 2010 Mohit Muthanna Cheppudira

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


