var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(d,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");d!=Array.prototype&&d!=Object.prototype&&(d[c]=b.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var c=0;return $jscomp.iteratorPrototype(function(){return c<d.length?{done:!1,value:d[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.polyfill=function(d,c,b,f){if(c){b=$jscomp.global;d=d.split(".");for(f=0;f<d.length-1;f++){var e=d[f];e in b||(b[e]={});b=b[e]}d=d[d.length-1];f=b[d];c=c(f);c!=f&&null!=c&&$jscomp.defineProperty(b,d,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.from",function(d){return d?d:function(c,b,f){$jscomp.initSymbolIterator();b=null!=b?b:function(h){return h};var e=[],a=c[Symbol.iterator];if("function"==typeof a)for(c=a.call(c);!(a=c.next()).done;)e.push(b.call(f,a.value));else for(var a=c.length,d=0;d<a;d++)e.push(b.call(f,c[d]));return e}},"es6-impl","es3");$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();var c=d[Symbol.iterator];return c?c.call(d):$jscomp.arrayIterator(d)};
$jscomp.owns=function(d,c){return Object.prototype.hasOwnProperty.call(d,c)};
$jscomp.polyfill("WeakMap",function(d){function c(a){$jscomp.owns(a,f)||$jscomp.defineProperty(a,f,{value:{}})}function b(a){var h=Object[a];h&&(Object[a]=function(a){c(a);return h(a)})}if(function(){if(!d||!Object.seal)return!1;try{var a=Object.seal({}),h=Object.seal({}),b=new d([[a,2],[h,3]]);if(2!=b.get(a)||3!=b.get(h))return!1;b["delete"](a);b.set(h,4);return!b.has(a)&&4==b.get(h)}catch(l){return!1}}())return d;var f="$jscomp_hidden_"+Math.random().toString().substring(2);b("freeze");b("preventExtensions");
b("seal");var e=0,a=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var h;!(h=a.next()).done;)h=h.value,this.set(h[0],h[1])}};a.prototype.set=function(a,h){c(a);if(!$jscomp.owns(a,f))throw Error("WeakMap key fail: "+a);a[f][this.id_]=h;return this};a.prototype.get=function(a){return $jscomp.owns(a,f)?a[f][this.id_]:void 0};a.prototype.has=function(a){return $jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)};a.prototype["delete"]=
function(a){return $jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)?delete a[f][this.id_]:!1};return a},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(d){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new d($jscomp.makeIterator([[a,"s"]]));if("s"!=b.get(a)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var e=b.entries(),g=e.next();if(g.done||g.value[0]!=a||"s"!=g.value[1])return!1;g=e.next();return g.done||4!=g.value[0].x||"t"!=g.value[1]||!e.next().done?!1:!0}catch(n){return!1}}())return d;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var c=new WeakMap,b=function(b){this.data_={};this.head_=a();this.size=0;if(b){b=$jscomp.makeIterator(b);for(var h;!(h=b.next()).done;)h=h.value,this.set(h[0],h[1])}};b.prototype.set=function(a,b){var h=f(this,a);h.list||(h.list=this.data_[h.id]=[]);h.entry?h.entry.value=b:(h.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},h.list.push(h.entry),this.head_.previous.next=h.entry,this.head_.previous=h.entry,this.size++);return this};b.prototype["delete"]=
function(a){a=f(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};b.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=a();this.size=0};b.prototype.has=function(a){return!!f(this,a).entry};b.prototype.get=function(a){return(a=f(this,a).entry)&&a.value};b.prototype.entries=function(){return e(this,function(a){return[a.key,
a.value]})};b.prototype.keys=function(){return e(this,function(a){return a.key})};b.prototype.values=function(){return e(this,function(a){return a.value})};b.prototype.forEach=function(a,b){for(var e=this.entries(),g;!(g=e.next()).done;)g=g.value,a.call(b,g[1],g[0],this)};b.prototype[Symbol.iterator]=b.prototype.entries;var f=function(a,b){var e;e=b&&typeof b;"object"==e||"function"==e?c.has(b)?e=c.get(b):(e=""+ ++k,c.set(b,e)):e="p_"+b;var g=a.data_[e];if(g&&$jscomp.owns(a.data_,e))for(var h=0;h<
g.length;h++){var d=g[h];if(b!==b&&d.key!==d.key||b===d.key)return{id:e,list:g,index:h,entry:d}}return{id:e,list:g,index:-1,entry:void 0}},e=function(a,b){var e=a.head_;return $jscomp.iteratorPrototype(function(){if(e){for(;e.head!=a.head_;)e=e.previous;for(;e.next!=e.head;)return e=e.next,{done:!1,value:b(e)};e=null}return{done:!0,value:void 0}})},a=function(){var a={};return a.previous=a.next=a.head=a},k=0;return b},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.polyfill("Set",function(d){if(!$jscomp.ASSUME_NO_NATIVE_SET&&function(){if(!d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new d($jscomp.makeIterator([b]));if(!c.has(b)||1!=c.size||c.add(b)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var e=c.entries(),a=e.next();if(a.done||a.value[0]!=b||a.value[1]!=b)return!1;a=e.next();return a.done||a.value[0]==b||4!=a.value[0].x||a.value[1]!=a.value[0]?!1:e.next().done}catch(k){return!1}}())return d;
$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=function(b){this.map_=new Map;if(b){b=$jscomp.makeIterator(b);for(var c;!(c=b.next()).done;)this.add(c.value)}this.size=this.map_.size};c.prototype.add=function(b){this.map_.set(b,b);this.size=this.map_.size;return this};c.prototype["delete"]=function(b){b=this.map_["delete"](b);this.size=this.map_.size;return b};c.prototype.clear=function(){this.map_.clear();this.size=0};c.prototype.has=function(b){return this.map_.has(b)};c.prototype.entries=
function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(b,c){var e=this;this.map_.forEach(function(a){return b.call(c,a,a,e)})};return c},"es6-impl","es3");$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(d,c){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var b=0,f={next:function(){if(b<d.length){var e=b++;return{value:c(e,d[e]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6-impl","es3");
var AboutPage=function(){return{initialize:function(d){document.querySelector("body > div#container > div#controls > div.control#ok").addEventListener("click",function(){Header.handlePlay()})},draw:function(){},getPath:function(){return"/about.html"}}}(),AJAX=function(){return{GET:function(d,c,b){c=void 0===c?null:c;b=void 0===b?null:b;var f=new XMLHttpRequest;f.onreadystatechange=function(){4==this.readyState&&(200==this.status?null!==c&&c(this.responseText):null!==b&&b(this.status))};f.open("GET",
d,!0);f.send()}}}(),CatalogPage=function(){function d(){AJAX.GET(App.getPiecesPath()+"indexes.json",function(b){b=JSON.parse(b);var c=b.scales;1==a.length?b.hasOwnProperty(a[0])&&(c=b[a[0]]):1<a.length&&"scales"==a[0]&&b.scales.hasOwnProperty(a[1])&&(c=b.scales[a[1]]);e={query:a,tiles:[]};b=[];for(g in c)c.hasOwnProperty(g)&&"_"!==g.substring(0,1)&&b.push(g);b.sort(function(a,b){var e=Locale.getTranslation(c[a]._desc,"en"),g=Locale.getTranslation(c[b]._desc,"en");return e<g?-1:e>g?1:0});for(var d=
0;d<b.length;d++){var g=b[d],h=c[g];if("_"!==g.substring(0,1)){var g={id:g,description:h._desc},p=0;for(keyInNextLevel in h)h.hasOwnProperty(keyInNextLevel)&&"_"!==keyInNextLevel.substring(0,1)&&(p+=1);0>=p?g.type="piece":(g.type="folder",g.total=p);e.tiles.push(g)}}f()})}function c(a){a=a.target.getAttribute("data");window.location=App.getPagePath(CatalogPage)+"?q="+encodeURIComponent("scales,"+a)}function b(a){window.location=App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a.target.getAttribute("data"))}
function f(){for(var a=0;a<e.tiles.length;a++){var d=e.tiles[a];if("folder"==d.type){var f=document.createElement("div");f.classList.add("tile");f.classList.add("folder");f.setAttribute("data",d.id);f.innerHTML=Locale.getTranslation(d.description);f.addEventListener("click",c);k.append(f)}else f=document.createElement("div"),f.classList.add("tile"),f.classList.add("piece"),f.setAttribute("data",d.id),f.innerHTML=Locale.getTranslation(d.description),f.addEventListener("click",b),k.append(f),d.hasOwnProperty("data")}}
var e={},a="",k=null;return{initialize:function(b){k=document.querySelector("div#tiles");window.hasOwnProperty("catalogSnapshot")&&(e=window.catalogSnapshot);parseInt(b.p);a=Array.from(new Set((b.q||"").split(",")));d()},draw:function(){},getPath:function(){return"/catalog.html"}}}(),Header=function(){function d(){var a;a=App.getParams();var b="default";a.hasOwnProperty("p")?b=a.p:"lastPieceId"in sessionStorage&&(b=sessionStorage.lastPieceId);a=b;window.location=App.getPagePath(IndexPage)+"?p="+encodeURIComponent(a)+
"&v=0"}function c(){window.location=App.getPagePath(CatalogPage)}function b(){window.location=App.getPagePath(AboutPage)}var f=null,e=null;return{initialize:function(){f=document.querySelector("div#header > div#controls > div.control#play");e=document.querySelector("div#header > div#controls > div.control#open");f.addEventListener("click",d);e.addEventListener("click",c);document.querySelector("div#header > div#title  > div#text").addEventListener("click",b);document.querySelector("div#header > div#title  > div#icon").addEventListener("click",
b);document.querySelector("div#header > div#title  > div#text").innerHTML=Locale.getApplicationTitle()},handlePlay:d,highlight:function(a){f.classList.remove("highlighted");e.classList.remove("highlighted");a===IndexPage?f.classList.add("highlighted"):a===CatalogPage&&e.classList.add("highlighted")}}}(),IndexPage=function(){function d(a){var e=a.clientX,c=a.clientY;"ontouchstart"in window&&(e=a.touches[0].clientX,c=a.touches[0].clientY);b(e,c)}function c(a){a=null;for(var b=document.querySelectorAll("body > div#container > div#notes > div.note"),
e=0;e<b.length;e++)if(b[e].classList.contains("selected")){a=b[e];break}if(null!==a){a.classList.remove("selected");ViolinSimulator.stop();var b=l.getBar(g),e=g-b.first,c=b.verticals[e],c=Array.from(c.notes.keys());"playAllNotesAndMoveNext"!==a.id?(c=[parseInt(a.getAttribute("value"))],m.changeNotesColor(e,c,"green"),m.changeNotesSize(e,c,1)):(m.changeNotesColor(e,c,"black"),m.changeNotesSize(e,c,1),g+=1,a=!1,g>=b.first+b.verticals.length&&(a=!0),g>=l.getTotalVerticals()&&(g=0),a?window.location=
window.location.pathname+"?p="+l.getData().id+"&v="+g:(e+=1,c=b.verticals[e],c=Array.from(c.notes.keys()),m.changeNotesColor(e,c,"green"),m.changeNotesSize(e,c,1),f()))}}function b(a,b){for(var e=null,c=document.querySelectorAll("body > div#container > div#notes > div.note"),d=0;d<c.length;d++){var f=c[d].getBoundingClientRect();if(a>=f.left&&a<=f.right&&b>=f.top&&b<=f.bottom){e=c[d];break}}if(null!==e)if(e.classList.contains("note")||(e=e.parentNode),e.classList.add("selected"),null===l)n={x:a,y:b};
else{var d=l.getBar(g),c=g-d.first,f=d.verticals[c],h=[],v=[];if("playAllNotesAndMoveNext"===e.id)for(d=0;d<f.notes.length;d++)h.push(Note.getNoteFrequency(f.notes[d])),v.push(d);else e=parseInt(e.getAttribute("value")),h.push(Note.getNoteFrequency(f.notes[e])),v.push(e);"r"===f.duration.substr(-1)?ViolinSimulator.play([0]):ViolinSimulator.play(h);m.changeNotesColor(c,v,"red");m.changeNotesSize(c,v,1.3)}}function f(){for(var a=document.querySelectorAll("body > div#container > div#notes > div.note"),
b=0;b<a.length;b++)"playAllNotesAndMoveNext"!==a[b].id&&a[b].parentNode.removeChild(a[b]);var a=document.querySelector("body > div#container > div#notes"),b=l.getBar(g),e=b.verticals[g-b.first];if("r"!==e.duration.substr(-1))for(b=e.notes.length-1;0<=b;b--){var c=document.createElement("div");c.classList.add("note");c.setAttribute("value",""+b);var d=c,f;f=Note.getNoteDetail(e.notes[b]);var h=""===f.accidental?"":"withAccidental";f=('<div class="natural YYY">'+f.natural+'</div><div class="accidental XXX"></div><div class="octave ZZZ">'+
f.octave+"</div>").replace("XXX",""===f.accidental?"hidden":f.accidental).replace("YYY",h).replace("ZZZ",h);d.innerHTML=f;a.appendChild(c)}}function e(){null!==l&&(m.setPiece(l),m.setFocus(g),m.display(),f())}function a(){g>=l.getTotalVerticals()&&(g=0);e();var a=l.getBar(g),c=g-a.first;m.changeNotesColor(c,Array.from(a.verticals[c].notes.keys()),"green");null!==n&&b(n.x,n.y);l.getData();document.querySelector("body > div#container > div#musicTitle").innerHTML=Locale.getTranslation(l.getData().descriptions);
sessionStorage.lastPieceId=l.getData().id;a=l.getNextBar(g);c=0;null!==a&&(c=a.first);AJAX.GET(window.location.pathname+"?p="+l.getData().id+"&v="+c);p.enableControls()}function k(){var a="mousedown",b="mouseup";"ontouchstart"in window&&(a="touchstart",b="touchend");window.addEventListener(a,d);window.addEventListener(b,c);m=new MusicPlayer(document.querySelector("body > div#container > div#music"));p.initialize()}function h(){return"/index.html"}var m=null,l=null,g=0,n=null,p=function(){function a(a){a=
a.target.id;l.getData();if("pdf"===a){LoadingIconManager.show();var b=document.querySelector("body > div#pdfRenderer");b.style.display="block";(new PDFRenderer(b)).render(l);(new PDFConverter(b,function(a){window.location=a;b.style.display="none";LoadingIconManager.hide()})).convert(l)}else if("pre"==a){var e=l.getPreBar(g);a=l.getTotalVerticals()-1;null!==e&&(a=e.first);window.location=window.location.pathname+"?p="+l.getData().id+"&v="+a}else"next"==a&&(e=l.getNextBar(g),a=0,null!==e&&(a=e.first),
window.location=window.location.pathname+"?p="+l.getData().id+"&v="+a)}return{initialize:function(){for(var b=document.querySelectorAll("body > div#controls > div.control"),e=0;e<b.length;e++)b[e].addEventListener("click",a)},enableControls:function(){for(var a=document.querySelectorAll("body > div#controls > div.control"),b=0;b<a.length;b++)a[b].classList.remove("disabled")}}}();return{initialize:function(b){k();var e=b.p||"default";g=parseInt(b.v)||0;n="unhandledEvent"in b&&b.lastPage===h()?b.unhandledEvent:
null;l=MusicStorageManager.getPiece(e);null!==l?a():(LoadingIconManager.show(),AJAX.GET(App.getPiecesPath()+e+".json",function(b){l=Piece.createFromString(b);MusicStorageManager.setPiece(l);a();LoadingIconManager.hide()},function(a){alert(Locale.getPieceLoadingFailureNotice(e));window.location=App.getPagePath(CatalogPage)}))},draw:e,getPath:h}}(),LoadingIconManager=function(){var d=0,c=document.querySelector("body > div#loading");return{show:function(){setTimeout(function(){100<(new Date).getTime()-
d&&c.classList.remove("hidden")},100)},hide:function(){c.classList.add("hidden");d=(new Date).getTime()}}}(),Locale=function(){function d(){if("language"in localStorage&&0<=b.indexOf(localStorage.language))f=localStorage.language;else{var a=navigator.languages&&navigator.languages[0]||navigator.language||navigator.userLanguage,a=a.toLowerCase();f=0<=b.indexOf(a)?a:"en"}}function c(a,b){b=void 0===b?"":b;""===b&&(b=f);return b in a?a[b]:a.en}var b=["en","zh-cn"],f="en",e={en:"Check more from $1","zh-cn":"\u66f4\u591a\u8d44\u6e90\u5728 $1"},
a={en:"Cannot load piece $piece from $address. Please choose a new one.","zh-cn":"\u65e0\u6cd5\u4ece$address\u4e0b\u8f7d\u66f2\u76ee$piece\u3002\u8bf7\u9009\u62e9\u65b0\u66f2\u76ee\u3002"},k={en:"ViolinEscort","zh-cn":"\u5c0f\u63d0\u7434\u4f34\u4fa3"};d();return{checkLanguage:d,getApplicationTitle:function(){return c(k)},getPrintFooter:function(){return f in e?e[f].replace("$1",window.location.hostname+App.getRootPath()):e.en.replace("$1",window.location.hostname+App.getRootPath())},getTranslation:c,
getPieceLoadingFailureNotice:function(b){return f in a?a[f].replace("$piece",b).replace("$address",window.location.hostname+App.getRootPath()):a.en.replace("$piece",b).replace("$address",window.location.hostname+App.getRootPath())}}}();
function MusicPlayer(d){function c(a){for(var b=a.first,e=[],c=0;c<a.verticals.length;c++){for(var d=[],g=0;g<a.verticals[c].notes.length;g++)d.push({color:"black",size:"1.0"});e.push(d)}return{isOnBar:function(a){return b===a.first},changeNotesSize:function(a,b,c){for(var d=0;d<b.length;d++)e[a][b[d]].size=c},changeNotesColor:function(a,b,c){for(var d=0;d<b.length;d++)e[a][b[d]].color=c},drawAllOrnaments:function(){for(var a=0;a<e.length;a++)for(var b=0;b<e[a].length;b++){if("1.0"!==e[a][b].size){var c=
f(a,[b]);c[0].style.transform="scale("+e[a][b].size+")";c[0].style.transformOrigin="50% 50%"}"black"!==e[a][b].color&&(c=f(a,[b]),c[0].setAttribute("fill",e[a][b].color))}}}}function b(){a.innerHTML="";var b=new Vex.Flow.Renderer(a,Vex.Flow.Renderer.Backends.SVG);context=b.getContext();b.resize(a.clientWidth,a.clientHeight);context.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return context}function f(a,b){for(var e=document.querySelectorAll("#vf-"+h[a].attrs.id+" g.vf-notehead path"),
c=[],d=0;d<b.length;d++)c.push(e[b[d]]);return c}function e(a){var b=k.getBar(a);return a-b.first}var a=d,k=null,h=[],m=0,l=null;return{setPiece:function(a){k=a;m=0},setFocus:function(a){m=a},display:function(){var a=b(),e=new Vex.Flow.Stave(4,60,a.width-8),d=k.getBar(m);e.addClef("treble").addTimeSignature(d.time).addKeySignature(VFUtility.toVFKeySignature(d.key));e.setMeasure(k.getData().bars.indexOf(d)+1);e.setContext(a).draw();h=[];for(var f={},v=0;v<d.verticals.length;v++)h.push(VFUtility.prepareStaveNote(d.key,
d.verticals[v],f));f=Vex.Flow.Beam.generateBeams(h);Vex.Flow.Formatter.FormatAndDraw(a,e,h);f.forEach(function(b){b.setContext(a).draw()});null!==l&&l.isOnBar(d)?l.drawAllOrnaments():l=new c(d)},changeNotesSize:function(a,b,c){c=void 0===c?"1.0":c;a=e(a);for(var d=f(a,b),g=0;g<d.length;g++)d[g].style.transform="scale("+c+")",d[g].style.transformOrigin="50% 50%";l.changeNotesSize(a,b,c)},changeNotesColor:function(a,b,c){c=void 0===c?"black":c;a=e(a);for(var d=f(a,b),g=0;g<d.length;g++)d[g].setAttribute("fill",
c);l.changeNotesColor(a,b,c)}}}var MusicStorageManager=function(){return{getPiece:function(d){d=localStorage.getItem("_piece_"+d);return null===d?null:Piece.createFromString(d)},setPiece:function(d){localStorage.setItem("_piece_"+d.id,JSON.stringify(d))}}}();
function MusicViewer(d){function c(){e.innerHTML="";var a=Vex.Flow.Renderer.Backends.SVG;"CANVAS"===e.tagName.toUpperCase()&&(a=Vex.Flow.Renderer.Backends.CANVAS);a=new Vex.Flow.Renderer(e,a);m=a.getContext();a.resize(e.clientWidth,e.clientHeight);m.setFont("Arial",10,"").setBackgroundFillStyle("#ffffff");return m}function b(b,c,d){c=void 0===c?0:c;d=void 0===d?0:d;var f={"C\u266f":7,"b\u266d":5,"E\u266d":3,"c\u266f":4,d:1,c:3,"a\u266f":7,F:1,B:5,D:2,"G\u266d":6,"B\u266d":2,"g\u266f":5,e:1,"C\u266d":7,
"F\u266f":6,b:2,G:1,"a\u266d":7,E:4,a:0,C:0,"A\u266d":4,"f\u266f":3,"d\u266f":6,g:2,A:3,f:4,"D\u266d":5,"e\u266d":6};c=(0===c?e.clientWidth:c)-8;var g=0===d?e.clientHeight:d;d=Math.floor(g/160);for(var g=40+.33*(g-160*d),k=a.getData(),l=[],m=0;m<d;m++)l.push({height:160,staves:[]});for(m=0;m<d&&b<k.bars.length;m++){for(var n=[],p="",u="",y="",q=b;q<k.bars.length;q++){var w=k.bars[q],r={clef:"",key:"",time:"",verticals:w.verticals.length,size:0};w.clef!==p&&(p=r.clef=w.clef,r.size+=25);w.key!==u&&
(u=r.key=w.key,r.size+=8*f[w.key]);w.time!==y&&(y=r.time=w.time,r.size+=14);r.size+=50*r.verticals;n.push(r)}u=0;p=k.bars.length-b;for(q=b;q<k.bars.length;q++)if(u+=n[q-b].size,u>c){p=q>b?q-b:1;break}for(q=u=0;q<p;q++)u+=n[q].size;for(q=y=0;q<p;q++)h=w=q+b,r=n[q].size/u*c,l[m].staves.push({barIndex:w,left:y+4,width:r}),y+=r;b+=p}return{rows:l,staveOffsetTop:g}}function f(e){var c=a.getData();e=0==e?c.bars.length-1:e-1;for(var d=0,f=0;f<c.bars.length;f++){for(var g=d,h=b(d),k=0;k<h.rows.length;k++)for(var l=
0;l<h.rows[k].length;l++){if(e===h.rows[k][l].barIndex)return 0==k+l?g:d;d=h.rows[k][l].barIndex}d+=1}}var e=d,a=null,k=0,h=0,m=null,l=null;c();return{setPiece:function(b){a=b},setFirstBar:function(a){k=a},display:function(){c();var e=a.getData(),d=b(k),f=d.staveOffsetTop;l=d;for(var h=0;h<d.rows.length;h++){for(var v="",B="",C="",x=0;x<d.rows[h].staves.length;x++){var t=e.bars[d.rows[h].staves[x].barIndex],A=new Vex.Flow.Stave(d.rows[h].staves[x].left,f,d.rows[h].staves[x].width);0==x&&A.setMeasure(d.rows[h].staves[x].barIndex+
1);t.clef!==v&&(v=t.clef,A.addClef(t.clef));t.key!==B&&(B=t.key,A.addKeySignature(VFUtility.toVFKeySignature(t.key)));t.time!==C&&(C=t.time,A.addTimeSignature(t.time));A.setContext(m).draw();for(var u=[],y={},q=0;q<t.verticals.length;q++)u.push(VFUtility.prepareStaveNote(t.key,t.verticals[q],y));t=Vex.Flow.Beam.generateBeams(u);Vex.Flow.Formatter.FormatAndDraw(m,A,u);t.forEach(function(a){a.setContext(m).draw()})}f+=d.rows[h].height}},getLastBar:function(){return h},getCurrentLayout:function(){return l},
getFirstBarInPreviousPage:f,getFirstBarInLastPage:function(){return f(0)}}}
var Note=function(){function d(b){var a={A:[0,1],"B\ud834\udd2b":[0,1],"G\ud834\udd2a":[0,1],"A\u266f":[0,2],"B\u266d":[0,2],B:[0,3],"A\ud834\udd2a":[0,3],"C\u266d":[1,3],C:[1,4],"D\ud834\udd2b":[1,4],"B\u266f":[0,4],"C\u266f":[1,5],"D\u266d":[1,5],D:[1,6],"E\ud834\udd2b":[1,6],"C\ud834\udd2a":[1,6],"D\u266f":[1,7],"E\u266d":[1,7],"F\ud834\udd2b":[1,7],E:[1,8],"F\u266d":[1,8],"D\ud834\udd2a":[1,8],F:[1,9],"G\ud834\udd2b":[1,9],"E\u266f":[1,9],"F\u266f":[1,10],"G\u266d":[1,10],G:[1,11],"A\ud834\udd2b":[1,
11],"F\ud834\udd2a":[1,11],"G\u266f":[1,12],"A\u266d":[1,12]};b=c(b);var e=b.natural+b.accidental;return a.hasOwnProperty(e)?(a=a[e],a[1]+12*(b.octave-a[0])):-1}function c(b){var a={natural:"",octave:-1,accidental:""};if(0>=b.length)return a;a.natural=b[0];a.octave=parseInt(b.substring(b.length-1,b.length));a.accidental="";a.accidentalASCII="";2<b.length&&(1==b.indexOf("\u266d")?(a.accidental="\u266d",a.accidentalASCII="b"):1==b.indexOf("\u266f")?(a.accidental="\u266f",a.accidentalASCII="#"):1==b.indexOf("\ud834\udd2b")?
(a.accidental="\ud834\udd2b",a.accidentalASCII="bb"):1==b.indexOf("\ud834\udd2a")&&(a.accidental="\ud834\udd2a",a.accidentalASCII="##"));return a}function b(b,a){var c=f[b],e="";"\u266d"==c.sharpflat&&"BEADGCF".indexOf(a)<c.amount?e="\u266d":"\u266f"==c.sharpflat&&"FCGDAEB".indexOf(a)<c.amount&&(e="\u266f");return e}var f={"D\u266d":{index:0,sharpflat:"\u266d",amount:5},"G\u266f":{index:1,sharpflat:"\u266f",amount:8},"b\u266d":{index:2,sharpflat:"\u266d",amount:5},"C\u266d":{index:3,sharpflat:"\u266d",
amount:7},e:{index:4,sharpflat:"\u266f",amount:1},"C\u266f":{index:5,sharpflat:"\u266f",amount:7},B:{index:6,sharpflat:"\u266f",amount:5},g:{index:7,sharpflat:"\u266d",amount:2},f:{index:8,sharpflat:"\u266d",amount:4},"F\u266d":{index:9,sharpflat:"\u266d",amount:8},a:{index:10,sharpflat:"\u266f",amount:0},G:{index:11,sharpflat:"\u266f",amount:1},"B\u266d":{index:12,sharpflat:"\u266d",amount:2},"e\u266f":{index:13,sharpflat:"\u266f",amount:8},"a\u266f":{index:14,sharpflat:"\u266f",amount:7},"d\u266d":{index:15,
sharpflat:"\u266d",amount:8},d:{index:16,sharpflat:"\u266d",amount:1},"F\u266f":{index:17,sharpflat:"\u266f",amount:6},"g\u266f":{index:18,sharpflat:"\u266f",amount:5},C:{index:19,sharpflat:"\u266f",amount:0},D:{index:20,sharpflat:"\u266f",amount:2},"A\u266d":{index:21,sharpflat:"\u266d",amount:4},A:{index:22,sharpflat:"\u266f",amount:3},"E\u266d":{index:23,sharpflat:"\u266d",amount:3},"f\u266f":{index:24,sharpflat:"\u266f",amount:3},c:{index:25,sharpflat:"\u266d",amount:3},b:{index:26,sharpflat:"\u266f",
amount:2},F:{index:27,sharpflat:"\u266d",amount:1},E:{index:28,sharpflat:"\u266f",amount:4},"G\u266d":{index:29,sharpflat:"\u266d",amount:6},"c\u266f":{index:30,sharpflat:"\u266f",amount:4},"e\u266d":{index:31,sharpflat:"\u266d",amount:6},"a\u266d":{index:32,sharpflat:"\u266d",amount:7},"d\u266f":{index:33,sharpflat:"\u266f",amount:6}};return{flat:"\u266d",sharp:"\u266f",flatflat:"\ud834\udd2b",sharpsharp:"\ud834\udd2a",getNoteOrder:d,getNoteFrequency:function(b){b=d(b);return 0>b?0:440*Math.pow(Math.pow(2,
1/12),b-49)},getNoteDetail:c,getDefaultAccidental:b,getDefaultAccidentalASCII:function(c,a){return b(c,a).replace("\u266f","#").replace("\u266d","b")},getFirstNoteInKey:function(b){b=b.substring(0,1);return 0<="GAB".indexOf(b)?b+"3":b+"4"}}}(),PDFConverter=function(d,c){function b(){var c=f.querySelectorAll("div.page");k+=1;k>=c.length?e(a.output("datauristring")):(a.addPage(),a.addHTML(c[k],b))}var f=d,e=c,a=null,k=0;return{convert:function(){var c=f.querySelectorAll("div.page");0>=c.length?e(null):
(a=new jsPDF("p","pt","a4"),k=0,a.addHTML(c[0],b))}}},PDFRenderer=function(d){return{render:function(c){d.innerHTML="";for(var b=-1,f=-1,e=0;8>e;e++){f+=1;b+=1;if(b>=c.getData().bars.length)break;var a;a=f;var k=document.createElement("div");k.classList.add("page");k.innerHTML='<div class="header"></div><div class="title XXX"></div><canvas class="music"></canvas><div class="footer"></div>'.replace("XXX",0===a?"":"hide");d.appendChild(k);a=k;a.querySelector("div.title").innerHTML=Locale.getTranslation(c.getData().descriptions);
a.querySelector("div.footer").innerHTML=Locale.getPrintFooter();a=new MusicViewer(a.querySelector("canvas.music"));a.setPiece(c);a.setFirstBar(b);a.display();b=a.getLastBar()}}}},Piece=function(){function d(c){function b(b){for(var a=0;a<d.bars.length;a++)if(d.bars[a].first<=b&&b<d.bars[a].first+d.bars[a].verticals.length)return d.bars[a];return null}var d=JSON.parse(c);return{getData:function(){return d},getBar:b,getPreBar:function(c){c=b(c);return null===c?null:b(c.first-1)},getNextBar:function(c){c=
b(c);return null===c?null:b(c.first+c.verticals.length)},getTotalVerticals:function(){var b=d.bars[d.bars.length-1];return b.first+b.verticals.length}}}return{createFromString:function(c){return new d(c)}}}(),VFUtility=function(){function d(c){c=Note.getNoteDetail(c);return c.natural+c.accidentalASCII+"/"+c.octave}return{toVFKeySignature:function(c){c!==c.toUpperCase()&&(c=c.toUpperCase()+"m");return c=c.replace(Note.flat,"b").replace(Note.sharp,"#")},prepareStaveNote:function(c,b,f){for(var e,a,
k,h=[],m=0;m<b.notes.length;m++)h.push(d(b.notes[m]));h=new Vex.Flow.StaveNote({keys:h,duration:b.duration});if("r"!==b.duration.substr(-1))for(m=0;m<b.notes.length;m++)a:{var l=c,g=h,n=m,p=f;k=g.keys[n];var z=k.indexOf("/");e=k.substring(0,1);a=parseInt(k.substring(z+1));k=k.substring(1,z);z=e+a;a=!1;if(p.hasOwnProperty(z))if(p[z]==k)break a;else a=!0;p[z]=k;"bb"==k?g.addAccidental(n,new Vex.Flow.Accidental("bb")):"##"==k?g.addAccidental(n,new Vex.Flow.Accidental("##")):(e=Note.getDefaultAccidentalASCII(l,
e),"#"==e?"#"==k?a&&g.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==k?g.addAccidental(n,new Vex.Flow.Accidental("b")):g.addAccidental(n,new Vex.Flow.Accidental("n")):"b"==e?"#"==k?g.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==k?a&&g.addAccidental(n,new Vex.Flow.Accidental("b")):g.addAccidental(n,new Vex.Flow.Accidental("n")):"#"==k?g.addAccidental(n,new Vex.Flow.Accidental("#")):"b"==k?g.addAccidental(n,new Vex.Flow.Accidental("b")):a&&g.addAccidental(n,new Vex.Flow.Accidental("n")))}c=
b.duration;"dd"==c.substring(c.length-2)?h.addDotToAll().addDotToAll():(b=b.duration,"d"==b.substring(b.length-1)&&h.addDotToAll());return h}}}(),ViolinSimulator=function(){function d(){if(null!=c)return!0;if("AudioContext"in window)c=new AudioContext;else if("webkitAudioContext"in window)c=new webkitAudioContext;else return c=null,!1;b=c.createGain();b.gain.value=0;b.connect(c.destination);return!0}var c=null,b=null,f=[];return{play:function(e){d();for(var a=0;a<e.length;a++){var k=c.createOscillator();
k.frequency.value=e[a];var h=k,m=Math.PI,l=new Float32Array(12),g=new Float32Array(12),n=[.49,.995,.94,.425,.48,0,.365,.04,.085,0,.09,0],m=[0,0,m/2,0,m/2,0,m/2,0,m/2,0,m/2,0];l[0]=0;g[0]=0;for(var p=1;12>p;p++)l[p]=n[p]*n[0]*Math.cos(m[p]),g[p]=n[p]*n[0]*Math.sin(m[p]);l=c.createPeriodicWave(g,l);h.setPeriodicWave(l);k.connect(b);k.start(0);f.push(k)}b.gain.linearRampToValueAtTime(0,c.currentTime);b.gain.linearRampToValueAtTime(.5,c.currentTime+.05)},stop:function(){d();b.gain.linearRampToValueAtTime(.5,
c.currentTime);b.gain.linearRampToValueAtTime(0,c.currentTime+.05);setTimeout(function(){for(var c=0;c<f.length;c++){var a=f[c];a.stop(0);a.disconnect(b)}f=[]},50)},playAndStop:function(b,a,c){}}}(),App=function(){function d(){b.draw()}var c={},b=null;return{initialize:function(f){f=void 0===f?{}:f;Header.initialize();for(var e=window.location.pathname,a=window.location.search,a=("?"===a[0]?a.substr(1):a).split("&"),k=0;k<a.length;k++){var h=a[k].split("=");f[decodeURIComponent(h[0])]=decodeURIComponent(h[1]||
"")}f.lastPage=sessionStorage.lastPage||null;c=f;b=0===e.indexOf("/v1"+CatalogPage.getPath())?CatalogPage:0===e.indexOf("/v1"+AboutPage.getPath())?AboutPage:IndexPage;Header.highlight(b);b.initialize(f);sessionStorage.setItem("lastPage",b.getPath());window.addEventListener("resize",d)},getParams:function(){return c},getRootPath:function(){return"/v1"},getPagePath:function(b){return"/v1"+(void 0===b?null:b).getPath()},getPiecesPath:function(){return"/v1/pieces/"},resize:d}}();
/*
Vex Flow - A JavaScript library for rendering music notation.
Copyright (c) 2010 Mohit Muthanna Cheppudira

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


