var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,m,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[m]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var m=0;return $jscomp.iteratorPrototype(function(){return m<a.length?{done:!1,value:a[m++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.polyfill=function(a,m,f,b){if(m){f=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var e=a[b];e in f||(f[e]={});f=f[e]}a=a[a.length-1];b=f[a];m=m(b);m!=b&&null!=m&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:m})}};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,f,b){$jscomp.initSymbolIterator();f=null!=f?f:function(b){return b};var e=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)e.push(f.call(b,g.value));else for(var g=a.length,n=0;n<g;n++)e.push(f.call(b,a[n]));return e}},"es6-impl","es3");var QRCode;
!function(){function a(c){this.mode=n.MODE_8BIT_BYTE;this.data=c;this.parsedData=[];c=[];for(var l=0,k=this.data.length;k>l;l++){var d=this.data.charCodeAt(l);65536<d?(c[0]=240|(1835008&d)>>>18,c[1]=128|(258048&d)>>>12,c[2]=128|(4032&d)>>>6,c[3]=128|63&d):2048<d?(c[0]=224|(61440&d)>>>12,c[1]=128|(4032&d)>>>6,c[2]=128|63&d):128<d?(c[0]=192|(1984&d)>>>6,c[1]=128|63&d):c[0]=d;this.parsedData=this.parsedData.concat(c)}this.parsedData.length!=this.data.length&&(this.parsedData.unshift(191),this.parsedData.unshift(187),
this.parsedData.unshift(239))}function m(c,l){this.typeNumber=c;this.errorCorrectLevel=l;this.modules=null;this.moduleCount=0;this.dataCache=null;this.dataList=[]}function f(c,l){if(void 0==c.length)throw Error(c.length+"/"+l);for(var k=0;k<c.length&&0==c[k];)k++;this.num=Array(c.length-k+l);for(var d=0;d<c.length-k;d++)this.num[d]=c[d+k]}function b(c,l){this.totalCount=c;this.dataCount=l}function e(){this.buffer=[];this.length=0}function g(){var c=!1,l=navigator.userAgent;return/android/i.test(l)&&
(c=!0,aMat=l.toString().match(/android ([0-9]\.[0-9])/i),aMat&&aMat[1]&&(c=parseFloat(aMat[1]))),c}a.prototype={getLength:function(){return this.parsedData.length},write:function(c){for(var l=0,k=this.parsedData.length;k>l;l++)c.put(this.parsedData[l],8)}};m.prototype={addData:function(c){c=new a(c);this.dataList.push(c);this.dataCache=null},isDark:function(c,l){if(0>c||this.moduleCount<=c||0>l||this.moduleCount<=l)throw Error(c+","+l);return this.modules[c][l]},getModuleCount:function(){return this.moduleCount},
make:function(){this.makeImpl(!1,this.getBestMaskPattern())},makeImpl:function(c,l){this.moduleCount=4*this.typeNumber+17;this.modules=Array(this.moduleCount);for(var k=0;k<this.moduleCount;k++){this.modules[k]=Array(this.moduleCount);for(var d=0;d<this.moduleCount;d++)this.modules[k][d]=null}this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(c,
l);7<=this.typeNumber&&this.setupTypeNumber(c);null==this.dataCache&&(this.dataCache=m.createData(this.typeNumber,this.errorCorrectLevel,this.dataList));this.mapData(this.dataCache,l)},setupPositionProbePattern:function(c,l){for(var k=-1;7>=k;k++)if(!(-1>=c+k||this.moduleCount<=c+k))for(var d=-1;7>=d;d++)-1>=l+d||this.moduleCount<=l+d||(this.modules[c+k][l+d]=0<=k&&6>=k&&(0==d||6==d)||0<=d&&6>=d&&(0==k||6==k)||2<=k&&4>=k&&2<=d&&4>=d?!0:!1)},getBestMaskPattern:function(){for(var c=0,l=0,k=0;8>k;k++){this.makeImpl(!0,
k);var d=q.getLostPoint(this);(0==k||c>d)&&(c=d,l=k)}return l},createMovieClip:function(c,l,k){c=c.createEmptyMovieClip(l,k);this.make();for(l=0;l<this.modules.length;l++){k=1*l;for(var d=0;d<this.modules[l].length;d++){var b=1*d;this.modules[l][d]&&(c.beginFill(0,100),c.moveTo(b,k),c.lineTo(b+1,k),c.lineTo(b+1,k+1),c.lineTo(b,k+1),c.endFill())}}return c},setupTimingPattern:function(){for(var c=8;c<this.moduleCount-8;c++)null==this.modules[c][6]&&(this.modules[c][6]=0==c%2);for(c=8;c<this.moduleCount-
8;c++)null==this.modules[6][c]&&(this.modules[6][c]=0==c%2)},setupPositionAdjustPattern:function(){for(var c=q.getPatternPosition(this.typeNumber),l=0;l<c.length;l++)for(var k=0;k<c.length;k++){var d=c[l],b=c[k];if(null==this.modules[d][b])for(var e=-2;2>=e;e++)for(var a=-2;2>=a;a++)this.modules[d+e][b+a]=-2==e||2==e||-2==a||2==a||0==e&&0==a?!0:!1}},setupTypeNumber:function(c){for(var l=q.getBCHTypeNumber(this.typeNumber),k=0;18>k;k++){var d=!c&&1==(1&l>>k);this.modules[Math.floor(k/3)][k%3+this.moduleCount-
8-3]=d}for(k=0;18>k;k++)d=!c&&1==(1&l>>k),this.modules[k%3+this.moduleCount-8-3][Math.floor(k/3)]=d},setupTypeInfo:function(c,l){for(var k=q.getBCHTypeInfo(this.errorCorrectLevel<<3|l),d=0;15>d;d++){var b=!c&&1==(1&k>>d);6>d?this.modules[d][8]=b:8>d?this.modules[d+1][8]=b:this.modules[this.moduleCount-15+d][8]=b}for(d=0;15>d;d++)b=!c&&1==(1&k>>d),8>d?this.modules[8][this.moduleCount-d-1]=b:9>d?this.modules[8][15-d-1+1]=b:this.modules[8][15-d-1]=b;this.modules[this.moduleCount-8][8]=!c},mapData:function(c,
l){for(var k=-1,d=this.moduleCount-1,b=7,e=0,a=this.moduleCount-1;0<a;a-=2)for(6==a&&a--;;){for(var g=0;2>g;g++)if(null==this.modules[d][a-g]){var f=!1;e<c.length&&(f=1==(1&c[e]>>>b));q.getMask(l,d,a-g)&&(f=!f);this.modules[d][a-g]=f;b--; -1==b&&(e++,b=7)}if(d+=k,0>d||this.moduleCount<=d){d-=k;k=-k;break}}}};m.PAD0=236;m.PAD1=17;m.createData=function(c,l,k){l=b.getRSBlocks(c,l);for(var d=new e,a=0;a<k.length;a++){var g=k[a];d.put(g.mode,4);d.put(g.getLength(),q.getLengthInBits(g.mode,c));g.write(d)}for(a=
c=0;a<l.length;a++)c+=l[a].dataCount;if(d.getLengthInBits()>8*c)throw Error("code length overflow. ("+d.getLengthInBits()+">"+8*c+")");for(d.getLengthInBits()+4<=8*c&&d.put(0,4);0!=d.getLengthInBits()%8;)d.putBit(!1);for(;!(d.getLengthInBits()>=8*c||(d.put(m.PAD0,8),d.getLengthInBits()>=8*c));)d.put(m.PAD1,8);return m.createBytes(d,l)};m.createBytes=function(c,l){for(var b=0,d=0,e=0,a=Array(l.length),g=Array(l.length),h=0;h<l.length;h++){var n=l[h].dataCount,p=l[h].totalCount-n,d=Math.max(d,n),e=
Math.max(e,p);a[h]=Array(n);for(var v=0;v<a[h].length;v++)a[h][v]=255&c.buffer[v+b];b+=n;v=q.getErrorCorrectPolynomial(p);n=(new f(a[h],v.getLength()-1)).mod(v);g[h]=Array(v.getLength()-1);for(v=0;v<g[h].length;v++)p=v+n.getLength()-g[h].length,g[h][v]=0<=p?n.get(p):0}for(v=h=0;v<l.length;v++)h+=l[v].totalCount;b=Array(h);for(v=n=0;d>v;v++)for(h=0;h<l.length;h++)v<a[h].length&&(b[n++]=a[h][v]);for(v=0;e>v;v++)for(h=0;h<l.length;h++)v<g[h].length&&(b[n++]=g[h][v]);return b};for(var n={MODE_NUMBER:1,
MODE_ALPHA_NUM:2,MODE_8BIT_BYTE:4,MODE_KANJI:8},p={L:1,M:0,Q:3,H:2},q={PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50],[6,30,54],[6,32,58],[6,34,62],[6,26,46,66],[6,26,48,70],[6,26,50,74],[6,30,54,78],[6,30,56,82],[6,30,58,86],[6,34,62,90],[6,28,50,72,94],[6,26,50,74,98],[6,30,54,78,102],[6,28,54,80,106],[6,32,58,84,110],[6,30,58,86,114],[6,34,62,90,118],[6,26,50,74,98,122],[6,30,54,78,102,126],[6,26,52,78,104,130],[6,30,56,82,108,134],[6,34,60,
86,112,138],[6,30,58,86,114,142],[6,34,62,90,118,146],[6,30,54,78,102,126,150],[6,24,50,76,102,128,154],[6,28,54,80,106,132,158],[6,32,58,84,110,136,162],[6,26,54,82,110,138,166],[6,30,58,86,114,142,170]],G15:1335,G18:7973,G15_MASK:21522,getBCHTypeInfo:function(c){for(var b=c<<10;0<=q.getBCHDigit(b)-q.getBCHDigit(q.G15);)b^=q.G15<<q.getBCHDigit(b)-q.getBCHDigit(q.G15);return(c<<10|b)^q.G15_MASK},getBCHTypeNumber:function(c){for(var b=c<<12;0<=q.getBCHDigit(b)-q.getBCHDigit(q.G18);)b^=q.G18<<q.getBCHDigit(b)-
q.getBCHDigit(q.G18);return c<<12|b},getBCHDigit:function(c){for(var b=0;0!=c;)b++,c>>>=1;return b},getPatternPosition:function(c){return q.PATTERN_POSITION_TABLE[c-1]},getMask:function(c,b,k){switch(c){case 0:return 0==(b+k)%2;case 1:return 0==b%2;case 2:return 0==k%3;case 3:return 0==(b+k)%3;case 4:return 0==(Math.floor(b/2)+Math.floor(k/3))%2;case 5:return 0==b*k%2+b*k%3;case 6:return 0==(b*k%2+b*k%3)%2;case 7:return 0==(b*k%3+(b+k)%2)%2;default:throw Error("bad maskPattern:"+c);}},getErrorCorrectPolynomial:function(c){for(var b=
new f([1],0),k=0;c>k;k++)b=b.multiply(new f([1,h.gexp(k)],0));return b},getLengthInBits:function(c,b){if(1<=b&&10>b)switch(c){case n.MODE_NUMBER:return 10;case n.MODE_ALPHA_NUM:return 9;case n.MODE_8BIT_BYTE:return 8;case n.MODE_KANJI:return 8;default:throw Error("mode:"+c);}else if(27>b)switch(c){case n.MODE_NUMBER:return 12;case n.MODE_ALPHA_NUM:return 11;case n.MODE_8BIT_BYTE:return 16;case n.MODE_KANJI:return 10;default:throw Error("mode:"+c);}else{if(!(41>b))throw Error("type:"+b);switch(c){case n.MODE_NUMBER:return 14;
case n.MODE_ALPHA_NUM:return 13;case n.MODE_8BIT_BYTE:return 16;case n.MODE_KANJI:return 12;default:throw Error("mode:"+c);}}},getLostPoint:function(c){for(var b=c.getModuleCount(),k=0,d=0;b>d;d++)for(var a=0;b>a;a++){for(var e=0,g=c.isDark(d,a),h=-1;1>=h;h++)if(!(0>d+h||d+h>=b))for(var f=-1;1>=f;f++)0>a+f||a+f>=b||(0!=h||0!=f)&&g==c.isDark(d+h,a+f)&&e++;5<e&&(k+=3+e-5)}for(d=0;b-1>d;d++)for(a=0;b-1>a;a++)e=0,c.isDark(d,a)&&e++,c.isDark(d+1,a)&&e++,c.isDark(d,a+1)&&e++,c.isDark(d+1,a+1)&&e++,0!=e&&
4!=e||(k+=3);for(d=0;b>d;d++)for(a=0;b-6>a;a++)c.isDark(d,a)&&!c.isDark(d,a+1)&&c.isDark(d,a+2)&&c.isDark(d,a+3)&&c.isDark(d,a+4)&&!c.isDark(d,a+5)&&c.isDark(d,a+6)&&(k+=40);for(a=0;b>a;a++)for(d=0;b-6>d;d++)c.isDark(d,a)&&!c.isDark(d+1,a)&&c.isDark(d+2,a)&&c.isDark(d+3,a)&&c.isDark(d+4,a)&&!c.isDark(d+5,a)&&c.isDark(d+6,a)&&(k+=40);for(a=e=0;b>a;a++)for(d=0;b>d;d++)c.isDark(d,a)&&e++;return k+Math.abs(100*e/b/b-50)/5*10}},h={glog:function(c){if(1>c)throw Error("glog("+c+")");return h.LOG_TABLE[c]},
gexp:function(c){for(;0>c;)c+=255;for(;256<=c;)c-=255;return h.EXP_TABLE[c]},EXP_TABLE:Array(256),LOG_TABLE:Array(256)},r=0;8>r;r++)h.EXP_TABLE[r]=1<<r;for(r=8;256>r;r++)h.EXP_TABLE[r]=h.EXP_TABLE[r-4]^h.EXP_TABLE[r-5]^h.EXP_TABLE[r-6]^h.EXP_TABLE[r-8];for(r=0;255>r;r++)h.LOG_TABLE[h.EXP_TABLE[r]]=r;f.prototype={get:function(c){return this.num[c]},getLength:function(){return this.num.length},multiply:function(c){for(var b=Array(this.getLength()+c.getLength()-1),a=0;a<this.getLength();a++)for(var d=
0;d<c.getLength();d++)b[a+d]^=h.gexp(h.glog(this.get(a))+h.glog(c.get(d)));return new f(b,0)},mod:function(c){if(0>this.getLength()-c.getLength())return this;for(var b=h.glog(this.get(0))-h.glog(c.get(0)),a=Array(this.getLength()),d=0;d<this.getLength();d++)a[d]=this.get(d);for(d=0;d<c.getLength();d++)a[d]^=h.gexp(h.glog(c.get(d))+b);return(new f(a,0)).mod(c)}};b.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[2,35,17],[2,35,13],
[1,100,80],[2,50,32],[2,50,24],[4,25,9],[1,134,108],[2,67,43],[2,33,15,2,34,16],[2,33,11,2,34,12],[2,86,68],[4,43,27],[4,43,19],[4,43,15],[2,98,78],[4,49,31],[2,32,14,4,33,15],[4,39,13,1,40,14],[2,121,97],[2,60,38,2,61,39],[4,40,18,2,41,19],[4,40,14,2,41,15],[2,146,116],[3,58,36,2,59,37],[4,36,16,4,37,17],[4,36,12,4,37,13],[2,86,68,2,87,69],[4,69,43,1,70,44],[6,43,19,2,44,20],[6,43,15,2,44,16],[4,101,81],[1,80,50,4,81,51],[4,50,22,4,51,23],[3,36,12,8,37,13],[2,116,92,2,117,93],[6,58,36,2,59,37],[4,
46,20,6,47,21],[7,42,14,4,43,15],[4,133,107],[8,59,37,1,60,38],[8,44,20,4,45,21],[12,33,11,4,34,12],[3,145,115,1,146,116],[4,64,40,5,65,41],[11,36,16,5,37,17],[11,36,12,5,37,13],[5,109,87,1,110,88],[5,65,41,5,66,42],[5,54,24,7,55,25],[11,36,12],[5,122,98,1,123,99],[7,73,45,3,74,46],[15,43,19,2,44,20],[3,45,15,13,46,16],[1,135,107,5,136,108],[10,74,46,1,75,47],[1,50,22,15,51,23],[2,42,14,17,43,15],[5,150,120,1,151,121],[9,69,43,4,70,44],[17,50,22,1,51,23],[2,42,14,19,43,15],[3,141,113,4,142,114],[3,
70,44,11,71,45],[17,47,21,4,48,22],[9,39,13,16,40,14],[3,135,107,5,136,108],[3,67,41,13,68,42],[15,54,24,5,55,25],[15,43,15,10,44,16],[4,144,116,4,145,117],[17,68,42],[17,50,22,6,51,23],[19,46,16,6,47,17],[2,139,111,7,140,112],[17,74,46],[7,54,24,16,55,25],[34,37,13],[4,151,121,5,152,122],[4,75,47,14,76,48],[11,54,24,14,55,25],[16,45,15,14,46,16],[6,147,117,4,148,118],[6,73,45,14,74,46],[11,54,24,16,55,25],[30,46,16,2,47,17],[8,132,106,4,133,107],[8,75,47,13,76,48],[7,54,24,22,55,25],[22,45,15,13,
46,16],[10,142,114,2,143,115],[19,74,46,4,75,47],[28,50,22,6,51,23],[33,46,16,4,47,17],[8,152,122,4,153,123],[22,73,45,3,74,46],[8,53,23,26,54,24],[12,45,15,28,46,16],[3,147,117,10,148,118],[3,73,45,23,74,46],[4,54,24,31,55,25],[11,45,15,31,46,16],[7,146,116,7,147,117],[21,73,45,7,74,46],[1,53,23,37,54,24],[19,45,15,26,46,16],[5,145,115,10,146,116],[19,75,47,10,76,48],[15,54,24,25,55,25],[23,45,15,25,46,16],[13,145,115,3,146,116],[2,74,46,29,75,47],[42,54,24,1,55,25],[23,45,15,28,46,16],[17,145,115],
[10,74,46,23,75,47],[10,54,24,35,55,25],[19,45,15,35,46,16],[17,145,115,1,146,116],[14,74,46,21,75,47],[29,54,24,19,55,25],[11,45,15,46,46,16],[13,145,115,6,146,116],[14,74,46,23,75,47],[44,54,24,7,55,25],[59,46,16,1,47,17],[12,151,121,7,152,122],[12,75,47,26,76,48],[39,54,24,14,55,25],[22,45,15,41,46,16],[6,151,121,14,152,122],[6,75,47,34,76,48],[46,54,24,10,55,25],[2,45,15,64,46,16],[17,152,122,4,153,123],[29,74,46,14,75,47],[49,54,24,10,55,25],[24,45,15,46,46,16],[4,152,122,18,153,123],[13,74,
46,32,75,47],[48,54,24,14,55,25],[42,45,15,32,46,16],[20,147,117,4,148,118],[40,75,47,7,76,48],[43,54,24,22,55,25],[10,45,15,67,46,16],[19,148,118,6,149,119],[18,75,47,31,76,48],[34,54,24,34,55,25],[20,45,15,61,46,16]];b.getRSBlocks=function(c,a){var k=b.getRsBlockTable(c,a);if(void 0==k)throw Error("bad rs block @ typeNumber:"+c+"/errorCorrectLevel:"+a);for(var d=k.length/3,e=[],l=0;d>l;l++)for(var g=k[3*l+0],h=k[3*l+1],f=k[3*l+2],n=0;g>n;n++)e.push(new b(h,f));return e};b.getRsBlockTable=function(c,
a){switch(a){case p.L:return b.RS_BLOCK_TABLE[4*(c-1)+0];case p.M:return b.RS_BLOCK_TABLE[4*(c-1)+1];case p.Q:return b.RS_BLOCK_TABLE[4*(c-1)+2];case p.H:return b.RS_BLOCK_TABLE[4*(c-1)+3]}};e.prototype={get:function(c){return 1==(1&this.buffer[Math.floor(c/8)]>>>7-c%8)},put:function(c,b){for(var a=0;b>a;a++)this.putBit(1==(1&c>>>b-a-1))},getLengthInBits:function(){return this.length},putBit:function(c){var b=Math.floor(this.length/8);this.buffer.length<=b&&this.buffer.push(0);c&&(this.buffer[b]|=
128>>>this.length%8);this.length++}};var u=[[17,14,11,7],[32,26,20,14],[53,42,32,24],[78,62,46,34],[106,84,60,44],[134,106,74,58],[154,122,86,64],[192,152,108,84],[230,180,130,98],[271,213,151,119],[321,251,177,137],[367,287,203,155],[425,331,241,177],[458,362,258,194],[520,412,292,220],[586,450,322,250],[644,504,364,280],[718,560,394,310],[792,624,442,338],[858,666,482,382],[929,711,509,403],[1003,779,565,439],[1091,857,611,461],[1171,911,661,511],[1273,997,715,535],[1367,1059,751,593],[1465,1125,
805,625],[1528,1190,868,658],[1628,1264,908,698],[1732,1370,982,742],[1840,1452,1030,790],[1952,1538,1112,842],[2068,1628,1168,898],[2188,1722,1228,958],[2303,1809,1283,983],[2431,1911,1351,1051],[2563,1989,1423,1093],[2699,2099,1499,1139],[2809,2213,1579,1219],[2953,2331,1663,1273]],r=function(){var b=function(b,c){this._el=b;this._htOption=c};return b.prototype.draw=function(b){function c(b,c){var a=document.createElementNS("http://www.w3.org/2000/svg",b),d;for(d in c)c.hasOwnProperty(d)&&a.setAttribute(d,
c[d]);return a}var a=this._htOption,e=this._el,g=b.getModuleCount();Math.floor(a.width/g);Math.floor(a.height/g);this.clear();var h=c("svg",{viewBox:"0 0 "+String(g)+" "+String(g),width:"100%",height:"100%",fill:a.colorLight});h.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:xlink","http://www.w3.org/1999/xlink");e.appendChild(h);h.appendChild(c("rect",{fill:a.colorDark,width:"1",height:"1",id:"template"}));for(a=0;g>a;a++)for(e=0;g>e;e++)if(b.isDark(a,e)){var l=c("use",{x:String(a),y:String(e)});
l.setAttributeNS("http://www.w3.org/1999/xlink","href","#template");h.appendChild(l)}},b.prototype.clear=function(){for(;this._el.hasChildNodes();)this._el.removeChild(this._el.lastChild)},b}(),x="svg"===document.documentElement.tagName.toLowerCase()?r:"undefined"!=typeof CanvasRenderingContext2D?function(){function b(){this._elImage.src=this._elCanvas.toDataURL("image/png");this._elImage.style.display="block";this._elCanvas.style.display="none"}function a(b,c){var a=this;if(a._fFail=c,a._fSuccess=
b,null===a._bSupportDataURI){var d=document.createElement("img"),e=function(){a._bSupportDataURI=!1;a._fFail&&_fFail.call(a)};return d.onabort=e,d.onerror=e,d.onload=function(){a._bSupportDataURI=!0;a._fSuccess&&a._fSuccess.call(a)},d.src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==",void 0}!0===a._bSupportDataURI&&a._fSuccess?a._fSuccess.call(a):!1===a._bSupportDataURI&&a._fFail&&a._fFail.call(a)}if(this._android&&
2.1>=this._android){var e=1/window.devicePixelRatio,d=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(b,c,a,k,h,g,l,f){if("nodeName"in b&&/img/i.test(b.nodeName))for(var n=arguments.length-1;1<=n;n--)arguments[n]*=e;else"undefined"==typeof f&&(arguments[1]*=e,arguments[2]*=e,arguments[3]*=e,arguments[4]*=e);d.apply(this,arguments)}}var h=function(b,c){this._bIsPainted=!1;this._android=g();this._htOption=c;this._elCanvas=document.createElement("canvas");
this._elCanvas.width=c.width;this._elCanvas.height=c.height;b.appendChild(this._elCanvas);this._el=b;this._oContext=this._elCanvas.getContext("2d");this._bIsPainted=!1;this._elImage=document.createElement("img");this._elImage.style.display="none";this._el.appendChild(this._elImage);this._bSupportDataURI=null};return h.prototype.draw=function(b){var c=this._elImage,a=this._oContext,d=this._htOption,e=b.getModuleCount(),k=d.width/e,h=d.height/e,g=Math.round(k),l=Math.round(h);c.style.display="none";
this.clear();for(c=0;e>c;c++)for(var f=0;e>f;f++){var n=b.isDark(c,f),p=f*k,m=c*h;a.strokeStyle=n?d.colorDark:d.colorLight;a.lineWidth=1;a.fillStyle=n?d.colorDark:d.colorLight;a.fillRect(p,m,k,h);a.strokeRect(Math.floor(p)+.5,Math.floor(m)+.5,g,l);a.strokeRect(Math.ceil(p)-.5,Math.ceil(m)-.5,g,l)}this._bIsPainted=!0},h.prototype.makeImage=function(){this._bIsPainted&&a.call(this,b)},h.prototype.isPainted=function(){return this._bIsPainted},h.prototype.clear=function(){this._oContext.clearRect(0,0,
this._elCanvas.width,this._elCanvas.height);this._bIsPainted=!1},h.prototype.round=function(b){return b?Math.floor(1E3*b)/1E3:b},h}():function(){var b=function(b,c){this._el=b;this._htOption=c};return b.prototype.draw=function(b){for(var c=this._htOption,a=this._el,e=b.getModuleCount(),h=Math.floor(c.width/e),g=Math.floor(c.height/e),f=['<table style="border:0;border-collapse:collapse;">'],l=0;e>l;l++){f.push("<tr>");for(var n=0;e>n;n++)f.push('<td style="border:0;border-collapse:collapse;padding:0;margin:0;width:'+
h+"px;height:"+g+"px;background-color:"+(b.isDark(l,n)?c.colorDark:c.colorLight)+';"></td>');f.push("</tr>")}f.push("</table>");a.innerHTML=f.join("");b=a.childNodes[0];a=(c.width-b.offsetWidth)/2;c=(c.height-b.offsetHeight)/2;0<a&&0<c&&(b.style.margin=c+"px "+a+"px")},b.prototype.clear=function(){this._el.innerHTML=""},b}();QRCode=function(b,a){if(this._htOption={width:256,height:256,typeNumber:4,colorDark:"#000000",colorLight:"#ffffff",correctLevel:p.H},"string"==typeof a&&(a={text:a}),a)for(var c in a)this._htOption[c]=
a[c];"string"==typeof b&&(b=document.getElementById(b));this._android=g();this._el=b;this._oQRCode=null;this._oDrawing=new x(this._el,this._htOption);this._htOption.text&&this.makeCode(this._htOption.text)};QRCode.prototype.makeCode=function(b){var c=this._htOption.correctLevel,a=1,d;d=encodeURI(b).toString().replace(/\%[0-9a-fA-F]{2}/g,"a");d=d.length+(d.length!=b?3:0);for(var e=0,h=u.length;h>=e;e++){var g=0;switch(c){case p.L:g=u[e][0];break;case p.M:g=u[e][1];break;case p.Q:g=u[e][2];break;case p.H:g=
u[e][3]}if(g>=d)break;a++}if(a>u.length)throw Error("Too long data");this._oQRCode=new m(a,this._htOption.correctLevel);this._oQRCode.addData(b);this._oQRCode.make();this._el.title=b;this._oDrawing.draw(this._oQRCode);this.makeImage()};QRCode.prototype.makeImage=function(){"function"==typeof this._oDrawing.makeImage&&(!this._android||3<=this._android)&&this._oDrawing.makeImage()};QRCode.prototype.clear=function(){this._oDrawing.clear()};QRCode.CorrectLevel=p}();
function SharingManager(a,m){function f(){g.classList.remove("hidden")}function b(){g.classList.add("hidden");n&&n()}function e(a){if("more"==a.target.id)for(a=0;a<p.length;a++){var c=p[a];"more"==c.id?c.classList.add("hidden"):c.classList.remove("hidden")}else"qr"==a.target.id?qrElement.classList.toggle("hidden"):("mail"==a.target.id?window.location.href="mailto:?subject="+encodeURIComponent(r)+"&body="+encodeURIComponent(h):"link"==a.target.id?(copyElement.classList.remove("hidden"),copyElement.value=
h,copyElement.select(),document.execCommand("copy"),copyElement.classList.add("hidden")):(a=u[a.target.id].replace("URL",encodeURIComponent(h)).replace("DESCRIPTION",encodeURIComponent(r)),window.open(a,"sharing...","top="+(screen.height/2-175)+",left="+(screen.width/2-260)+",toolbar=0,status=0,width=520,height=350")),b())}var g=a,n=void 0===m?null:m,p=null,q="a"+Math.random(),h="",r="",u={qq:"http://v.t.qq.com/share/share.php?url=URL&title=DESCRIPTION",weibo:"http://service.weibo.com/share/share.php?url=URL&title=DESCRIPTION",
qzone:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=URL&title=DESCRIPTION",facebook:"https://www.facebook.com/sharer/sharer.php?u=URL&t=DESCRIPTION",twitter:"https://twitter.com/intent/tweet?text=DESCRIPTION&url=URL&via=ScalesEscort"};(function(){g.classList.add("sharingManager");g.innerHTML='<div id="icons">  <div id="facebook" class="icon"></div>  <div id="twitter" class="icon"></div>  <div id="weibo" class="icon"></div><div id="qzone" class="icon"></div>    <div id="mail" class="icon"></div>  <div id="qr" class="icon"></div>  <div id="link" class="icon"></div>  <div id="more" class="icon"></div></div><div id="'+
q+'" class="qr hidden"></div><input id="copy" class="hidden"/>';qrElement=g.querySelector("div.qr");copyElement=g.querySelector("input#copy");p=[];for(var b=g.querySelectorAll("div.icon"),c=0;c<b.length;c++)p.push(b[c]);for(c=0;c<p.length;c++)b=p[c],b.addEventListener("click",e),0<=["zh-cn","zh"].indexOf(window.navigator.language)?0<=["facebook","twitter"].indexOf(b.id)&&b.classList.add("hidden"):0<=["weibo","qq","qzone"].indexOf(b.id)&&b.classList.add("hidden")})();return{isDisplayed:function(){return!g.classList.contains("hidden")},
display:f,hide:b,share:function(b,c){h=b;r=c;qrElement.innerHTML="";new QRCode(q,{text:h,width:256,height:256,colorDark:"#000000",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H});f()}}}
var encoder=function(){function a(b,a){a=void 0===a?f:a;if(b<a.base.length)return a.base[b];if(b<a.base.length*(a.extra.length+1))return a.extra[Math.floor(b/a.base.length)-1]+a.base[b%a.base.length];for(var e=a.extraExtra;;){if(b<a.base.length){e+=a.base[b];break}e+=a.base[b%a.base.length];b=Math.floor(b/a.base.length)}return e+a.extraExtra}function m(b,a,g){g=void 0===g?f:g;var e={};if(a>=b.length)return null;if(0<=g.base.indexOf(b[a])){var p=g.base.indexOf(b[a]);if(0>p)return null;e.value=p;e.end=
a+1}else if(0<=g.extra.indexOf(b[a])){if(a==b.lengt-1)return null;p=g.extra.indexOf(b[a])+1;b=g.base.indexOf(b[a+1]);if(0>=p||0>b)return null;e.value=p*g.base.length+b;e.end=a+2}else if(g.extraExtra==b[a]){var m=a+1,h=b.indexOf(g.extraExtra,m);if(h<=m)return null;p=g.base.indexOf(b[h-1]);if(0>p)return null;for(var r=h-2;r>=m;r--){var u=g.base.indexOf(b[r]);if(0>u)return null;p=p*g.base.length+u}e.value=p;e.end=a+h-m+2}a=[];for(var x in e)e.hasOwnProperty(x)&&a.push(x);return 0==a.length?null:e}var f=
{base:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",extra:"0123456789-.",extraExtra:"_",reserved:"~"};return{encodeInt:a,decodeInt:m,encodeIntArray:function(b,e){e=void 0===e?f:e;for(var g="",n=0;n<b.length;n++)g+=a(b[n],e);return g},decodeIntArray:function(b,a){a=void 0===a?f:a;for(var e=[],n=0;n<b.length;){n=m(b,n,a);if(null==n)return null;e.push(n.value);n=n.end}return e},URLIntCodingParams:f}}(),ConfigManager=function(){function a(b){for(var a=b.name,g="",f=0;f<b.sequences.length;f++)var p=
b.sequences[f],m=b[p],a=a+("~"+p),g=g+("~"+encoder.encodeIntArray(m.beats.concat(m.repeats)));return"?n="+a+"&v="+g.substring(1)}function m(a){if(null==a)return null;var b={},g=a.indexOf("?n="),f=a.indexOf("&v=");if(0!=g||0>f)return null;g=a.substring(3,f).split("~");if(1>g.length)return null;b.name=g[0];g.splice(0,1);b.sequences=g;var m=g.length;a=a.substring(f+3).split("~");if(a.length<m)return null;for(f=0;f<m;f++){var q=encoder.decodeIntArray(a[f]),h=q&&q.length||0;if(0>=h)return null;var r={};
r.repeats=q[h-1];q.splice(h-1,1);r.beats=q;b[g[f]]=r}return b}function f(){return{name:"Untitled",sequences:["S1"],S1:{beats:[60],repeats:1}}}return{clone:function(b){return m(a(b))},toString:a,fromString:m,isEmptyConfig:function(b){return a(b)==a(f())},isKnownConfig:function(b){var e=a(b);if(localStorage.getItem("~config~"+b.name)==e||a(b)==a(f()))return"~exact";e=e.substring(e.indexOf("&v="));for(b=0;b<localStorage.length;b++){var g=localStorage.key(b);if(0==g.indexOf("~config~")){var m=localStorage.getItem(g);
if(e==m.substring(m.indexOf("&v=")))return g.substring(8)}}return"~unknown"},getConfigByName:function(a){return m(localStorage.getItem("~config~"+a))||f()},setLastConfig:function(a){localStorage.setItem("~lastConfig",a.name)},getLastConfig:function(){var a=localStorage.getItem("~lastConfig");return null==a?null:m(localStorage.getItem("~config~"+a))},getEmptyConfig:f,getAllConfigNames:function(){for(var a=[],e=0;e<localStorage.length;e++){var g=localStorage.key(e);0==g.indexOf("~config~")&&a.push(g.substring(8))}return a},
save:function(b){localStorage.setItem("~config~"+b.name,a(b))},discard:function(a){localStorage.removeItem("~config~"+a.name)}}}(),PitchGenerator=function(){function a(){if(null!=b)return!0;if("AudioContext"in window)b=new AudioContext;else if("webkitAudioContext"in window)b=new webkitAudioContext;else return b=null,!1;g=b.createGain();g.gain.value=0;g.connect(b.destination);return!0}function m(){a();n&&(n=!1,g.gain.linearRampToValueAtTime(.5,b.currentTime),g.gain.linearRampToValueAtTime(0,b.currentTime+
.05),setTimeout(function(){e.stop(0);oscillator2.stop(0);e.disconnect(g);oscillator2.disconnect(g)},50))}function f(e,f,h){a();var m=b.createOscillator();m.frequency.value=e;m.connect(g);m.start(0);g.gain.linearRampToValueAtTime(0,b.currentTime);g.gain.linearRampToValueAtTime(.5,b.currentTime+f);g.gain.linearRampToValueAtTime(.5,b.currentTime+h-f);g.gain.linearRampToValueAtTime(0,b.currentTime+h);setTimeout(function(){m.stop(0);m.disconnect(g)},1E3*h)}var b=null,e=null,g=e=null,n=!1;return{switchOn:function(f,
m){a();if(!n){n=!0;e=b.createOscillator();oscillator2=b.createOscillator();e.frequency.value=f;oscillator2.frequency.value=m;var h=Math.PI,p=new Float32Array(12),q=new Float32Array(12),x=[.49,.995,.94,.425,.48,0,.365,.04,.085,0,.09,0],h=[0,0,h/2,0,h/2,0,h/2,0,h/2,0,h/2,0];p[0]=0;q[0]=0;for(var c=1;12>c;c++)p[c]=x[c]*x[0]*Math.cos(h[c]),q[c]=x[c]*x[0]*Math.sin(h[c]);x=b.createPeriodicWave(q,p);p=b.createPeriodicWave(q,p);e.setPeriodicWave(x);oscillator2.setPeriodicWave(p);e.connect(g);oscillator2.connect(g);
e.start(0);oscillator2.start(0);g.gain.linearRampToValueAtTime(0,b.currentTime);g.gain.linearRampToValueAtTime(.5,b.currentTime+.05)}},switchOff:function(){m()},switchOnAndOff:function(a,b,e){f(a,b,e)},invalidateAudioContext:function(){null!=b&&(b.close(),b=null)}}}(),BlinkingBackgroundAnimator=function(){function a(){"blinking"!=q||p>g?(m.style.backgroundColor=f,q="idle"):(m.style.backgroundColor="hsl("+b+","+e+"%,"+100*(.2+p/g*.8)+"%)",p+=1,setTimeout(a,n))}var m=null,f=0,b="100",e="0",g=10,n=20,
p=0,q="idle";return{start:function(h,r,u,x,c){if("idle"!=q)return!1;q="blinking";m=h;f=m.style.backgroundColor;b=void 0===r?"120":r;e=void 0===u?"100":u;g=void 0===x?10:x;n=void 0===c?20:c;p=0;a();return!0}}}();
function TabManager(a,m,f,b,e,g,n){function p(a){var b=a.target.value.trim(),c=w.childNodes[k],d=B.childNodes[k];""==b?(a=a.target.parentNode,a=Array.from(w.childNodes).indexOf(a),E&&E(a),w.removeChild(c),B.removeChild(d),l>a&&--l,u(l)):(null!=K&&(b=K(k,b,a.target.getAttribute("original"))),c.innerHTML=b)}function q(a,b){a.innerHTML='<input id="tabName" placeholder="Tab Name"></input>';var c=a.querySelector("input#tabName");c.setAttribute("original",b);c.value=b;c.focus();c.addEventListener("blur",
p)}function h(a){var b=w.childNodes.length-1,c=document.createElement("div");c.classList.add("tab");c.innerHTML=a;w.insertBefore(c,d);a=document.createElement("div");a.classList.add("content");B.appendChild(a);u(b);null!=P&&P(b);""==c.innerHTML.trim()&&q(c,"");c.addEventListener("click",function(a){a=a.target;a=Array.from(w.childNodes).indexOf(a);a==k?(a=w.childNodes[a],q(a,a.innerHTML)):u(a)})}function r(a,b){return 0<=a&&a<w.childNodes.length?(w.childNodes[a].innerHTML=b,!0):!1}function u(a){void 0===
w.childNodes[a]||a>=w.childNodes.length-1||(null!=M&&l!=a&&M(l,a),l=k,l<w.childNodes.length-1&&(w.childNodes[l].classList.remove("active"),B.childNodes[l].classList.add("hidden")),k=a,w.childNodes[k].classList.add("active"),B.childNodes[k].classList.remove("hidden"))}function x(a){0<=a&&a<w.childNodes.length-1&&(w.removeChild(w.childNodes[a]),B.removeChild(B.childNodes[a]),E&&E(a))}m=void 0===m?[]:m;f=void 0===f?[]:f;var c=Math.random(),l=0,k=0,d=null,w=null,B=null,P=void 0===b?null:b,E=void 0===
e?null:e,M=void 0===g?null:g,K=void 0===n?null:n;(function(b,c){a.classList.add("TabManager");for(var e=0;e<c.length;e++)a.classList.add(c[e]);a.innerHTML='<div id="tabs"><div id="newTab"></div></div><div class="clearBoth"></div><div id="contents"></div>';w=a.querySelector("div#tabs");B=a.querySelector("div#contents");for(e=0;e<b.length;e++)h(b[e]);d=a.querySelector("div#tabs > div#newTab");d.addEventListener("click",function(){h("")});u(0)})(m,f);return{id:c,getTabElement:function(a){return 0<=a&&
a<w.childNodes.length-1?w.childNodes[a]:null},getContentElement:function(a){return 0<=a&&a<B.childNodes.length?B.childNodes[a]:null},setActiveTabName:function(a){r(k,a)},setTabName:r,getTabName:function(a){return 0<=a&&a<w.childNodes.length?w.childNodes[a].innerHTML:null},getAllTabNames:function(){for(var a=[],b=0;b<w.childNodes.length-1;b++)a.push(w.childNodes[b].innerHTML);return a},addTab:function(a){h(a)},resize:function(b,c){a.style.width=b+"px";a.style.height=(void 0===c?32:c)+"px"},setActiveTab:u,
removeTab:x,removeAllTabs:function(){for(var a=w.childNodes.length-1;0<=a;a--)x(a)}}}
function Slider(a,m,f){function b(){var a=g.getBoundingClientRect(),b=p.getBoundingClientRect(),e=q.getBoundingClientRect(),f=h.getBoundingClientRect(),d=a.left,m=a.right-f.width;p.style.top=.5*(a.height-b.height)+"px";p.style.left="0px";q.style.top=.5*(a.height-e.height)-b.height+"px";q.style.left="0px";h.style.top=.5*(a.height-f.height)-b.height-e.height+"px";h.style.left=d+(m-d)*u+"px"}function e(a){var b=g.getBoundingClientRect(),e=h.getBoundingClientRect(),f=b.right-e.width;a>f&&(a=f);a<b.left&&
(a=b.left);h.style.left=a-b.left+"px";f=b.left;u=(a-f)/(b.right-e.width-f);null!=n&&n(u)}var g=a,n=m,p=null,q=null,h=null,r=!1,u=0;(function(){g.classList.add("Slider");g.ondragstart=function(){return!1};g.ondrop=function(){return!1};g.innerHTML='<div id="hiddenSlide"></div><div id="slide"></div><div id="knob"></div>';p=g.querySelector("div#hiddenSlide");q=g.querySelector("div#slide");h=g.querySelector("div#knob");var a="mousedown",c="mousemove",l="mouseup";"ontouchstart"in window&&(a="touchstart",
c="touchmove",l="touchend");h.addEventListener(a,function(){event.preventDefault();r=!0;h.classList.add("activated")});window.addEventListener(l,function(a){r&&(a.preventDefault(),e("touchend"===a.type?a.changedTouches[0].clientX:a.clientX),"function"==typeof f&&f(),r=!1,h.classList.remove("activated"))});window.addEventListener(c,function(a){r&&(a.preventDefault(),e("touchmove"===a.type?a.changedTouches[0].clientX:a.clientX))});p.addEventListener("click",function(a){e(a.clientX);f&&f()});b()})();
return{set:function(a){u=1<a?1:0>a?0:a;a=g.getBoundingClientRect();var b=h.getBoundingClientRect();h.style.left=(a.right-b.width-a.left)*u+"px"}}}
function SequenceManager(a,m,f){function b(a){h.beats.splice(a,1)}function e(){r()}function g(a,b,c){b=parseInt(b);if(20<=b&&300>=b)return d.set((b-20)/280),h.beats[a]=b,b!=parseInt(c)&&r(),a,""+b;Toast.show("A valid beat is a number between 20 and 300.");return c}function n(a){var b=60;0<a&&(b=parseInt(k.getTabName(a-1)));a<h.beats.length?b=h.beats[a]:(h.beats.push(b),r());k.setTabName(a,""+b);d.set((b-20)/280)}function p(a,b){var c=k.getTabName(b),c=(parseInt(c)-20)/280;d.set(c)}function q(a){k.setActiveTabName(""+
Math.floor(280*a+20))}var h=m,r=f,u=null,x=null,c=null,l=null,k=null,d=null;(function(){a.classList.add("SequenceManager");a.innerHTML='<div id="beats">beats</div><div id="value"></div><div id="repeats"><div id="repeatsLabel" class="label">Repeats (0 for indefinite): </div><input type="number" min="0" id="repeats"></input></div><div class="clearBoth"></div>';u=a.querySelector("div#beats");x=a.querySelector("div#value");c=a.querySelector("input#repeats");l=a.querySelector("div#repeatsLabel");k=new TabManager(u,
[],["sequence"],n,b,p,g);d=new Slider(x,q,e);for(var f=0;f<h.beats.length;f++)k.addTab(""+h.beats[f]);k.setActiveTab(0);c.value=""+h.repeats;c.addEventListener("input",function(){var a=parseInt(c.value);isNaN(a)||0>a?Toast.show("Repeats must be a number and it cannot be less than 0."):a!=h.repeats&&(h.repeats=a,r())})})();return{getBeatElement:function(a){return k.getTabElement(a)},setActiveBeat:function(a){k.setActiveTab(a)},setCurrentRepeat:function(a){""==a?(c.classList.remove("hidden"),l.innerHTML=
"Repeats (0 for indefinite): "):(c.classList.add("hidden"),l.innerHTML=a)}}}
var Toast=function(){var a=null;return{initialize:function(m){m=void 0===m?[]:m;a=document.createElement("div");document.body.appendChild(a);m=void 0===m?[]:m;for(var f=0;f<a.classList.length;f++){var b=a.classList.item(f);a.classList.remove(b)}for(f=0;f<m.length;f++)a.classList.add(m[f]);a.classList.add("Toast");a.classList.add("hidden")},show:function(m,f){f=void 0===f?"short":f;a.innerHTML=m;a.classList.remove("hidden");a.classList.add("show");var b=f;"short"==f?b=1500:"long"==f&&(b=3E3);setTimeout(function(){a.classList.add("hidden");
a.classList.remove("show")},b)}}}(),ModalDialog=function(){function a(){if(!b.classList.contains("hidden")){g.style.width="0px";g.style.height="0px";if(n&&"handleWindowResized"in n)n.handleWindowResized();else{var a=window.innerHeight,f=window.innerWidth,h=0,m=0,u=.75*window.innerWidth,x=window.innerHeight-16;e.style.width=u+"px";e.style.height=x+"px";for(var c=0;c<e.childNodes.length;c++)if(!e.childNodes[c].classList.contains("ignoreWhenResizing")){var l=e.childNodes[c].getBoundingClientRect();l.top<
a&&(a=l.top);l.left<f&&(f=l.left);l.bottom>h&&(h=l.bottom);l.right>m&&(m=l.right)}f=m-f;a=h-a;u>f&&(u=f);x>a&&(x=a);e.style.width=u+"px";e.style.height=x+"px";e.style.marginTop=.25*(window.innerHeight-e.offsetHeight)+"px"}g.style.width=document.body.scrollWidth+"px";g.style.height=document.body.scrollHeight+"px"}}function m(a,b){for(var e=0;e<a.classList.length;e++){var f=a.classList.item(e);a.classList.remove(f)}for(e=0;e<b.length;e++)a.classList.add(b[e])}function f(a){m(b,["ModalDialog","hidden"].concat(a))}
var b=null,e=null,g=null,n=null;return{initialize:function(m){m=void 0===m?[]:m;b=document.createElement("div");document.body.appendChild(b);b.innerHTML='<div id="content"></div><div id="overlay" class="hidden"></div>';f(m);e=b.querySelector("div#content");g=b.querySelector("div#overlay");window.addEventListener("resize",a);a()},setTheme:f,getEventHandlers:function(){return n},getContentElement:function(){return e},onWindowResized:a,show:function(f,q,h){h=void 0===h?[]:h;b.classList.contains("hidden")&&
(e.removeAttribute("style"),e.innerHTML=f,n=q,m(e,h),g.classList.remove("hidden"),b.classList.remove("hidden"),a())},hide:function(){g.classList.add("hidden");b.classList.add("hidden")}}}();
function Confirm(a,m,f){f=void 0===f?["Ok","Cancel"]:f;a='<div id="message">'+a+'</div><div id="controls">';for(var b=0;b<f.length;b++)a+='<button class="control" onclick="ModalDialog.getEventHandlers().c('+b+');" id="c'+b+'">'+f[b]+"</button>";ModalDialog.show(a+"</div>",{c:function(a){m(a);ModalDialog.hide()}},["Confirm"])}
function Prompt(a,m,f){f=void 0===f?null:f;ModalDialog.show('<div id="message" class="card">'+a+'</div><div id="inputWrapper" class="card ignoreWhenResizing"><input id="input"></input></div><div id="error" class="card"></div><div id="controls" class="card"><button class="control" onclick="ModalDialog.getEventHandlers().submit(true);" id="ok">Ok</button><button class="control" onclick="ModalDialog.getEventHandlers().submit(false);" id="cancel">Cancel</button></div>',{submit:function(a){var b=ModalDialog.getContentElement().querySelector("input#input").value;
if(a){if(f&&(a=f(b),null!=a)){ModalDialog.getContentElement().querySelector("div#error").innerHTML=a;ModalDialog.onWindowResized();return}m(b)}else m(null);ModalDialog.hide()}},["Prompt"])}
var Locale=function(){var a="en",m={en_confirmDiscardChanges:"You have made some changes. Do you want to discard them?",en_confirmDelete:"Do you want to delete this config?",en_confirmSave:"You have made changes to current config. Do you want to save it?",en_promptGiveName:"Please give a name of your config.",en_toastErrorInConfig:"Error in loading config [%s].",en_toastCannotParse:"Cannot parse [%s].",en_toastUntitledIgnored:"Config [Untitled] ignored.",en_toastRenamedToUntitled:"Config [%s] already exists. Renamed to [Untitled].",
en_toastReceivedSameConfig:"Received [%s], but it's same as [%s].",en_toastReceived:"Received [%s].",en_toastConfigNotSaved:"Config not saved.",zh_cn_confirmDiscardChanges:"cYou have made some changes. Do you want to discard them?",zh_cn_confirmDelete:"cDo you want to delete this config?",zh_cn_confirmSave:"cYou have made changes to current config. Do you want to save it?",zh_cn_propmptGiveName:"cPlease give a name of your config.",zh_cn_toastErrorInConfig:"cError in loading config [%s].",zh_cn_toastCannotParse:"cCannot parse [%s].",
zh_cn_toastUntitledIgnored:"cConfig [Untitled] ignored.",zh_cn_toastRenamedToUntitled:"cConfig [%s] already exists. Renamed to [Untitled].",zh_cn_toastReceivedSameConfig:"cReceived [%s], but it's same as [%s].",zh_cn_toastReceived:"cReceived [%s].",zh_cn_toastConfigNotSaved:"cConfig not saved.",en_errorConfigName:"cA name cannot exist already, cannot be empty or contain ~ in it.",en_errorSequenceName:"cSequence name cannot contain ~."};return{initialize:function(){0==(navigator.languages&&0<navigator.languages.length?
navigator.languages[0]:navigator.language||navigator.userLanguage).toLowerCase().indexOf("zh-cn")&&(a="zh_cn")},getLocale:function(){return a},setLocale:function(f){a=f},getString:function(){for(var f=m[a+"_"+arguments[0]].split("%s"),b="",e=0;e<Math.min(f.length-1,arguments.length-1);e++)b+=f[e]+arguments[e+1];for(;e<f.length-1;e++)b+=f[e]+"%s";return b+=f[e]}}}();
function Metronome(a){function m(){H.classList.add("gray");Q.classList.add("gray");T=ConfigManager.clone(t)}function f(){history.replaceState({from:t.name},t.name,"index.html"+ConfigManager.toString(t));H.classList.remove("gray");Q.classList.remove("gray");y.isDisplayed()&&y.hide()}function b(){y.isDisplayed()&&y.hide();Confirm('<h2>Metronome</h2>Copyright (c) <2017> yanfu2007@gmail.com<br><br>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
function(){localStorage.setItem("~licenseReadLastTime",""+(new Date).getTime())},["Ok"])}function e(a){H.classList.contains("gray")||M()}function g(a){H.classList.contains("gray")||Confirm(Locale.getString("confirmDiscardChanges"),function(a){0==a&&E(T)},["Yes","No"])}function n(a){I.classList.contains("gray")||(y.isDisplayed()&&y.hide(),Confirm(Locale.getString("confirmDelete"),function(a){0==a&&("Untitled"!=t.name&&(ConfigManager.discard(t),d()),a=ConfigManager.getEmptyConfig(),E(a),z.value="c"+
F.indexOf("Untitled"))},["Yes","No"]))}function p(){function a(){R=!0;S.classList.add("playing");D=O=G=0;C.setActiveTab(0);L.style.pointerEvents="none";u()}y.isDisplayed()&&y.hide();R?B():K(a)}function q(){function a(){var a=location.origin,b="Metronome";ConfigManager.isEmptyConfig(t)||(a=window.location.href,b=t.name);N.classList.add("shown");y.share(a,b);y.display()}y.isDisplayed()?(N.classList.remove("shown"),y.hide()):K(a)}function h(){y.isDisplayed()&&y.hide();K(function(){var a=F[parseInt(z.value.substring(1))],
b=ConfigManager.getConfigByName(a)||ConfigManager.getEmptyConfig();E(b);z.value="c"+F.indexOf(b.name);"Untitled"==b.name?(I.classList.add("gray"),z.value!="c"+F.indexOf("Untitled")&&Toast.show(Locale.get("toastErrorInConfig",a))):I.classList.remove("gray")})}function r(){z.parentNode.removeChild(z);476<=window.innerWidth?(z.classList.remove("body"),z.classList.add("header"),U.parentNode.insertBefore(z,U)):(z.classList.add("body"),z.classList.remove("header"),L.parentNode.insertBefore(z,L));var a=
A.querySelector("div#header > div#title"),b=A.querySelector("div#header > div#titleIcon");316<=window.innerWidth?(a.classList.remove("hidden"),b.classList.add("hidden")):(a.classList.add("hidden"),b.classList.remove("hidden"))}function u(){if(R){var a=J[D];if(G>=t[t.sequences[D]].beats.length&&(G=0,O+=1,0<t[t.sequences[D]].repeats&&O>=t[t.sequences[D]].repeats)){a.setActiveBeat(0);O=0;D+=1;if(D>=t.sequences.length){B();return}a=J[D];C.setActiveTab(D)}var b=60/t[t.sequences[D]].beats[G],c=500;0==G&&
(c=750);PitchGenerator.switchOnAndOff(c,.05,.1);setTimeout(u,1E3*b);a.setActiveBeat(G);a.setCurrentRepeat("Current repeat: "+(O+1)+"/"+t[t.sequences[D]].repeats);BlinkingBackgroundAnimator.start(a.getBeatElement(G));G+=1}}function x(a){var b;b=a<t.sequences.length?t[t.sequences[a]]:{beats:[60],repeats:1};var c=new SequenceManager(C.getContentElement(a),b,f);J.push(c);""==C.getTabName(a).trim()&&C.setTabName(a,v("S"+(a+1)));a>=t.sequences.length&&(a=C.getTabName(a),t.sequences.push(a),t[a]=b,f())}
function c(a){J.splice(a,1);t.sequences.splice(a,1);f()}function l(a,b){}function k(a,b,c){if(0<=b.indexOf("~"))return Toast.show(Locale.getString("errorSequenceName")),c;if(b==c)return b;t.sequences[a]=b;t[b]=t[c];delete t[c];f();return b}function d(){F=[];for(var a=ConfigManager.getAllConfigNames().concat("Untitled"),b="",c=0;c<a.length;c++)F.push(a[c]),b+='<option value="c'+F.indexOf(a[c])+'">'+a[c]+"</option>";z.innerHTML=b}function w(){A.classList.add("Metronome");A.innerHTML='<div id="header"><div id="title">Metronome</div><div id="titleIcon" class="hidden"></div><div id="controls"><div id="icons"><div class="icon" id="save"></div><div class="icon" id="discard"></div><div class="icon" id="delete"></div><div class="icon" id="share"></div><div class="icon" id="playstop"></div></div></div></div><div class="clearBoth"></div><div id="sequences"></div><select id="configSelector"><option value="Untitled">Untitled</option></select><div id="sharing"></div>';
L=A.querySelector("div#sequences");C=new TabManager(L,[],[],x,c,l,k);U=A.querySelector("div#icons");H=A.querySelector("div#save");Q=A.querySelector("div#discard");I=A.querySelector("div#delete");N=A.querySelector("div#share");S=A.querySelector("div#playstop");z=A.querySelector("select#configSelector");y=new SharingManager(A.querySelector("div#sharing"),function(){N.classList.remove("shown")});y.hide();A.querySelector("div#title").addEventListener("click",b);A.querySelector("div#titleIcon").addEventListener("click",
b);H.addEventListener("click",e);Q.addEventListener("click",g);I.addEventListener("click",n);N.addEventListener("click",q);S.addEventListener("click",p);z.addEventListener("change",h);window.addEventListener("resize",r);r()}function B(){R=!1;S.classList.remove("playing");J[0].setActiveBeat(0);C.setActiveTab(0);L.style.pointerEvents="auto";for(var a=0;a<J.length;a++)J[a].setCurrentRepeat("")}function P(){var a=ConfigManager.fromString(window.location.search);if(null==a)return""!=window.location.search.trim()&&
Toast.show(Locale.getString("toastCannotParse",window.location.search)),null;if("Untitled"==a.name)return Toast.show(Locale.getString("toastUntitledIgnored")),null;var b=ConfigManager.isKnownConfig(a);"~exact"!=b&&("~unknown"==b?0<=ConfigManager.getAllConfigNames().indexOf(a.name)?(Toast.show(Locale.getString("toastRenamedToUntitled",a.name)),a.name="Untitled"):(Toast.show(Locale.getString("toastReceived",a.name)),ConfigManager.save(a),d()):(Toast.show(Locale.getString("toastReceivedSameConfig",a.name,
b)),a=ConfigManager.getConfigByName(b)));return a}function E(a){var b=t.name;C.removeAllTabs();t=a;for(a=0;a<t.sequences.length;a++)C.addTab(t.sequences[a]);C.setActiveTab(0);history.replaceState({from:b},t.name,"index.html"+ConfigManager.toString(t));m()}function M(){if("Untitled"==t.name){var a=ConfigManager.getAllConfigNames().concat("Untitled");Prompt(Locale.getString("promptGiveName"),function(a){null!=a?(t.name=a,ConfigManager.save(t),ConfigManager.setLastConfig(t),d(),m(),history.replaceState({from:"Untitled"},
t.name,"index.html"+ConfigManager.toString(t))):Toast.show(Locale.getString("toastConfigNotSaved"))},function(b){return null==b||""!=b.trim()&&0>b.indexOf("~")&&0>a.indexOf(b)?null:Locale.getString("errorConfigName")})}else ConfigManager.save(t),m()}function K(a,b,c){a=void 0===a?null:a;b=void 0===b?a:b;c=void 0===c?a:c;H.classList.contains("gray")?a&&a():Confirm(Locale.getString("confirmSave"),function(a){0==a?(M(),b&&b()):(E(T),c&&c())},["Yes","No"])}function v(a){var b=C.getAllTabNames();if(0>
b.indexOf(a))return a;a+="-";for(var c=1;0<=b.indexOf(a+c);c++);return a+c}var A=a,L=null,C=null,H=null,Q=null,I=null,N=null,S=null,U=null,z=null,y=null,F=null,J=[],t=ConfigManager.getEmptyConfig(),T=ConfigManager.getEmptyConfig(),G=0,O=0,D=0,R=!1;(function(){Locale.initialize();ModalDialog.initialize();Toast.initialize();PitchGenerator.switchOnAndOff(0,.05,.1);w();var a=P()||ConfigManager.getLastConfig()||ConfigManager.getEmptyConfig();E(a);"Untitled"==a.name?(I.classList.add("gray"),ConfigManager.isEmptyConfig(a)||
f()):I.classList.remove("gray");d();z.value="c"+F.indexOf(a.name)})();return{}}
var App=function(){function a(){var a="mousedown",f="mousemove",b="mouseup";"ontouchstart"in window&&(a="touchstart",f="touchmove",b="touchend");window.addEventListener(a,function(){event.preventDefault()});window.addEventListener(b,function(a){a.preventDefault()});window.addEventListener(f,function(a){a.preventDefault()})}return{initialize:function(){document.querySelector("body").innerHTML='<div id="metronome"></div>';new Metronome(document.querySelector("div#metronome"));a()}}}();
//---------------------------------------------------------------------
// QRCode for JavaScript
//
// Copyright (c) 2009 Kazuhiko Arase
//
// URL: http://www.d-project.com/
//
// Licensed under the MIT license:
//   http://www.opensource.org/licenses/mit-license.php
//
// The word "QR Code" is registered trademark of 
// DENSO WAVE INCORPORATED
//   http://www.denso-wave.com/qrcode/faqpatent-e.html
//
//---------------------------------------------------------------------


