var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(d,l,h){if(h.get||h.set)throw new TypeError("ES3 does not support getters and setters.");d!=Array.prototype&&d!=Object.prototype&&(d[l]=h.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var l=0;return $jscomp.iteratorPrototype(function(){return l<d.length?{done:!1,value:d[l++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.polyfill=function(d,l,h,a){if(l){h=$jscomp.global;d=d.split(".");for(a=0;a<d.length-1;a++){var c=d[a];c in h||(h[c]={});h=h[c]}d=d[d.length-1];a=h[d];l=l(a);l!=a&&null!=l&&$jscomp.defineProperty(h,d,{configurable:!0,writable:!0,value:l})}};
$jscomp.polyfill("Array.from",function(d){return d?d:function(d,h,a){$jscomp.initSymbolIterator();h=null!=h?h:function(a){return a};var c=[],k=d[Symbol.iterator];if("function"==typeof k)for(d=k.call(d);!(k=d.next()).done;)c.push(h.call(a,k.value));else for(var k=d.length,n=0;n<k;n++)c.push(h.call(a,d[n]));return c}},"es6-impl","es3");var QRCode;
!function(){function d(b){this.mode=n.MODE_8BIT_BYTE;this.data=b;this.parsedData=[];b=[];for(var g=0,f=this.data.length;f>g;g++){var e=this.data.charCodeAt(g);65536<e?(b[0]=240|(1835008&e)>>>18,b[1]=128|(258048&e)>>>12,b[2]=128|(4032&e)>>>6,b[3]=128|63&e):2048<e?(b[0]=224|(61440&e)>>>12,b[1]=128|(4032&e)>>>6,b[2]=128|63&e):128<e?(b[0]=192|(1984&e)>>>6,b[1]=128|63&e):b[0]=e;this.parsedData=this.parsedData.concat(b)}this.parsedData.length!=this.data.length&&(this.parsedData.unshift(191),this.parsedData.unshift(187),
this.parsedData.unshift(239))}function l(b,g){this.typeNumber=b;this.errorCorrectLevel=g;this.modules=null;this.moduleCount=0;this.dataCache=null;this.dataList=[]}function h(b,g){if(void 0==b.length)throw Error(b.length+"/"+g);for(var f=0;f<b.length&&0==b[f];)f++;this.num=Array(b.length-f+g);for(var e=0;e<b.length-f;e++)this.num[e]=b[e+f]}function a(b,g){this.totalCount=b;this.dataCount=g}function c(){this.buffer=[];this.length=0}function k(){var b=!1,g=navigator.userAgent;return/android/i.test(g)&&
(b=!0,aMat=g.toString().match(/android ([0-9]\.[0-9])/i),aMat&&aMat[1]&&(b=parseFloat(aMat[1]))),b}d.prototype={getLength:function(){return this.parsedData.length},write:function(b){for(var g=0,f=this.parsedData.length;f>g;g++)b.put(this.parsedData[g],8)}};l.prototype={addData:function(b){b=new d(b);this.dataList.push(b);this.dataCache=null},isDark:function(b,g){if(0>b||this.moduleCount<=b||0>g||this.moduleCount<=g)throw Error(b+","+g);return this.modules[b][g]},getModuleCount:function(){return this.moduleCount},
make:function(){this.makeImpl(!1,this.getBestMaskPattern())},makeImpl:function(b,g){this.moduleCount=4*this.typeNumber+17;this.modules=Array(this.moduleCount);for(var f=0;f<this.moduleCount;f++){this.modules[f]=Array(this.moduleCount);for(var e=0;e<this.moduleCount;e++)this.modules[f][e]=null}this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(b,
g);7<=this.typeNumber&&this.setupTypeNumber(b);null==this.dataCache&&(this.dataCache=l.createData(this.typeNumber,this.errorCorrectLevel,this.dataList));this.mapData(this.dataCache,g)},setupPositionProbePattern:function(b,g){for(var f=-1;7>=f;f++)if(!(-1>=b+f||this.moduleCount<=b+f))for(var e=-1;7>=e;e++)-1>=g+e||this.moduleCount<=g+e||(this.modules[b+f][g+e]=0<=f&&6>=f&&(0==e||6==e)||0<=e&&6>=e&&(0==f||6==f)||2<=f&&4>=f&&2<=e&&4>=e?!0:!1)},getBestMaskPattern:function(){for(var b=0,g=0,f=0;8>f;f++){this.makeImpl(!0,
f);var e=p.getLostPoint(this);(0==f||b>e)&&(b=e,g=f)}return g},createMovieClip:function(b,g,f){b=b.createEmptyMovieClip(g,f);this.make();for(g=0;g<this.modules.length;g++){f=1*g;for(var e=0;e<this.modules[g].length;e++){var r=1*e;this.modules[g][e]&&(b.beginFill(0,100),b.moveTo(r,f),b.lineTo(r+1,f),b.lineTo(r+1,f+1),b.lineTo(r,f+1),b.endFill())}}return b},setupTimingPattern:function(){for(var b=8;b<this.moduleCount-8;b++)null==this.modules[b][6]&&(this.modules[b][6]=0==b%2);for(b=8;b<this.moduleCount-
8;b++)null==this.modules[6][b]&&(this.modules[6][b]=0==b%2)},setupPositionAdjustPattern:function(){for(var b=p.getPatternPosition(this.typeNumber),g=0;g<b.length;g++)for(var f=0;f<b.length;f++){var e=b[g],r=b[f];if(null==this.modules[e][r])for(var a=-2;2>=a;a++)for(var c=-2;2>=c;c++)this.modules[e+a][r+c]=-2==a||2==a||-2==c||2==c||0==a&&0==c?!0:!1}},setupTypeNumber:function(b){for(var g=p.getBCHTypeNumber(this.typeNumber),f=0;18>f;f++){var e=!b&&1==(1&g>>f);this.modules[Math.floor(f/3)][f%3+this.moduleCount-
8-3]=e}for(f=0;18>f;f++)e=!b&&1==(1&g>>f),this.modules[f%3+this.moduleCount-8-3][Math.floor(f/3)]=e},setupTypeInfo:function(b,g){for(var f=p.getBCHTypeInfo(this.errorCorrectLevel<<3|g),e=0;15>e;e++){var a=!b&&1==(1&f>>e);6>e?this.modules[e][8]=a:8>e?this.modules[e+1][8]=a:this.modules[this.moduleCount-15+e][8]=a}for(e=0;15>e;e++)a=!b&&1==(1&f>>e),8>e?this.modules[8][this.moduleCount-e-1]=a:9>e?this.modules[8][15-e-1+1]=a:this.modules[8][15-e-1]=a;this.modules[this.moduleCount-8][8]=!b},mapData:function(b,
g){for(var f=-1,e=this.moduleCount-1,a=7,c=0,d=this.moduleCount-1;0<d;d-=2)for(6==d&&d--;;){for(var h=0;2>h;h++)if(null==this.modules[e][d-h]){var k=!1;c<b.length&&(k=1==(1&b[c]>>>a));p.getMask(g,e,d-h)&&(k=!k);this.modules[e][d-h]=k;a--; -1==a&&(c++,a=7)}if(e+=f,0>e||this.moduleCount<=e){e-=f;f=-f;break}}}};l.PAD0=236;l.PAD1=17;l.createData=function(b,g,f){g=a.getRSBlocks(b,g);for(var e=new c,r=0;r<f.length;r++){var d=f[r];e.put(d.mode,4);e.put(d.getLength(),p.getLengthInBits(d.mode,b));d.write(e)}for(r=
b=0;r<g.length;r++)b+=g[r].dataCount;if(e.getLengthInBits()>8*b)throw Error("code length overflow. ("+e.getLengthInBits()+">"+8*b+")");for(e.getLengthInBits()+4<=8*b&&e.put(0,4);0!=e.getLengthInBits()%8;)e.putBit(!1);for(;!(e.getLengthInBits()>=8*b||(e.put(l.PAD0,8),e.getLengthInBits()>=8*b));)e.put(l.PAD1,8);return l.createBytes(e,g)};l.createBytes=function(b,g){for(var f=0,e=0,a=0,c=Array(g.length),d=Array(g.length),k=0;k<g.length;k++){var n=g[k].dataCount,m=g[k].totalCount-n,e=Math.max(e,n),a=
Math.max(a,m);c[k]=Array(n);for(var w=0;w<c[k].length;w++)c[k][w]=255&b.buffer[w+f];f+=n;w=p.getErrorCorrectPolynomial(m);n=(new h(c[k],w.getLength()-1)).mod(w);d[k]=Array(w.getLength()-1);for(w=0;w<d[k].length;w++)m=w+n.getLength()-d[k].length,d[k][w]=0<=m?n.get(m):0}for(w=k=0;w<g.length;w++)k+=g[w].totalCount;f=Array(k);for(w=n=0;e>w;w++)for(k=0;k<g.length;k++)w<c[k].length&&(f[n++]=c[k][w]);for(w=0;a>w;w++)for(k=0;k<g.length;k++)w<d[k].length&&(f[n++]=d[k][w]);return f};for(var n={MODE_NUMBER:1,
MODE_ALPHA_NUM:2,MODE_8BIT_BYTE:4,MODE_KANJI:8},v={L:1,M:0,Q:3,H:2},p={PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50],[6,30,54],[6,32,58],[6,34,62],[6,26,46,66],[6,26,48,70],[6,26,50,74],[6,30,54,78],[6,30,56,82],[6,30,58,86],[6,34,62,90],[6,28,50,72,94],[6,26,50,74,98],[6,30,54,78,102],[6,28,54,80,106],[6,32,58,84,110],[6,30,58,86,114],[6,34,62,90,118],[6,26,50,74,98,122],[6,30,54,78,102,126],[6,26,52,78,104,130],[6,30,56,82,108,134],[6,34,60,
86,112,138],[6,30,58,86,114,142],[6,34,62,90,118,146],[6,30,54,78,102,126,150],[6,24,50,76,102,128,154],[6,28,54,80,106,132,158],[6,32,58,84,110,136,162],[6,26,54,82,110,138,166],[6,30,58,86,114,142,170]],G15:1335,G18:7973,G15_MASK:21522,getBCHTypeInfo:function(b){for(var g=b<<10;0<=p.getBCHDigit(g)-p.getBCHDigit(p.G15);)g^=p.G15<<p.getBCHDigit(g)-p.getBCHDigit(p.G15);return(b<<10|g)^p.G15_MASK},getBCHTypeNumber:function(b){for(var g=b<<12;0<=p.getBCHDigit(g)-p.getBCHDigit(p.G18);)g^=p.G18<<p.getBCHDigit(g)-
p.getBCHDigit(p.G18);return b<<12|g},getBCHDigit:function(b){for(var g=0;0!=b;)g++,b>>>=1;return g},getPatternPosition:function(b){return p.PATTERN_POSITION_TABLE[b-1]},getMask:function(b,g,f){switch(b){case 0:return 0==(g+f)%2;case 1:return 0==g%2;case 2:return 0==f%3;case 3:return 0==(g+f)%3;case 4:return 0==(Math.floor(g/2)+Math.floor(f/3))%2;case 5:return 0==g*f%2+g*f%3;case 6:return 0==(g*f%2+g*f%3)%2;case 7:return 0==(g*f%3+(g+f)%2)%2;default:throw Error("bad maskPattern:"+b);}},getErrorCorrectPolynomial:function(b){for(var g=
new h([1],0),f=0;b>f;f++)g=g.multiply(new h([1,m.gexp(f)],0));return g},getLengthInBits:function(b,g){if(1<=g&&10>g)switch(b){case n.MODE_NUMBER:return 10;case n.MODE_ALPHA_NUM:return 9;case n.MODE_8BIT_BYTE:return 8;case n.MODE_KANJI:return 8;default:throw Error("mode:"+b);}else if(27>g)switch(b){case n.MODE_NUMBER:return 12;case n.MODE_ALPHA_NUM:return 11;case n.MODE_8BIT_BYTE:return 16;case n.MODE_KANJI:return 10;default:throw Error("mode:"+b);}else{if(!(41>g))throw Error("type:"+g);switch(b){case n.MODE_NUMBER:return 14;
case n.MODE_ALPHA_NUM:return 13;case n.MODE_8BIT_BYTE:return 16;case n.MODE_KANJI:return 12;default:throw Error("mode:"+b);}}},getLostPoint:function(b){for(var g=b.getModuleCount(),f=0,e=0;g>e;e++)for(var a=0;g>a;a++){for(var c=0,d=b.isDark(e,a),k=-1;1>=k;k++)if(!(0>e+k||e+k>=g))for(var h=-1;1>=h;h++)0>a+h||a+h>=g||(0!=k||0!=h)&&d==b.isDark(e+k,a+h)&&c++;5<c&&(f+=3+c-5)}for(e=0;g-1>e;e++)for(a=0;g-1>a;a++)c=0,b.isDark(e,a)&&c++,b.isDark(e+1,a)&&c++,b.isDark(e,a+1)&&c++,b.isDark(e+1,a+1)&&c++,0!=c&&
4!=c||(f+=3);for(e=0;g>e;e++)for(a=0;g-6>a;a++)b.isDark(e,a)&&!b.isDark(e,a+1)&&b.isDark(e,a+2)&&b.isDark(e,a+3)&&b.isDark(e,a+4)&&!b.isDark(e,a+5)&&b.isDark(e,a+6)&&(f+=40);for(a=0;g>a;a++)for(e=0;g-6>e;e++)b.isDark(e,a)&&!b.isDark(e+1,a)&&b.isDark(e+2,a)&&b.isDark(e+3,a)&&b.isDark(e+4,a)&&!b.isDark(e+5,a)&&b.isDark(e+6,a)&&(f+=40);for(a=c=0;g>a;a++)for(e=0;g>e;e++)b.isDark(e,a)&&c++;return f+Math.abs(100*c/g/g-50)/5*10}},m={glog:function(b){if(1>b)throw Error("glog("+b+")");return m.LOG_TABLE[b]},
gexp:function(b){for(;0>b;)b+=255;for(;256<=b;)b-=255;return m.EXP_TABLE[b]},EXP_TABLE:Array(256),LOG_TABLE:Array(256)},q=0;8>q;q++)m.EXP_TABLE[q]=1<<q;for(q=8;256>q;q++)m.EXP_TABLE[q]=m.EXP_TABLE[q-4]^m.EXP_TABLE[q-5]^m.EXP_TABLE[q-6]^m.EXP_TABLE[q-8];for(q=0;255>q;q++)m.LOG_TABLE[m.EXP_TABLE[q]]=q;h.prototype={get:function(b){return this.num[b]},getLength:function(){return this.num.length},multiply:function(b){for(var a=Array(this.getLength()+b.getLength()-1),f=0;f<this.getLength();f++)for(var e=
0;e<b.getLength();e++)a[f+e]^=m.gexp(m.glog(this.get(f))+m.glog(b.get(e)));return new h(a,0)},mod:function(b){if(0>this.getLength()-b.getLength())return this;for(var a=m.glog(this.get(0))-m.glog(b.get(0)),f=Array(this.getLength()),e=0;e<this.getLength();e++)f[e]=this.get(e);for(e=0;e<b.getLength();e++)f[e]^=m.gexp(m.glog(b.get(e))+a);return(new h(f,0)).mod(b)}};a.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[2,35,17],[2,35,13],
[1,100,80],[2,50,32],[2,50,24],[4,25,9],[1,134,108],[2,67,43],[2,33,15,2,34,16],[2,33,11,2,34,12],[2,86,68],[4,43,27],[4,43,19],[4,43,15],[2,98,78],[4,49,31],[2,32,14,4,33,15],[4,39,13,1,40,14],[2,121,97],[2,60,38,2,61,39],[4,40,18,2,41,19],[4,40,14,2,41,15],[2,146,116],[3,58,36,2,59,37],[4,36,16,4,37,17],[4,36,12,4,37,13],[2,86,68,2,87,69],[4,69,43,1,70,44],[6,43,19,2,44,20],[6,43,15,2,44,16],[4,101,81],[1,80,50,4,81,51],[4,50,22,4,51,23],[3,36,12,8,37,13],[2,116,92,2,117,93],[6,58,36,2,59,37],[4,
46,20,6,47,21],[7,42,14,4,43,15],[4,133,107],[8,59,37,1,60,38],[8,44,20,4,45,21],[12,33,11,4,34,12],[3,145,115,1,146,116],[4,64,40,5,65,41],[11,36,16,5,37,17],[11,36,12,5,37,13],[5,109,87,1,110,88],[5,65,41,5,66,42],[5,54,24,7,55,25],[11,36,12],[5,122,98,1,123,99],[7,73,45,3,74,46],[15,43,19,2,44,20],[3,45,15,13,46,16],[1,135,107,5,136,108],[10,74,46,1,75,47],[1,50,22,15,51,23],[2,42,14,17,43,15],[5,150,120,1,151,121],[9,69,43,4,70,44],[17,50,22,1,51,23],[2,42,14,19,43,15],[3,141,113,4,142,114],[3,
70,44,11,71,45],[17,47,21,4,48,22],[9,39,13,16,40,14],[3,135,107,5,136,108],[3,67,41,13,68,42],[15,54,24,5,55,25],[15,43,15,10,44,16],[4,144,116,4,145,117],[17,68,42],[17,50,22,6,51,23],[19,46,16,6,47,17],[2,139,111,7,140,112],[17,74,46],[7,54,24,16,55,25],[34,37,13],[4,151,121,5,152,122],[4,75,47,14,76,48],[11,54,24,14,55,25],[16,45,15,14,46,16],[6,147,117,4,148,118],[6,73,45,14,74,46],[11,54,24,16,55,25],[30,46,16,2,47,17],[8,132,106,4,133,107],[8,75,47,13,76,48],[7,54,24,22,55,25],[22,45,15,13,
46,16],[10,142,114,2,143,115],[19,74,46,4,75,47],[28,50,22,6,51,23],[33,46,16,4,47,17],[8,152,122,4,153,123],[22,73,45,3,74,46],[8,53,23,26,54,24],[12,45,15,28,46,16],[3,147,117,10,148,118],[3,73,45,23,74,46],[4,54,24,31,55,25],[11,45,15,31,46,16],[7,146,116,7,147,117],[21,73,45,7,74,46],[1,53,23,37,54,24],[19,45,15,26,46,16],[5,145,115,10,146,116],[19,75,47,10,76,48],[15,54,24,25,55,25],[23,45,15,25,46,16],[13,145,115,3,146,116],[2,74,46,29,75,47],[42,54,24,1,55,25],[23,45,15,28,46,16],[17,145,115],
[10,74,46,23,75,47],[10,54,24,35,55,25],[19,45,15,35,46,16],[17,145,115,1,146,116],[14,74,46,21,75,47],[29,54,24,19,55,25],[11,45,15,46,46,16],[13,145,115,6,146,116],[14,74,46,23,75,47],[44,54,24,7,55,25],[59,46,16,1,47,17],[12,151,121,7,152,122],[12,75,47,26,76,48],[39,54,24,14,55,25],[22,45,15,41,46,16],[6,151,121,14,152,122],[6,75,47,34,76,48],[46,54,24,10,55,25],[2,45,15,64,46,16],[17,152,122,4,153,123],[29,74,46,14,75,47],[49,54,24,10,55,25],[24,45,15,46,46,16],[4,152,122,18,153,123],[13,74,
46,32,75,47],[48,54,24,14,55,25],[42,45,15,32,46,16],[20,147,117,4,148,118],[40,75,47,7,76,48],[43,54,24,22,55,25],[10,45,15,67,46,16],[19,148,118,6,149,119],[18,75,47,31,76,48],[34,54,24,34,55,25],[20,45,15,61,46,16]];a.getRSBlocks=function(b,g){var f=a.getRsBlockTable(b,g);if(void 0==f)throw Error("bad rs block @ typeNumber:"+b+"/errorCorrectLevel:"+g);for(var e=f.length/3,c=[],d=0;e>d;d++)for(var k=f[3*d+0],h=f[3*d+1],n=f[3*d+2],m=0;k>m;m++)c.push(new a(h,n));return c};a.getRsBlockTable=function(b,
g){switch(g){case v.L:return a.RS_BLOCK_TABLE[4*(b-1)+0];case v.M:return a.RS_BLOCK_TABLE[4*(b-1)+1];case v.Q:return a.RS_BLOCK_TABLE[4*(b-1)+2];case v.H:return a.RS_BLOCK_TABLE[4*(b-1)+3]}};c.prototype={get:function(b){return 1==(1&this.buffer[Math.floor(b/8)]>>>7-b%8)},put:function(b,a){for(var f=0;a>f;f++)this.putBit(1==(1&b>>>a-f-1))},getLengthInBits:function(){return this.length},putBit:function(b){var a=Math.floor(this.length/8);this.buffer.length<=a&&this.buffer.push(0);b&&(this.buffer[a]|=
128>>>this.length%8);this.length++}};var u=[[17,14,11,7],[32,26,20,14],[53,42,32,24],[78,62,46,34],[106,84,60,44],[134,106,74,58],[154,122,86,64],[192,152,108,84],[230,180,130,98],[271,213,151,119],[321,251,177,137],[367,287,203,155],[425,331,241,177],[458,362,258,194],[520,412,292,220],[586,450,322,250],[644,504,364,280],[718,560,394,310],[792,624,442,338],[858,666,482,382],[929,711,509,403],[1003,779,565,439],[1091,857,611,461],[1171,911,661,511],[1273,997,715,535],[1367,1059,751,593],[1465,1125,
805,625],[1528,1190,868,658],[1628,1264,908,698],[1732,1370,982,742],[1840,1452,1030,790],[1952,1538,1112,842],[2068,1628,1168,898],[2188,1722,1228,958],[2303,1809,1283,983],[2431,1911,1351,1051],[2563,1989,1423,1093],[2699,2099,1499,1139],[2809,2213,1579,1219],[2953,2331,1663,1273]],q=function(){var b=function(b,a){this._el=b;this._htOption=a};return b.prototype.draw=function(b){function a(b,a){var e=document.createElementNS("http://www.w3.org/2000/svg",b),f;for(f in a)a.hasOwnProperty(f)&&e.setAttribute(f,
a[f]);return e}var e=this._htOption,g=this._el,c=b.getModuleCount();Math.floor(e.width/c);Math.floor(e.height/c);this.clear();var d=a("svg",{viewBox:"0 0 "+String(c)+" "+String(c),width:"100%",height:"100%",fill:e.colorLight});d.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:xlink","http://www.w3.org/1999/xlink");g.appendChild(d);d.appendChild(a("rect",{fill:e.colorDark,width:"1",height:"1",id:"template"}));for(e=0;c>e;e++)for(g=0;c>g;g++)if(b.isDark(e,g)){var k=a("use",{x:String(e),y:String(g)});
k.setAttributeNS("http://www.w3.org/1999/xlink","href","#template");d.appendChild(k)}},b.prototype.clear=function(){for(;this._el.hasChildNodes();)this._el.removeChild(this._el.lastChild)},b}(),x="svg"===document.documentElement.tagName.toLowerCase()?q:"undefined"!=typeof CanvasRenderingContext2D?function(){function b(){this._elImage.src=this._elCanvas.toDataURL("image/png");this._elImage.style.display="block";this._elCanvas.style.display="none"}function a(b,a){var e=this;if(e._fFail=a,e._fSuccess=
b,null===e._bSupportDataURI){var f=document.createElement("img"),g=function(){e._bSupportDataURI=!1;e._fFail&&_fFail.call(e)};return f.onabort=g,f.onerror=g,f.onload=function(){e._bSupportDataURI=!0;e._fSuccess&&e._fSuccess.call(e)},f.src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==",void 0}!0===e._bSupportDataURI&&e._fSuccess?e._fSuccess.call(e):!1===e._bSupportDataURI&&e._fFail&&e._fFail.call(e)}if(this._android&&
2.1>=this._android){var f=1/window.devicePixelRatio,e=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(b,a,g,c,d,k,h,n){if("nodeName"in b&&/img/i.test(b.nodeName))for(var w=arguments.length-1;1<=w;w--)arguments[w]*=f;else"undefined"==typeof n&&(arguments[1]*=f,arguments[2]*=f,arguments[3]*=f,arguments[4]*=f);e.apply(this,arguments)}}var c=function(b,a){this._bIsPainted=!1;this._android=k();this._htOption=a;this._elCanvas=document.createElement("canvas");
this._elCanvas.width=a.width;this._elCanvas.height=a.height;b.appendChild(this._elCanvas);this._el=b;this._oContext=this._elCanvas.getContext("2d");this._bIsPainted=!1;this._elImage=document.createElement("img");this._elImage.style.display="none";this._el.appendChild(this._elImage);this._bSupportDataURI=null};return c.prototype.draw=function(b){var a=this._elImage,e=this._oContext,f=this._htOption,g=b.getModuleCount(),c=f.width/g,d=f.height/g,k=Math.round(c),h=Math.round(d);a.style.display="none";
this.clear();for(a=0;g>a;a++)for(var n=0;g>n;n++){var m=b.isDark(a,n),r=n*c,l=a*d;e.strokeStyle=m?f.colorDark:f.colorLight;e.lineWidth=1;e.fillStyle=m?f.colorDark:f.colorLight;e.fillRect(r,l,c,d);e.strokeRect(Math.floor(r)+.5,Math.floor(l)+.5,k,h);e.strokeRect(Math.ceil(r)-.5,Math.ceil(l)-.5,k,h)}this._bIsPainted=!0},c.prototype.makeImage=function(){this._bIsPainted&&a.call(this,b)},c.prototype.isPainted=function(){return this._bIsPainted},c.prototype.clear=function(){this._oContext.clearRect(0,0,
this._elCanvas.width,this._elCanvas.height);this._bIsPainted=!1},c.prototype.round=function(b){return b?Math.floor(1E3*b)/1E3:b},c}():function(){var b=function(b,a){this._el=b;this._htOption=a};return b.prototype.draw=function(b){for(var a=this._htOption,e=this._el,c=b.getModuleCount(),g=Math.floor(a.width/c),d=Math.floor(a.height/c),k=['<table style="border:0;border-collapse:collapse;">'],h=0;c>h;h++){k.push("<tr>");for(var n=0;c>n;n++)k.push('<td style="border:0;border-collapse:collapse;padding:0;margin:0;width:'+
g+"px;height:"+d+"px;background-color:"+(b.isDark(h,n)?a.colorDark:a.colorLight)+';"></td>');k.push("</tr>")}k.push("</table>");e.innerHTML=k.join("");b=e.childNodes[0];e=(a.width-b.offsetWidth)/2;a=(a.height-b.offsetHeight)/2;0<e&&0<a&&(b.style.margin=a+"px "+e+"px")},b.prototype.clear=function(){this._el.innerHTML=""},b}();QRCode=function(b,a){if(this._htOption={width:256,height:256,typeNumber:4,colorDark:"#000000",colorLight:"#ffffff",correctLevel:v.H},"string"==typeof a&&(a={text:a}),a)for(var f in a)this._htOption[f]=
a[f];"string"==typeof b&&(b=document.getElementById(b));this._android=k();this._el=b;this._oQRCode=null;this._oDrawing=new x(this._el,this._htOption);this._htOption.text&&this.makeCode(this._htOption.text)};QRCode.prototype.makeCode=function(b){var a=this._htOption.correctLevel,f=1,e;e=encodeURI(b).toString().replace(/\%[0-9a-fA-F]{2}/g,"a");e=e.length+(e.length!=b?3:0);for(var c=0,d=u.length;d>=c;c++){var k=0;switch(a){case v.L:k=u[c][0];break;case v.M:k=u[c][1];break;case v.Q:k=u[c][2];break;case v.H:k=
u[c][3]}if(k>=e)break;f++}if(f>u.length)throw Error("Too long data");this._oQRCode=new l(f,this._htOption.correctLevel);this._oQRCode.addData(b);this._oQRCode.make();this._el.title=b;this._oDrawing.draw(this._oQRCode);this.makeImage()};QRCode.prototype.makeImage=function(){"function"==typeof this._oDrawing.makeImage&&(!this._android||3<=this._android)&&this._oDrawing.makeImage()};QRCode.prototype.clear=function(){this._oDrawing.clear()};QRCode.CorrectLevel=v}();
function SharingManager(d,l){function h(){k.classList.remove("hidden")}function a(){k.classList.add("hidden");n&&n()}function c(c){if("more"==c.target.id)for(c=0;c<v.length;c++){var b=v[c];"more"==b.id?b.classList.add("hidden"):b.classList.remove("hidden")}else"qr"==c.target.id?qrElement.classList.toggle("hidden"):("mail"==c.target.id?window.location.href="mailto:?subject="+encodeURIComponent(q)+"&body="+encodeURIComponent(m):"link"==c.target.id?(copyElement.classList.remove("hidden"),copyElement.value=
m,copyElement.select(),document.execCommand("copy"),copyElement.classList.add("hidden")):(c=u[c.target.id].replace("URL",encodeURIComponent(m)).replace("DESCRIPTION",encodeURIComponent(q)),window.open(c,"sharing...","top="+(screen.height/2-175)+",left="+(screen.width/2-260)+",toolbar=0,status=0,width=520,height=350")),a())}var k=d,n=void 0===l?null:l,v=null,p="a"+Math.random(),m="",q="",u={qq:"http://v.t.qq.com/share/share.php?url=URL&title=DESCRIPTION",weibo:"http://service.weibo.com/share/share.php?url=URL&title=DESCRIPTION",
qzone:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=URL&title=DESCRIPTION",facebook:"https://www.facebook.com/sharer/sharer.php?u=URL&t=DESCRIPTION",twitter:"https://twitter.com/intent/tweet?text=DESCRIPTION&url=URL&via=ScalesEscort"};(function(){k.classList.add("sharingManager");k.innerHTML='<div id="icons">  <div id="facebook" class="icon"></div>  <div id="twitter" class="icon"></div>  <div id="weibo" class="icon"></div><div id="qzone" class="icon"></div>    <div id="mail" class="icon"></div>  <div id="qr" class="icon"></div>  <div id="link" class="icon"></div>  <div id="more" class="icon"></div></div><div id="'+
p+'" class="qr hidden"></div><input id="copy" class="hidden"/>';qrElement=k.querySelector("div.qr");copyElement=k.querySelector("input#copy");v=[];for(var a=k.querySelectorAll("div.icon"),b=0;b<a.length;b++)v.push(a[b]);for(b=0;b<v.length;b++)a=v[b],a.addEventListener("click",c),0<=["zh-cn","zh"].indexOf(window.navigator.language)?0<=["facebook","twitter"].indexOf(a.id)&&a.classList.add("hidden"):0<=["weibo","qq","qzone"].indexOf(a.id)&&a.classList.add("hidden")})();return{isDisplayed:function(){return!k.classList.contains("hidden")},
display:h,hide:a,share:function(a,b){m=a;q=b;qrElement.innerHTML="";new QRCode(p,{text:m,width:256,height:256,colorDark:"#000000",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H});h()}}}
var encoder=function(){function d(a,c){c=void 0===c?h:c;if(a<c.base.length)return c.base[a];if(a<c.base.length*(c.extra.length+1))return c.extra[Math.floor(a/c.base.length)-1]+c.base[a%c.base.length];for(var d=c.extraExtra;;){if(a<c.base.length){d+=c.base[a];break}d+=c.base[a%c.base.length];a=Math.floor(a/c.base.length)}return d+c.extraExtra}function l(a,c,d){d=void 0===d?h:d;var k={};if(c>=a.length)return null;if(0<=d.base.indexOf(a[c])){var l=d.base.indexOf(a[c]);if(0>l)return null;k.value=l;k.end=
c+1}else if(0<=d.extra.indexOf(a[c])){if(c==a.lengt-1)return null;l=d.extra.indexOf(a[c])+1;a=d.base.indexOf(a[c+1]);if(0>=l||0>a)return null;k.value=l*d.base.length+a;k.end=c+2}else if(d.extraExtra==a[c]){var p=c+1,m=a.indexOf(d.extraExtra,p);if(m<=p)return null;l=d.base.indexOf(a[m-1]);if(0>l)return null;for(var q=m-2;q>=p;q--){var u=d.base.indexOf(a[q]);if(0>u)return null;l=l*d.base.length+u}k.value=l;k.end=c+m-p+2}c=[];for(var x in k)k.hasOwnProperty(x)&&c.push(x);return 0==c.length?null:k}var h=
{base:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",extra:"0123456789-.",extraExtra:"_",reserved:"~"};return{encodeInt:d,decodeInt:l,encodeIntArray:function(a,c){c=void 0===c?h:c;for(var k="",n=0;n<a.length;n++)k+=d(a[n],c);return k},decodeIntArray:function(a,c){c=void 0===c?h:c;for(var d=[],n=0;n<a.length;){n=l(a,n,c);if(null==n)return null;d.push(n.value);n=n.end}return d},URLIntCodingParams:h}}(),ConfigManager=function(){function d(a){for(var c=a.name,d="",h=0;h<a.sequences.length;h++)var l=
a.sequences[h],p=a[l],c=c+("~"+l),d=d+("~"+encoder.encodeIntArray(p.beats.concat(p.repeats)));return"?n="+c+"&v="+d.substring(1)}function l(a){if(null==a)return null;var c={},d=a.indexOf("?n="),h=a.indexOf("&v=");if(0!=d||0>h)return null;d=a.substring(3,h).split("~");if(1>d.length)return null;c.name=d[0];d.splice(0,1);c.sequences=d;var l=d.length;a=a.substring(h+3).split("~");if(a.length<l)return null;for(h=0;h<l;h++){var p=encoder.decodeIntArray(a[h]),m=p&&p.length||0;if(0>=m)return null;var q={};
q.repeats=p[m-1];p.splice(m-1,1);q.beats=p;c[d[h]]=q}return c}function h(){return{name:"Untitled",sequences:["S1"],S1:{beats:[60],repeats:1}}}return{clone:function(a){return l(d(a))},toString:d,fromString:l,isEmptyConfig:function(a){return d(a)==d(h())},isKnownConfig:function(a){var c=d(a);if(localStorage.getItem("~config~"+a.name)==c||d(a)==d(h()))return"~exact";c=c.substring(c.indexOf("&v="));for(a=0;a<localStorage.length;a++){var k=localStorage.key(a);if(0==k.indexOf("~config~")){var l=localStorage.getItem(k);
if(c==l.substring(l.indexOf("&v=")))return k.substring(8)}}return"~unknown"},getConfigByName:function(a){return l(localStorage.getItem("~config~"+a))||h()},setLastConfig:function(a){localStorage.setItem("~lastConfig",a.name)},getLastConfig:function(){var a=localStorage.getItem("~lastConfig");return null==a?null:l(localStorage.getItem("~config~"+a))},getEmptyConfig:h,getAllConfigNames:function(){for(var a=[],c=0;c<localStorage.length;c++){var d=localStorage.key(c);0==d.indexOf("~config~")&&a.push(d.substring(8))}return a},
save:function(a){localStorage.setItem("~config~"+a.name,d(a))},discard:function(a){localStorage.removeItem("~config~"+a.name)}}}(),Player=function(){function d(c,d){var k=new XMLHttpRequest;k.open("GET",c,!0);k.responseType="arraybuffer";k.onload=function(){h.decodeAudioData(k.response,function(c){a[d]=c})};k.send()}function l(a){if(null===a)return!1;var c=h.createBufferSource();c.buffer=a;c.connect(h.destination);c.start(0);return!0}var h=null,a={first:null,other:null};return{initialize:function(){window.AudioContext=
window.AudioContext||window.webkitAudioContext;h=new AudioContext;d("/sound/first.wav","first");d("/sound/other.wav","other")},playFirst:function(){return l(a.first)},playOther:function(){return l(a.other)}}}(),BlinkingBackgroundAnimator=function(){function d(){"blinking"!=p||v>k?(l.style.backgroundColor=h,p="idle"):(l.style.backgroundColor="hsl("+a+","+c+"%,"+100*(.2+v/k*.8)+"%)",v+=1,setTimeout(d,n))}var l=null,h=0,a="100",c="0",k=10,n=20,v=0,p="idle";return{start:function(m,q,u,x,b){if("idle"!=
p)return!1;p="blinking";l=m;h=l.style.backgroundColor;a=void 0===q?"120":q;c=void 0===u?"100":u;k=void 0===x?10:x;n=void 0===b?20:b;v=0;d();return!0}}}();
function TabManager(d,l,h,a,c,k,n){function v(a){var b=a.target.value.trim(),e=r.childNodes[f],c=B.childNodes[f];""==b?(a=a.target.parentNode,a=Array.from(r.childNodes).indexOf(a),E&&E(a),r.removeChild(e),B.removeChild(c),g>a&&--g,u(g)):(null!=K&&(b=K(f,b,a.target.getAttribute("original"))),e.innerHTML=b)}function p(a,b){a.innerHTML='<input id="tabName" placeholder="Tab Name"></input>';var e=a.querySelector("input#tabName");e.setAttribute("original",b);e.value=b;e.focus();e.addEventListener("blur",
v)}function m(a){var b=r.childNodes.length-1,c=document.createElement("div");c.classList.add("tab");c.innerHTML=a;r.insertBefore(c,e);a=document.createElement("div");a.classList.add("content");B.appendChild(a);u(b);null!=P&&P(b);""==c.innerHTML.trim()&&p(c,"");c.addEventListener("click",function(a){a=a.target;a=Array.from(r.childNodes).indexOf(a);a==f?(a=r.childNodes[a],p(a,a.innerHTML)):u(a)})}function q(a,b){return 0<=a&&a<r.childNodes.length?(r.childNodes[a].innerHTML=b,!0):!1}function u(a){void 0===
r.childNodes[a]||a>=r.childNodes.length-1||(null!=M&&g!=a&&M(g,a),g=f,g<r.childNodes.length-1&&(r.childNodes[g].classList.remove("active"),B.childNodes[g].classList.add("hidden")),f=a,r.childNodes[f].classList.add("active"),B.childNodes[f].classList.remove("hidden"))}function x(a){0<=a&&a<r.childNodes.length-1&&(r.removeChild(r.childNodes[a]),B.removeChild(B.childNodes[a]),E&&E(a))}l=void 0===l?[]:l;h=void 0===h?[]:h;var b=Math.random(),g=0,f=0,e=null,r=null,B=null,P=void 0===a?null:a,E=void 0===
c?null:c,M=void 0===k?null:k,K=void 0===n?null:n;(function(a,b){d.classList.add("TabManager");for(var c=0;c<b.length;c++)d.classList.add(b[c]);d.innerHTML='<div id="tabs"><div id="newTab"></div></div><div class="clearBoth"></div><div id="contents"></div>';r=d.querySelector("div#tabs");B=d.querySelector("div#contents");for(c=0;c<a.length;c++)m(a[c]);e=d.querySelector("div#tabs > div#newTab");e.addEventListener("click",function(){m("")});u(0)})(l,h);return{id:b,getTabElement:function(a){return 0<=a&&
a<r.childNodes.length-1?r.childNodes[a]:null},getContentElement:function(a){return 0<=a&&a<B.childNodes.length?B.childNodes[a]:null},setActiveTabName:function(a){q(f,a)},setTabName:q,getTabName:function(a){return 0<=a&&a<r.childNodes.length?r.childNodes[a].innerHTML:null},getAllTabNames:function(){for(var a=[],b=0;b<r.childNodes.length-1;b++)a.push(r.childNodes[b].innerHTML);return a},addTab:function(a){m(a)},resize:function(a,b){d.style.width=a+"px";d.style.height=(void 0===b?32:b)+"px"},setActiveTab:u,
removeTab:x,removeAllTabs:function(){for(var a=r.childNodes.length-1;0<=a;a--)x(a)}}}
function Slider(d,l,h){function a(){var a=k.getBoundingClientRect(),b=v.getBoundingClientRect(),c=p.getBoundingClientRect(),d=m.getBoundingClientRect(),e=a.left,h=a.right-d.width;v.style.top=.5*(a.height-b.height)+"px";v.style.left="0px";p.style.top=.5*(a.height-c.height)-b.height+"px";p.style.left="0px";m.style.top=.5*(a.height-d.height)-b.height-c.height+"px";m.style.left=e+(h-e)*u+"px"}function c(a){var b=k.getBoundingClientRect(),c=m.getBoundingClientRect(),d=b.right-c.width;a>d&&(a=d);a<b.left&&
(a=b.left);m.style.left=a-b.left+"px";d=b.left;u=(a-d)/(b.right-c.width-d);null!=n&&n(u)}var k=d,n=l,v=null,p=null,m=null,q=!1,u=0;(function(){k.classList.add("Slider");k.ondragstart=function(){return!1};k.ondrop=function(){return!1};k.innerHTML='<div id="hiddenSlide"></div><div id="slide"></div><div id="knob"></div>';v=k.querySelector("div#hiddenSlide");p=k.querySelector("div#slide");m=k.querySelector("div#knob");var d="mousedown",b="mousemove",g="mouseup";"ontouchstart"in window&&(d="touchstart",
b="touchmove",g="touchend");m.addEventListener(d,function(){event.preventDefault();q=!0;m.classList.add("activated")});document.body.addEventListener(g,function(a){q&&(a.preventDefault(),c("touchend"===a.type?a.changedTouches[0].clientX:a.clientX),"function"==typeof h&&h(),q=!1,m.classList.remove("activated"))});document.body.addEventListener(b,function(a){q&&(a.preventDefault(),c("touchmove"===a.type?a.changedTouches[0].clientX:a.clientX))});v.addEventListener("click",function(a){c(a.clientX);h&&
h()});a()})();return{set:function(a){u=1<a?1:0>a?0:a;a=k.getBoundingClientRect();var b=m.getBoundingClientRect();m.style.left=(a.right-b.width-a.left)*u+"px"}}}
function SequenceManager(d,l,h){function a(a){m.beats.splice(a,1)}function c(){q()}function k(a,b,c){b=parseInt(b);if(20<=b&&300>=b)return e.set((b-20)/280),m.beats[a]=b,b!=parseInt(c)&&q(),a,""+b;Toast.show("A valid beat is a number between 20 and 300.");return c}function n(a){var b=60;0<a&&(b=parseInt(f.getTabName(a-1)));a<m.beats.length?b=m.beats[a]:(m.beats.push(b),q());f.setTabName(a,""+b);e.set((b-20)/280)}function v(a,b){var c=f.getTabName(b),c=(parseInt(c)-20)/280;e.set(c)}function p(a){f.setActiveTabName(""+
Math.floor(280*a+20))}var m=l,q=h,u=null,x=null,b=null,g=null,f=null,e=null;(function(){d.classList.add("SequenceManager");d.innerHTML='<div id="beats">beats</div><div id="value"></div><div id="repeats"><div id="repeatsLabel" class="label">Repeats (0 for indefinite): </div><input type="number" min="0" id="repeats"></input></div><div class="clearBoth"></div>';u=d.querySelector("div#beats");x=d.querySelector("div#value");b=d.querySelector("input#repeats");g=d.querySelector("div#repeatsLabel");f=new TabManager(u,
[],["sequence"],n,a,v,k);e=new Slider(x,p,c);for(var h=0;h<m.beats.length;h++)f.addTab(""+m.beats[h]);f.setActiveTab(0);b.value=""+m.repeats;b.addEventListener("input",function(){var a=parseInt(b.value);isNaN(a)||0>a?Toast.show("Repeats must be a number and it cannot be less than 0."):a!=m.repeats&&(m.repeats=a,q())})})();return{getBeatElement:function(a){return f.getTabElement(a)},setActiveBeat:function(a){f.setActiveTab(a)},setCurrentRepeat:function(a){""==a?(b.classList.remove("hidden"),g.innerHTML=
"Repeats (0 for indefinite): "):(b.classList.add("hidden"),g.innerHTML=a)}}}
var Toast=function(){var d=null;return{initialize:function(l){l=void 0===l?[]:l;d=document.createElement("div");document.body.appendChild(d);l=void 0===l?[]:l;for(var h=0;h<d.classList.length;h++){var a=d.classList.item(h);d.classList.remove(a)}for(h=0;h<l.length;h++)d.classList.add(l[h]);d.classList.add("Toast");d.classList.add("hidden")},show:function(l,h){h=void 0===h?"short":h;d.innerHTML=l;d.classList.remove("hidden");d.classList.add("show");var a=h;"short"==h?a=1500:"long"==h&&(a=3E3);setTimeout(function(){d.classList.add("hidden");
d.classList.remove("show")},a)}}}(),ModalDialog=function(){function d(){if(!a.classList.contains("hidden")){k.style.width="0px";k.style.height="0px";if(n&&"handleWindowResized"in n)n.handleWindowResized();else{var d=window.innerHeight,h=window.innerWidth,l=0,q=0,u=.75*window.innerWidth,x=window.innerHeight-16;c.style.width=u+"px";c.style.height=x+"px";for(var b=0;b<c.childNodes.length;b++)if(!c.childNodes[b].classList.contains("ignoreWhenResizing")){var g=c.childNodes[b].getBoundingClientRect();g.top<
d&&(d=g.top);g.left<h&&(h=g.left);g.bottom>l&&(l=g.bottom);g.right>q&&(q=g.right)}h=q-h;d=l-d;u>h&&(u=h);x>d&&(x=d);c.style.width=u+"px";c.style.height=x+"px";c.style.marginTop=.25*(window.innerHeight-c.offsetHeight)+"px"}k.style.width=document.body.scrollWidth+"px";k.style.height=document.body.scrollHeight+"px"}}function l(a,c){for(var d=0;d<a.classList.length;d++){var h=a.classList.item(d);a.classList.remove(h)}for(d=0;d<c.length;d++)a.classList.add(c[d])}function h(c){l(a,["ModalDialog","hidden"].concat(c))}
var a=null,c=null,k=null,n=null;return{initialize:function(l){l=void 0===l?[]:l;a=document.createElement("div");document.body.appendChild(a);a.innerHTML='<div id="content"></div><div id="overlay" class="hidden"></div>';h(l);c=a.querySelector("div#content");k=a.querySelector("div#overlay");window.addEventListener("resize",d);d()},setTheme:h,getEventHandlers:function(){return n},getContentElement:function(){return c},onWindowResized:d,show:function(h,p,m){m=void 0===m?[]:m;a.classList.contains("hidden")&&
(c.removeAttribute("style"),c.innerHTML=h,n=p,l(c,m),k.classList.remove("hidden"),a.classList.remove("hidden"),d())},hide:function(){k.classList.add("hidden");a.classList.add("hidden")}}}();
function Confirm(d,l,h){h=void 0===h?["Ok","Cancel"]:h;d='<div id="message">'+d+'</div><div id="controls">';for(var a=0;a<h.length;a++)d+='<button class="control" onclick="ModalDialog.getEventHandlers().c('+a+');" id="c'+a+'">'+h[a]+"</button>";ModalDialog.show(d+"</div>",{c:function(a){l(a);ModalDialog.hide()}},["Confirm"])}
function Prompt(d,l,h){h=void 0===h?null:h;ModalDialog.show('<div id="message" class="card">'+d+'</div><div id="inputWrapper" class="card ignoreWhenResizing"><input id="input"></input></div><div id="error" class="card"></div><div id="controls" class="card"><button class="control" onclick="ModalDialog.getEventHandlers().submit(true);" id="ok">Ok</button><button class="control" onclick="ModalDialog.getEventHandlers().submit(false);" id="cancel">Cancel</button></div>',{submit:function(a){var c=ModalDialog.getContentElement().querySelector("input#input").value;
if(a){if(h&&(a=h(c),null!=a)){ModalDialog.getContentElement().querySelector("div#error").innerHTML=a;ModalDialog.onWindowResized();return}l(c)}else l(null);ModalDialog.hide()}},["Prompt"])}
var Locale=function(){var d="en",l={en_confirmDiscardChanges:"You have made some changes. Do you want to discard them?",en_confirmDelete:"Do you want to delete this config?",en_confirmSave:"You have made changes to current config. Do you want to save it?",en_promptGiveName:"Please give a name of your config.",en_toastErrorInConfig:"Error in loading config [%s].",en_toastCannotParse:"Cannot parse [%s].",en_toastUntitledIgnored:"Config [Untitled] ignored.",en_toastRenamedToUntitled:"Config [%s] already exists. Renamed to [Untitled].",
en_toastReceivedSameConfig:"Received [%s], but it's same as [%s].",en_toastReceived:"Received [%s].",en_toastConfigNotSaved:"Config not saved.",zh_cn_confirmDiscardChanges:"cYou have made some changes. Do you want to discard them?",zh_cn_confirmDelete:"cDo you want to delete this config?",zh_cn_confirmSave:"cYou have made changes to current config. Do you want to save it?",zh_cn_propmptGiveName:"cPlease give a name of your config.",zh_cn_toastErrorInConfig:"cError in loading config [%s].",zh_cn_toastCannotParse:"cCannot parse [%s].",
zh_cn_toastUntitledIgnored:"cConfig [Untitled] ignored.",zh_cn_toastRenamedToUntitled:"cConfig [%s] already exists. Renamed to [Untitled].",zh_cn_toastReceivedSameConfig:"cReceived [%s], but it's same as [%s].",zh_cn_toastReceived:"cReceived [%s].",zh_cn_toastConfigNotSaved:"cConfig not saved.",en_errorConfigName:"cA name cannot exist already, cannot be empty or contain ~ in it.",en_errorSequenceName:"cSequence name cannot contain ~."};return{initialize:function(){0==(navigator.languages&&0<navigator.languages.length?
navigator.languages[0]:navigator.language||navigator.userLanguage).toLowerCase().indexOf("zh-cn")&&(d="zh_cn")},getLocale:function(){return d},setLocale:function(h){d=h},getString:function(){for(var h=l[d+"_"+arguments[0]].split("%s"),a="",c=0;c<Math.min(h.length-1,arguments.length-1);c++)a+=h[c]+arguments[c+1];for(;c<h.length-1;c++)a+=h[c]+"%s";return a+=h[c]}}}();
function Metronome(d){function l(){H.classList.add("gray");Q.classList.add("gray");T=ConfigManager.clone(t)}function h(){history.replaceState({from:t.name},t.name,"index.html"+ConfigManager.toString(t));H.classList.remove("gray");Q.classList.remove("gray");y.isDisplayed()&&y.hide()}function a(){y.isDisplayed()&&y.hide();Confirm('<h2>Metronome</h2>Copyright (c) <2017> yanfu2007@gmail.com<br><br>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
function(){localStorage.setItem("~licenseReadLastTime",""+(new Date).getTime())},["Ok"])}function c(a){H.classList.contains("gray")||M()}function k(a){H.classList.contains("gray")||Confirm(Locale.getString("confirmDiscardChanges"),function(a){0==a&&E(T)},["Yes","No"])}function n(a){I.classList.contains("gray")||(y.isDisplayed()&&y.hide(),Confirm(Locale.getString("confirmDelete"),function(a){0==a&&("Untitled"!=t.name&&(ConfigManager.discard(t),e()),a=ConfigManager.getEmptyConfig(),E(a),z.value="c"+
F.indexOf("Untitled"))},["Yes","No"]))}function v(){function a(){R=!0;S.classList.add("playing");D=O=G=0;C.setActiveTab(0);L.style.pointerEvents="none";u()}y.isDisplayed()&&y.hide();R?B():K(a)}function p(){function a(){var a=location.origin,b="Metronome";ConfigManager.isEmptyConfig(t)||(a=window.location.href,b=t.name);N.classList.add("shown");y.share(a,b);y.display()}y.isDisplayed()?(N.classList.remove("shown"),y.hide()):K(a)}function m(){y.isDisplayed()&&y.hide();K(function(){var a=F[parseInt(z.value.substring(1))],
b=ConfigManager.getConfigByName(a)||ConfigManager.getEmptyConfig();E(b);z.value="c"+F.indexOf(b.name);"Untitled"==b.name?(I.classList.add("gray"),z.value!="c"+F.indexOf("Untitled")&&Toast.show(Locale.get("toastErrorInConfig",a))):I.classList.remove("gray")})}function q(){z.parentNode.removeChild(z);476<=window.innerWidth?(z.classList.remove("body"),z.classList.add("header"),U.parentNode.insertBefore(z,U)):(z.classList.add("body"),z.classList.remove("header"),L.parentNode.insertBefore(z,L));var a=
A.querySelector("div#header > div#title"),b=A.querySelector("div#header > div#titleIcon");316<=window.innerWidth?(a.classList.remove("hidden"),b.classList.add("hidden")):(a.classList.add("hidden"),b.classList.remove("hidden"))}function u(){if(R){var a=J[D];if(G>=t[t.sequences[D]].beats.length&&(G=0,O+=1,0<t[t.sequences[D]].repeats&&O>=t[t.sequences[D]].repeats)){a.setActiveBeat(0);O=0;D+=1;if(D>=t.sequences.length){B();return}a=J[D];C.setActiveTab(D)}var b=60/t[t.sequences[D]].beats[G];0==G?Player.playFirst():
Player.playOther();setTimeout(u,1E3*b);a.setActiveBeat(G);a.setCurrentRepeat("Current repeat: "+(O+1)+"/"+t[t.sequences[D]].repeats);BlinkingBackgroundAnimator.start(a.getBeatElement(G));G+=1}}function x(a){var b;b=a<t.sequences.length?t[t.sequences[a]]:{beats:[60],repeats:1};var c=new SequenceManager(C.getContentElement(a),b,h);J.push(c);""==C.getTabName(a).trim()&&C.setTabName(a,w("S"+(a+1)));a>=t.sequences.length&&(a=C.getTabName(a),t.sequences.push(a),t[a]=b,h())}function b(a){J.splice(a,1);t.sequences.splice(a,
1);h()}function g(a,b){}function f(a,b,c){if(0<=b.indexOf("~"))return Toast.show(Locale.getString("errorSequenceName")),c;if(b==c)return b;t.sequences[a]=b;t[b]=t[c];delete t[c];h();return b}function e(){F=[];for(var a=ConfigManager.getAllConfigNames().concat("Untitled"),b="",c=0;c<a.length;c++)F.push(a[c]),b+='<option value="c'+F.indexOf(a[c])+'">'+a[c]+"</option>";z.innerHTML=b}function r(){A.classList.add("Metronome");A.innerHTML='<div id="header"><div id="title">Metronome</div><div id="titleIcon" class="hidden"></div><div id="controls"><div id="icons"><div class="icon" id="save"></div><div class="icon" id="discard"></div><div class="icon" id="delete"></div><div class="icon" id="share"></div><div class="icon" id="playstop"></div></div></div></div><div class="clearBoth"></div><div id="sequences"></div><select id="configSelector"><option value="Untitled">Untitled</option></select><div id="sharing"></div>';
L=A.querySelector("div#sequences");C=new TabManager(L,[],[],x,b,g,f);U=A.querySelector("div#icons");H=A.querySelector("div#save");Q=A.querySelector("div#discard");I=A.querySelector("div#delete");N=A.querySelector("div#share");S=A.querySelector("div#playstop");z=A.querySelector("select#configSelector");y=new SharingManager(A.querySelector("div#sharing"),function(){N.classList.remove("shown")});y.hide();A.querySelector("div#title").addEventListener("click",a);A.querySelector("div#titleIcon").addEventListener("click",
a);H.addEventListener("click",c);Q.addEventListener("click",k);I.addEventListener("click",n);N.addEventListener("click",p);S.addEventListener("click",v);z.addEventListener("change",m);window.addEventListener("resize",q);q()}function B(){R=!1;S.classList.remove("playing");J[0].setActiveBeat(0);C.setActiveTab(0);L.style.pointerEvents="auto";for(var a=0;a<J.length;a++)J[a].setCurrentRepeat("")}function P(){var a=ConfigManager.fromString(window.location.search);if(null==a)return""!=window.location.search.trim()&&
Toast.show(Locale.getString("toastCannotParse",window.location.search)),null;if("Untitled"==a.name)return Toast.show(Locale.getString("toastUntitledIgnored")),null;var b=ConfigManager.isKnownConfig(a);"~exact"!=b&&("~unknown"==b?0<=ConfigManager.getAllConfigNames().indexOf(a.name)?(Toast.show(Locale.getString("toastRenamedToUntitled",a.name)),a.name="Untitled"):(Toast.show(Locale.getString("toastReceived",a.name)),ConfigManager.save(a),e()):(Toast.show(Locale.getString("toastReceivedSameConfig",a.name,
b)),a=ConfigManager.getConfigByName(b)));return a}function E(a){var b=t.name;C.removeAllTabs();t=a;for(a=0;a<t.sequences.length;a++)C.addTab(t.sequences[a]);C.setActiveTab(0);history.replaceState({from:b},t.name,"index.html"+ConfigManager.toString(t));l()}function M(){if("Untitled"==t.name){var a=ConfigManager.getAllConfigNames().concat("Untitled");Prompt(Locale.getString("promptGiveName"),function(a){null!=a?(t.name=a,ConfigManager.save(t),ConfigManager.setLastConfig(t),e(),l(),history.replaceState({from:"Untitled"},
t.name,"index.html"+ConfigManager.toString(t))):Toast.show(Locale.getString("toastConfigNotSaved"))},function(b){return null==b||""!=b.trim()&&0>b.indexOf("~")&&0>a.indexOf(b)?null:Locale.getString("errorConfigName")})}else ConfigManager.save(t),l()}function K(a,b,c){a=void 0===a?null:a;b=void 0===b?a:b;c=void 0===c?a:c;H.classList.contains("gray")?a&&a():Confirm(Locale.getString("confirmSave"),function(a){0==a?(M(),b&&b()):(E(T),c&&c())},["Yes","No"])}function w(a){var b=C.getAllTabNames();if(0>
b.indexOf(a))return a;a+="-";for(var c=1;0<=b.indexOf(a+c);c++);return a+c}var A=d,L=null,C=null,H=null,Q=null,I=null,N=null,S=null,U=null,z=null,y=null,F=null,J=[],t=ConfigManager.getEmptyConfig(),T=ConfigManager.getEmptyConfig(),G=0,O=0,D=0,R=!1;(function(){Locale.initialize();ModalDialog.initialize();Toast.initialize();Player.initialize();r();var a=P()||ConfigManager.getLastConfig()||ConfigManager.getEmptyConfig();E(a);"Untitled"==a.name?(I.classList.add("gray"),ConfigManager.isEmptyConfig(a)||
h()):I.classList.remove("gray");e();z.value="c"+F.indexOf(a.name)})();return{}}
var App=function(){function d(){var d="mousedown",h="mousemove",a="mouseup";"ontouchstart"in window&&(d="touchstart",h="touchmove",a="touchend");document.body.addEventListener(d,function(){event.stopPropagation()});document.body.addEventListener(a,function(a){a.stopPropagation()});document.body.addEventListener(h,function(a){a.stopPropagation()})}return{initialize:function(){document.querySelector("body").innerHTML='<div id="metronome"></div>';new Metronome(document.querySelector("div#metronome"));
d()}}}();
//---------------------------------------------------------------------
// QRCode for JavaScript
//
// Copyright (c) 2009 Kazuhiko Arase
//
// URL: http://www.d-project.com/
//
// Licensed under the MIT license:
//   http://www.opensource.org/licenses/mit-license.php
//
// The word "QR Code" is registered trademark of 
// DENSO WAVE INCORPORATED
//   http://www.denso-wave.com/qrcode/faqpatent-e.html
//
//---------------------------------------------------------------------


